### ISSUE TITLE
Thermostat cleanup

### ISSUE THREAD

**Issue by TD22057** [TD22057/insteon-mqtt#107]
@krkeegan: I'm working on cleaning up some of the and making sure everything has correctly formatted doc strings and is using consistent naming conventions and methods.  I started in the network/, handlers/ and mqtt/ directories and will continue on to the devices/ soon.

I ran into a few things I'd like to change in Thermostat so I thought this would be a good place to communicate them.  
- mqtt/Thermostat: 
  - use default lower case for template args ('on' instead of 'ON') to match other devices.  I updated the sample config.yaml to add .upper() so that output is the same.
  - simplified template data specifications (one affect is that it now prefers temp_c over temp_f but I doubt that's a big deal)
- device/Thermostat: 
  - changed all enum values to be upper case to match other enums
- handler/ThermostatCmd: 
  - removed duplicate mode enum - changed code to use Thermostat.Mode

When you have a little time, please take a look at the cleanup branch and let me know if you see any issues with this.  You can ignore most of the diffs (lots of comment updates) - just check the thermostat files (found out that if you Alt-click the collapse file button, it collapse all of them which makes it a lot easier).  Be sure to set the diff to be against the dev branch.  

There is a TODO comment in device/Thermostat.py - I don't think the return statement should be there in the handle_broadcast() method.  At least none of the other devices skips the call to the base class.  That call is where linked devices are notified of the broadcast message so I think that return should be removed.

**Comment by krkeegan** [comment]
My above PR should fix these:

- mqtt/Thermostat
  - template args - whatever is standard is fine.
  - temp_c - this is also fine
- device/Thermostat
  - enum capitalization - also fine
  - handle_broadcast todo - You are right, this should call Base.handle_broadcast().  I fixed this in the commit.
- handler/ThermostatCmd
  - duplicate enum - This isn't actually a duplicate.  If you look at the mapping you will see that it is different.  Not sure how else to handle this, this is an annoyance in the insteon spec that the values are not consistent across different types of requests.  I reverted this change and tried to make my comment less snarky and more descriptive.

Thank you for all of the cleanup.  Hopefully once I get this running in a production environment and not just testing I will start to get the style preferences correct.

I noticed a lot of doc string fixing.  I hate to ask.  Is there a doc string linter we should be using to catch formatting errors?

**Comment by TD22057** [comment]
Thanks.  I'll merge this later tonight.

re linter: Nope.  I tried to use the pylint docstring plugin which claims to understand the google doc style but it doesn't report anything useful.  Badly styled docs don't error and it's overly pedantic about some docs that are fine.  The biggest change was that I had been using:
```
Args:
   variable:   (type) description
Returns:
   (type) description
```
and the correct google style (even though it looks worse and is harder to read when there are a lot arguments) is:
```
Args:
   variable (type):  description
Returns:
   type: description
```

pydocstyle says it checks things, but I don't think it finds putting the type in the wrong place which was the biggest issue.

**Comment by TD22057** [comment]
Please take a look at the latest commit on the cleanup branch.  I added back in the ThermostatCmd.Mode enum but since I think the signal needs to have a standard API, I converted it to a  Thermostat.Mode enum by doing this:

```
local_mode = ThermostatCmd.Mode(mode_nibble)
hvac_mode = self.device.Mode[local_mode.name]
```

I also fixed a few bugs where on_done is set to None in the method def but not checked (I'm not sure it should ever be none - that was an initial idea I had but I think in practice it's always something).  There is a util command that allows this so it doesn't have to check `if on_done` everywhere.

```
def foo( ...,  on_done=None):
   on_done = util.make_callback(on_done)
   ...
   on_done(status, msg, data)
```

**Comment by krkeegan** [comment]
All of those changes look good.

**Comment by TD22057** [comment]
Thanks for the review.  I'm going to run some tests on the cleanup branch and then merge it to dev.
