### ISSUE TITLE
Hassio 0.6.5 update fails

### ISSUE THREAD

**Issue by mooshee** [TD22057/insteon-mqtt#110]
Looks like the new docker images need to be uploaded to https://hub.docker.com/r/lnr0626

`19-02-15 13:08:55 INFO (SyncWorker_0) [hassio.docker.interface] Pull image lnr0626/armhf-insteon-mqtt tag 0.6.5.
19-02-15 13:08:56 ERROR (SyncWorker_0) [hassio.docker.interface] Can't install lnr0626/armhf-insteon-mqtt:0.6.5 -> 404 Client Error: Not Found ("manifest for lnr0626/armhf-insteon-mqtt:0.6.5 not found").`

**Comment by mooshee** [comment]
@lnr0626

**Comment by lnr0626** [comment]
built and pushed, let me know if there's any other issues

**Comment by mooshee** [comment]
Works like a charm.  Thanks!
