### ISSUE TITLE
Can't update to version 0.6.7 on Hass.io

### ISSUE THREAD

**Issue by DBestman** [TD22057/insteon-mqtt#122]
As in the title, I can't update to version 0.6.7 of insteon-mqtt on hassio.  
I believe @lnr0626 needs to update images on https://hub.docker.com/r/lnr0626. 
Thanks!

**Comment by lnr0626** [comment]
give it a try now, should be updated with 0.6.7

**Comment by DBestman** [comment]
That was quick!  Thanks, it works now.
