### ISSUE TITLE
Possible to skip battery devices during refresh_all

### ISSUE THREAD

**Issue by NickWaterton** [TD22057/insteon-mqtt#123]
I have been testing out some new devices with refresh-all. One annoying thing is that refresh_all tries to query my battery powered devices, which will not work - but I have to wait while the 3 attempts are made, and fail. I have a fair number of battery devices (mini remotes and sensors), so this takes some time.

Is there a way to have refresh-all skip battery devices, unless specifically required?

I realize you may want to specifically refresh one device, while you are waking it up, but the majority of the time, refresh all will fail on these devices, and it takes several minutes doing so.

Is there a `refresh_non_battery` command?

Thanks

**Comment by TD22057** [comment]
This is basically the same as #31.  I need to implement some kind of queue in the battery devices such that when the device sends a message to the modem (i.e. it's awake), the messages in the queue are sent.  I'll try and spend some time implementing that next week.

**Comment by TD22057** [comment]
The last update (version >= 0.7.0) to the scene sync code changed the refresh all command to skip battery devices by default.  You can enable battery devices by passing --battery to refresh all.
