### ISSUE TITLE
Having some issues with new Siren device

### ISSUE THREAD

**Issue by NickWaterton** [TD22057/insteon-mqtt#124]
I am writing a new device handler for the Siren device.

I'm having some trouble understanding the broadcast message handling logic for devices.
The Siren, when activated sends out a broadcast alternating fast ON and fast OFF. The duration remaining for the siren is found by doing a direct command 0x19, 0x00 (same as a refresh), the remaining time is returned in cmd2. The only real way to tell if the siren is on or off is to query it, and see if the remaining time is 0 (because it sends ON and OFF when it is sounding) - I think this is intended to flash lights that respond to the broadcast.

So, I have that working, and when the siren broadcasts a Fast ON or OFF, I emit my ON/OFF signal, but I also query the siren to get the remaining time. This seems to work, except when the broadcast is over, after the siren has counted down to zero, I get this:
```
2019-02-22 17:55:01 DEBUG Mqtt: MQTT publish insteon/hallway_siren/state { "state": "OFF", "time": 2, "mode" : fast, "armed" : None } qos=1 ret=0
2019-02-22 17:55:01 DEBUG Base: Found 2 responders in group 1
2019-02-22 17:55:01 DEBUG Base: Group 1 -> ['2b.4f.d0', '3c.4d.4a']
2019-02-22 17:55:01 INFO Base: 3f.3c.01 (hallway_siren) broadcast to 2b.4f.d0 for group 1
2019-02-22 17:55:01 WARNING Base: 3f.3c.01 (hallway_siren) broadcast - device 3c.4d.4a not found
2019-02-22 17:55:01 DEBUG Mqtt: MQTT writing
2019-02-22 17:55:01 INFO Protocol: Read 0x50: Std: 3f.3c.01 Type.ALL_LINK_CLEANUP grp: 01 cmd: 14 01
2019-02-22 17:55:01 DEBUG Protocol: Setting next write time: 1550876101.543602
2019-02-22 17:55:01 DEBUG MsgHistory: Received 0 hops, total 0 for 11 entries
2019-02-22 17:55:01 DEBUG Protocol: Passing msg to write handler: DeviceRefresh handler
2019-02-22 17:55:01 UI Siren: Siren 3f.3c.01 (hallway_siren) duration refresh on=True time remaining=1
2019-02-22 17:55:01 DEBUG Protocol: Write handler finished
2019-02-22 17:55:01 DEBUG Serial: Wrote 8 bytes to serial socket://192.168.100.101:9761
2019-02-22 17:55:01 ERROR Serial: Serial write error from socket://192.168.100.101:9761
Traceback (most recent call last):
  File "/home/nick/Scripts/insteon-mqtt/insteon_mqtt/network/Serial.py", line 228, in write_to_link
    self.signal_wrote.emit(self, data)
  File "/home/nick/Scripts/insteon-mqtt/insteon_mqtt/Signal.py", line 47, in emit
    slot(*args, **kwargs)
  File "/home/nick/Scripts/insteon-mqtt/insteon_mqtt/Protocol.py", line 470, in _msg_written
    assert self._write_queue
AssertionError
2019-02-22 17:55:01 INFO Protocol: Read 0x62: Std: 3f.3c.01, Type.DIRECT, 19 00 ack: True
2019-02-22 17:55:01 WARNING Protocol: No read handler found for message type 0x62: Std: 3f.3c.01, Type.DIRECT, 19 00 ack: True
2019-02-22 17:55:02 INFO Protocol: Read 0x50: Std: 3f.3c.01->2b.4f.d0 Type.DIRECT_ACK cmd: 00 00
2019-02-22 17:55:02 DEBUG Protocol: Setting next write time: 1550876102.324194
2019-02-22 17:55:02 DEBUG MsgHistory: Received 0 hops, total 0 for 11 entries
2019-02-22 17:55:02 WARNING Protocol: No read handler found for message type 0x50: Std: 3f.3c.01->2b.4f.d0 Type.DIRECT_ACK cmd: 00 00
```
This is obviously something to do with my querying the siren for remaining time (doesn't do it if I don't query), so I must be missing something about what happens when a broadcast is over, but a reply is still pending. I'm using a slightly modified `refresh_handler` to get the remaining time, which is called for every broadcast received. It's only a problem at the end though, when the broadcast ends.

I think I'm not understanding what `self.broadcast_done` is used for.

This is the broadcast handler:
```
    def handle_broadcast(self, msg):
        """Handle broadcast messages from this device.
        
        NOTE for Siren, when activated, it sends alternating fast ON and OFF messages

        The broadcast message from a device is sent when the device is
        triggered.  The message has the group ID in it.  We'll update
        the device state and look up the group in the all link
        database.  For each device that is in the group (as a
        reponsder), we'll call handle_group_cmd() on that device to
        trigger it.  This way all the devices in the group are updated
        to the correct values when we see the broadcast message.

        Args:
          msg:   (InptStandard) Broadcast message from the device.
        """
        # ACK of the broadcast - ignore this.
        if msg.cmd1 == 0x06:
            LOG.info("Siren %s broadcast ACK grp: %s", self.addr, msg.group)
            if self.broadcast_done:
                self.broadcast_done()
            self.broadcast_done = None
            return

        # On/off commands.
        elif on_off.Mode.is_valid(msg.cmd1):
            is_on, mode = on_off.Mode.decode(msg.cmd1)
            LOG.info("Siren %s broadcast grp: %s on: %s mode: %s", self.addr,
                     msg.group, is_on, mode)
            
            if mode == on_off.Mode.FAST:
                self._set_is_on(is_on, mode)

        # This will find all the devices we're the controller of for
        # this group and call their handle_group_cmd() methods to
        # update their states since they will have seen the group
        # broadcast and updated (without sending anything out).
        super().handle_broadcast(msg)
```
the time remaining query is done in `_set_is_on` here:
```
    def _set_is_on(self, is_on, mode=on_off.Mode.NORMAL, duration=None):
        """Set the device on/off state.

        This will change the internal state and emit the state changed
        signal.

        Args:
          is_on:   (bool) True if siren is active, False if it isn't.
          mode:    (on_off.Mode): The type of command to send (normal, fast, etc)
        """
        LOG.info("Setting device %s on: %s(%s)", self.label, is_on, mode)
        self._is_on = bool(is_on)
        
        if duration is None:
            self.get_alarm_duration()

        # Notify others that the siren state has changed.
        self.signal_active.emit(self, self._is_on, self._alarm_time_remaining, mode)
```
`self._alarm_time_remaining`, is updated by `self.get_alarm_duration()`, so it lags behind the actual message, but it only gets updated every 2 seconds anyway. `self.get_alarm_duration()` emits the OFF and 0 message when it reads 0 seconds remaining.

This is `self.get_alarm_duration()`
```
    def get_alarm_duration(self, on_done=None):
        """TODO: doc
        gets the remaining alarm duration
        """
        LOG.info("Siren %s getting remaining alarm duration" % (self.label))

        # This sends a refresh ping which will respond w/ the alarm time remaining.
        msg = Msg.OutStandard.direct(self.addr, 0x19, 0x00)
        msg_handler = handler.DeviceRefresh(self, self.handle_duration_request,
                                            force=False, num_retry=1,
                                            skip_db=True)
                                            

        # Send the message to the PLM modem for protocol.
        self.send(msg, msg_handler)
```

and it's message handler
```
    def handle_duration_request(self, msg):
        """Handle replies to the duration refresh command.

        The refresh command reply will contain the current device
        state in cmd2 and this updates the device with that value.

        Args:
          msg:  (message.InpStandard) The refresh message reply.  The current
                device state is in the msg.cmd2 field.
                for the Siren module, this is the
                remaining time for the current
                alert. A value of 0 indicates no
                current alert.
        """
        LOG.ui("Siren %s duration refresh on=%s time remaining=%s", self.label, msg.cmd2 > 0x00, msg.cmd2)

        # Remaining alarm time is stored in cmd2 so update variable
        # to match.
        self._alarm_time_remaining = msg.cmd2
        if msg.cmd2 == 0x00:
            self._set_is_on(is_on=False, duration=self._alarm_time_remaining)    #be careful! do not want to get in a loop...
```
Any pointers would be appreciated.

**Comment by TD22057** [comment]
I don't think sending a status request in the on/off code is a great idea.  Here is what I would think seems like a better way to handle this kind of behavior:

-  The first time in refresh, read the count down timer value and store it in the device.db.meta data dict.  That way it's available from then on.  In the Siren constructor, extract that value from the device.db meta data so it's a member variable in the class.
- When fast on is first seen, activate a timer callback to send a refresh message after the count down value has elapsed (maybe with a 1-2 sec pad).  See Protocolo.send() to see how to do this.

[insteon siren 2868-222dev-112816-en.pdf](https://github.com/TD22057/insteon-mqtt/files/2897296/insteon.siren.2868-222dev-112816-en.pdf)

**Comment by NickWaterton** [comment]
I have this working now. I was wondering though, when you start the insteon-mqtt bridge, the Siren device does not know the internal state of the actual siren (ie default values, flag settings etc). I read these during a refresh, but that isn't done automatically.

Is this how it is supposed to work? I'm asking because it makes some things difficult, for example, alarm delay and alarm duration are stored in one byte, so I can't update the alarm duration without knowing what the delay setting is (and vice versa). On starting up, I don't know either (unless I do a refresh, in which case I read everything, and set the class variables). I don't want to do a read-modify-write thing as that's slow and not very reliable.

I was looking at the new Thermostat device as a possible similar example but I don't see where that automatically reads anything (but the thermostat does send it's own direct messages when items change). Siren doesn't do that, you have to poll it to see if something has changed, like ramp_rate on a dimmer or something.

Is there a periodic poll of devices? how do you handle these sort of changeable default settings?

Thanks.

**Comment by TD22057** [comment]
Sorry - I don't understand.  Did my previous post about using the db meta data not make sense?  I believe it answers your question.

**Comment by NickWaterton** [comment]
No it doesn't really make sense. It would make sense to periodically poll each device to read its internal state and update a database, especially when first started up, but that does not seem to be happening.

I see that the Thermostat uses the db for storing the units value, after `get_status` is called, but that assumes that the units are not changed by an external factor (ie the user), and `get_status` has to be manually run (I don't see anywhere it is called automatically). If you don't do that it just defaults to Fahrenheit.

With most settings, you don't care what the previous value was - ie if you want to turn the LED on or off, or set a dimmer ramp rate, it doesn't matter what it was previously, you just set it to what you want. With more complex devices (like the Siren/Thermostat), it does matter what the previous or other setting was/are, as the effect is different depending on these other/previous settings. Storing those values in a database is not a solution, as they can be changed on the device by external factors. What you have to do is poll the device on startup (refresh) to obtain it's internal state, and work from that.

So I guess that's what I'll do.

**Comment by TD22057** [comment]
That's how it's designed to work.  There are a set of things that are in the category of internal state configuration.  Insteon doesn't report when they change so there is no way to detect them automatically unless you poll.  Polling is a poor solution and isn't the path this library is going to take because it slows everything down.  These config variables don't change very often (or at all) so they aren't a huge concern.  There are any number things that the user can adjust either by hand on the device or using other software that insteon-mqtt won't know about.  That's true of every insteon system - for example if you modify internal state with insteon-mqtt, then the hub won't know about it.  It's impossible to cover those cases unless you polled every device every second to see if they change so why bother?

Here is the solution that I've adopted for this kind of data:

- Start by make changes to internal config through insteon-mqtt so it knows about them.  Implement set_flags() support (see Keypadlinc or other devices for examples) to change internal state so the user can do this.

The second step is to make the device know about this dsata.  This is needed when the behavior of the device as reported by insteon-mqtt needs to change based on that config data.  No current devices do this but Keypadlinc is being modified right now to do this for things like detached load and radio button support.    Obviously the siren needs this as well.  The steps for this are:
- In the constructor, add member variables to store the configuration variables of the device 
   - load those variables from the db meta data if they exist
   - if they don't exist, either wait until you need them to request them or if that's not practical, add a refresh() command to the device constructor to get the data
- In refresh(), if the meta data doesn't exist or if force==True, add a call to get those values
   - In the handler for that call, save the meta data into the class and into the meta data

This way a normal refresh command isn't going to flood the network with a lot of extra commands but the user can still force the config to be reloaded with a force=True flag on the refresh command.  

Also note that the config file has an option to do a refresh on start up every time.  It's up to the user to set this or not and whether you should or not depends on how many devices you have, how often you restart the service, and how important it is for everything to be in the correct state on startup.

**Comment by NickWaterton** [comment]
Ok, I see how you are thinking, and I agree polling is slow, and most of these internal values don't change very often - you usually just set them once and forget them (like LED brightness or ramp rate).

I'll set things up as you say, and see how it works.

**Comment by NickWaterton** [comment]
So, have been saving values in the meta data (just two values), don't need to save lots of stuff.

There looks to be something of a problem with the `set_meta` method, 9or maybe another method is needed).

here is `set_meta`:

```
def set_meta(self, key, value):
        """Set the metadata key to value.
        Used for saving device parameters to persistent storage between
        reboots.
        Args:
          key:    A valid python dictionary key to store the value
          value:  A data type capable of being represented in json
        """
        self._meta[key] = value
        self.save()
```
As you can see `set_meta` actually overwrites the current `key` value with the new value. the new value is a dictionary, but as it overwrites the old value, it means that you have to read the old value, update it with the new dictionary values and then call set_meta. This means you can only use setters and getters for one variable, without a lot of messing around in the device class.

There are two ways around this, either use a new key for each variable (which makes storing the variable as a dictionary somewhat pointless), or add a method to the db say, `update_meta` which would be:

```
def update_meta(self, key, value):
        """Update the metadata key with value.
        Used for saving device parameters to persistent storage between
        reboots.
        Args:
          key:    A valid python dictionary key to store the value
          value:  A data type capable of being represented in json
        """
        self._meta[key].update(value)
        self.save()
```
But then you would probably need a way of deleting a value from the meta data.

For now I can just use a different key for my two values, but this would get unwieldy for more than one or two values.

Which do you think would be the preferred way to go? Add an update method, and use one key, or use a different key for each variable?

**Comment by TD22057** [comment]
That code won't work - the correct test would be `isinstance( value, dict )` not, is the current value None.  Only dict's have an update method.  For now - just use one value at a time.  If it becomes a problem, I'll update API and all the devices with the new API at the same time.

Any chance you'll have a PR for this some time?

**Comment by NickWaterton** [comment]
Yes, I got distracted with some other things (so shelved development for a while), and the siren is a difficult item to get working properly. I actually decided that saving values in the database was not really needed, so I changed direction with it.

I have a test device currently working. I'll try to get a PR for you this week.

**Comment by TD22057** [comment]
No worries - I was just reviewing old issues and checking on the status of them. Whenever you have time is fine.

**Comment by philletourneau** [comment]
@NickWaterton @TD22057 any chance this code made it into a PR? I would love to be able to use my Sirens

**Comment by NickWaterton** [comment]
No, the siren is complicated, and then I finally bought an ISY - which works great and has a python interface. So I switched over to that....

**Comment by TD22057** [comment]
Closing this in favor of the enhancement https://github.com/TD22057/insteon-mqtt/issues/217
