### ISSUE TITLE
Switch ON AssertionError

### ISSUE THREAD

**Issue by dainman** [TD22057/insteon-mqtt#125]
I think that this might be related to issue #119 but since it is closed I am opening a new issue.

I have two switches both OFF commands work without problem but the ON command is getting an Assertion Error.  I am up to date with Master as of this evening

```Insteon    | 2019-02-25 00:47:45 DEBUG Switch: Switch message insteon/46.e0.16/set b'ON'
Insteon    | 2019-02-25 00:47:45 DEBUG MsgTemplate: Input template render: '{ "cmd" : "on" }'
Insteon    | 2019-02-25 00:47:45 INFO Switch: Switch input command: {'cmd': 'on'}
Insteon    | 2019-02-25 00:47:45 INFO Switch: Switch 46.e0.16 cmd: on None
Insteon    | 2019-02-25 00:47:45 ERROR Switch: Invalid switch on/off command: {'cmd': 'on'}
Insteon    | Traceback (most recent call last):
Insteon    |   File "/usr/local/lib/python3.6/site-packages/insteon_mqtt/mqtt/Switch.py", line 231, in _input_on_off
Insteon    |     self.device.set(level=is_on, mode=mode)
Insteon    |   File "/usr/local/lib/python3.6/site-packages/insteon_mqtt/device/Switch.py", line 214, in set
Insteon    |     self.on(group, mode, on_done)
Insteon    |   File "/usr/local/lib/python3.6/site-packages/insteon_mqtt/device/Switch.py", line 144, in on
Insteon    |     assert isinstance(mode, on_off.Mode)
Insteon    | AssertionError```

**Comment by TD22057** [comment]
Sorry - I'm confused.  Why is this different than #119?  Are you still seeing this in the latest version?

**Comment by dainman** [comment]
Yes, I am still seeing this in the master as of today.  Sorry if opening another issue was not the right approach since #119 was closed already.   If you would like I can close this and move my comments over to #119?

**Comment by TD22057** [comment]
Can you double check that you're really synced to the latest master?   The code in insteon_mqtt/mqtt/util.py which parses the on/off commands was changed so it shouldn't return None (the 3rd line in your log).   I just ran off master with a switch using the default config file and I sent an "on" command it and worked fine.  Here's what I did:
```
git co master
git status
> On branch master
> Your branch is up-to-date with 'origin/master'.

[window 1]
./scripts/insteon-mqtt temp-config.yaml start
...

[window 2]
mosquitto_pub -t 'insteon/37.2d.35/set' -m 'off'
[switch turned off]
mosquitto_pub -t 'insteon/37.2d.35/set' -m 'on'
[switch turned on]
```

**Comment by dainman** [comment]
Oh man!   I am sorry... I did do a git pull of master but I forgot to reinstall it (can't believe I did that)


Thanks for the response. I am grateful for your work.  I am installing my insteon network in a new house and this module with Home Assistant has allowed me to replace my ISY.  It was a faithful device but I really hated the admin for it.  Looking forward to helping out if I can
