### ISSUE TITLE
Question: How is the insteon/{{name}}/set suppose to work with complex json?

### ISSUE THREAD

**Issue by jtmoderate876** [TD22057/insteon-mqtt#127]
It seems that no matter what is in my config.yaml, I can only send on and off to insteon-mqtt  insteon/{{name}}/set topics.

For example, even when I configure config.yaml to have:
```
    on_off_topic: 'insteon/{{name}}/set'
    on_off_payload: >
      { "cmd" : "{{value.lower()}}", "mode": "{{mode}}" }
```
Sending a {"cmd" : "off", "mode" : "instant"} does not work while just sending "off" does work.
What is the purpose of the  JSON payload format ( { "cmd" : "{{value.lower()}}", "mode": "{{mode}}" })  for the /set topic (insteon/{{name}}/set).

It seems to be ignored.

**Comment by TD22057** [comment]
That's not how the templates work.  From the docs:
```    # Available variables for templating are:
    #   value = the input payload
    #   json = the input payload converted to json.  Use json.VAR to extract
    #          a variable from a json payload.
```
So putting `{{mode}}` does nothing - that's not a variable that the system knows anything about.  The `json` variable is what you want.  I believe this is what you want:
```
on_off_payload: { "cmd" : "{{json.cmd.lower()}}", "mode" : "{{json.mode.lower)(}}" }
```

**Comment by jtmoderate876** [comment]
Thx Ted - I was totally missing the concept.
All good.
Closing...
