### ISSUE TITLE
thermostat home assistant template

### ISSUE THREAD

**Issue by jbarneson** [TD22057/insteon-mqtt#129]
i realize this is a bit off topic, but i'm thrilled to see this addition. I'm struggling to get HA's mqtt climate item to work with this. Does anyone mind posting an example config of theirs?

**Comment by TD22057** [comment]
It's hard to help without any information.  There is an example in config.yaml already.  You could help by:
1) describe what's working and not working
2) post your config entry
3) turn the logging level to DEBUG and post the logs when you issue the commands that are failing.

**Comment by jbarneson** [comment]
i found your example in the config file. It answered some of the limitations in HA's mqtt climate object. Hope to see some improvements over there. Closing..
