### ISSUE TITLE
Add support for control of status LED brightness

### ISSUE THREAD

**Issue by bfranske** [TD22057/insteon-mqtt#13]
It would be nice if there were a way to adjust the status LED brightness of Switch and Dimmer devices, especially if this was available as a /set MQTT topic. In particular, the status LEDs are very bright in bedrooms at night. You can manually adjust the brightness from the switch but it's a clumsy and error prone procedure. It would be nice to be able to do this from software, even better if it was accessible over MQTT.

**Comment by TD22057** [comment]
This is now available for switches, dimmers, and keypadlinc devices on the dev branch.  The command docs are: https://github.com/TD22057/insteon-mqtt/blob/dev/doc/mqtt.md#get-and-set-operating-flags

Basically you can say: ```insteon-mqtt config.yaml set-flags keypad1 backlight=0x11``` and it will adjust the backlight of the device.  Valid range is 0x11-0xff (17-255).  MQTT command is also available.

**Comment by bfranske** [comment]
Awesome! Thanks, I give it a try soon!

**Comment by bfranske** [comment]
Yes, I can confirm this seems to work on both my dimmers and my keypadlinc. It does not work on my older relays with the yellow LEDs but I'm not sure those support dimming of the status LED. Thanks again!
