### ISSUE TITLE
Cannot change scene topic to use name

### ISSUE THREAD

**Issue by elperepat** [TD22057/insteon-mqtt#130]
Hi!

Just discovered this software and am quite impressed. Seems to work pretty well.

However, I prefer to use {{name}} instead of {{address}} in the topics.

There seem to be a bug in the scene topic handling though. In the config.yaml on lines 231 and 322, the topic template is:

`scene_topic: 'insteon/{{address}}/scene'`

but in insteon_mqtt/mqtt/Switch.py on line 97
the code looks for scene_on_off_topic and not scene_topic:

`self.msg_scene_on_off.load_config(config, 'scene_on_off_topic', 'scene_on_off_payload', qos)`

Same for scene_payload vs scene_on_off_payload on lines 232 and 323 of config.yaml

I didn't do a pull request as I don't know which one you prefer. 

Thanks!

Patrick

**Comment by TD22057** [comment]
Thanks.  Fixed.  Since everyone has the same config file, I updated the code to match the config file.  I had written tests for those but didn't notice the config file was using a different naming scheme.
