### ISSUE TITLE
Invalid IOLinc scene command error

### ISSUE THREAD

**Issue by mikeyrhd** [TD22057/insteon-mqtt#134]
I am using 0.6.7  on hassio and getting the following errors when trying to control IOLinc device:

ERROR IOLinc: Invalid IOLinc scene command: {'cmd': 'on'}
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/insteon_mqtt/mqtt/IOLinc.py", line 185, in _input_scene
    is_on, _mode = util.parse_on_off(data, have_mode=False)
TypeError: 'bool' object is not iterable

It's not making a lot of sense, util.py looks correct and the debug output would make me think it should match the test. Something not right with have_mode=False? This only happens with IOLinc (afaik).

any ideas?
thanks!

**Comment by TD22057** [comment]
Its already fixed on the dev branch.  I'll push out a 0.6.8 release soon.
