### ISSUE TITLE
identify insteonPLM by /dev/serial/by-id

### ISSUE THREAD

**Issue by hoopsta1423** [TD22057/insteon-mqtt#135]
First off, i love this addon. It's so much quicker than using insteon natively with home assistant

Im running hassio 0.90.1 on Ubuntu 16.04 using VMVirtualbox on an always-on win10 server. Hassio doesn't mount SYMLINKs so I can't create static links to my devices (zwave/zigbee stick and insteon PLM). Every once in a while my server restarts after updating and the device addressed change (eg: from /dev/ttyUSB2 to /dev/ttyUSB0). In the hassio config, I can identify the zwave and zigbee device paths using /dev/serial/by-id/xxxxx so those will work even if the devices get mounted in a different order.

Right now, it doesn't appear that I can do the same in the insteonmqtt config and I wonder if it's possible to add the ability to identify the PLM device using /dev/serial/by-id/xxxxxx

Thanks!!

**Comment by TD22057** [comment]
On my Ubuntu 16.04 system /dev/serial/by-id/... are symlinks back to the /dev/tty device.  If I set the port to be equal to the path like this:
```
   port: '/dev/serial/by-id/usb-FTDI_FT232R_USB_UART_AL02YECX-if00-port0'
```
It starts up fine for me.  So what error are you getting when you do that?

**Comment by hoopsta1423** [comment]
welp...nevermind

I could've sworn I was having issues with it when I first tried but it definitely does work now

**Comment by hoopsta1423** [comment]
Reopening this issue, I updated to 0.91.0 this morning and now get errors using this symlink

`Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/serial/serialposix.py", line 265, in open
    self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/serial/by-id/usb-FTDI_FT232R_USB_UART_A901M8M1-if00-port0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/insteon_mqtt/network/Serial.py", line 156, in connect
    self.client.open()
  File "/usr/lib/python3.6/site-packages/serial/serialposix.py", line 268, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 2] could not open port /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_A901M8M1-if00-port0: [Errno 2] No such file or directory: '/dev/serial/by-id/usb-FTDI_FT232R_USB_UART_A901M8M1-if00-port0'
2019-04-04 17:46:03 INFO Mqtt: MQTT device opened 192.168.1.134 1883 with keepalive=30
2019-04-04 17:46:14 ERROR Serial: Serial connection error to /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_A901M8M1-if00-port0`

**Comment by TD22057** [comment]
Please check again.  Those port numbers move around - that's the reason to use something like this: https://askubuntu.com/questions/783357/create-a-symlink-in-dev-using-etc-udev-rules.

The error says "file doesn't exist" which generally means it doesn't actually exist.  The other option is that it's not created when you start up insteon-mqtt.  You may need to adjust the start up order to make sure that usb and serial are up before insteon-mqtt starts.

Changing versions of HA won't change a single thing about insteon-mqtt so updating HA has no affect on whether or not the port is there.

**Comment by hoopsta1423** [comment]
Yea, that's the problem using hassio. It won't mount those symlinks

I've double checked the port and it's correct. It doesn't make sense to me why my zwave/zigbee radios still work this way.

You mention changing the order of startup, is there a way to do that with hassio?

**Comment by TD22057** [comment]
No idea - that's why I don't use it.  When something goes wrong it's a black box.  

I'm sure you're right.  But did you try restarting insteon-mqtt?  I bet it works when you restart - that would indicate it's a startup ordering issue.  I might be able to put some sort of timer in to keep re-trying to open the serial connection until it works.

**Comment by hoopsta1423** [comment]
Yup, I've tried restarting insteon-mqtt, restarting hassio, restarting virtualbox.

It's very strange...I can get into the console via portainer and see the device in /dev/serial/by-id. For whatever reason, insteon-mqtt isn't seeing it. I'm fine using /dev/ttyUSBx for now until I finally move on from hassio

Thanks for your help

**Comment by TD22057** [comment]
The only thing I can think to do at this point is add a retry if the open fails system.  I can put that in and test it locally to at least see if it reconnects to a non-existant sym link at startup.  This is another problem with hassio - it would be nice if you could just download the branch for this and test it but it requires a full rebuild of the docker instances to do anything.  So I'll try and get this in for the next delivery and you can test it then.

**Comment by TD22057** [comment]
FYI - the reconnect system is already in 0.6.8.  Every 10 seconds it will attempt to re-open the serial connection the device.  So even if there is an order problem, it should re-connect at some point and work if that device ID actually exists.  I'm going to close this since it appears to be working fine to me.
