### ISSUE TITLE
Transition hassio build to td22057 repo

### ISSUE THREAD

**Issue by TD22057** [TD22057/insteon-mqtt#137]
Hey @lnr0626 - good news.  It looks like one of the Ubuntu updates for my system has fixed whatever the problem I was having building the hassio docker images.  So I should be able to do the builds whenever a release is made now so you don't have to try and keep doing this.

I tried changing the repo in build-docker.sh and hassio/config.json and everything appears fine and it uploads to my docker area.  Is there anything else that's required to make the move?

**Comment by lnr0626** [comment]
That's great, I believe that changing the repo is it. Lmk if you run into any other issues

**Comment by TD22057** [comment]
Thanks.  I noticed you had made a github repo to hold the docker config files.  Should I do the same or is the regular repo good enough?  (I've never used hass.io obviously).

**Comment by lnr0626** [comment]
Keeping it all local to this repo will be simpler for you to manage as you won't have to update version numbers in multiple places - i'd probably stick to that approach for now as long as it's working
