### ISSUE TITLE
Not getting battery level or dusk/dawn messages

### ISSUE THREAD

**Issue by Louis-Demers** [TD22057/insteon-mqtt#140]
Hi, when i was using Indigo, i was able to get battery level for contact, motion sensors and mini-remotes as well and dusk/dawn of motion sensors, so i know they work. But since switching to insteon-mqtt, i'm not getting any of theses status, only the state. I monitor the mqtt server with a mqtt client to take home assistant out of the equation...  Any clue ?

Thanks in advance for any help. (i'm running all the latest production stuff.)

**Comment by TD22057** [comment]
I own a mini remote and a motion sensor (that doesn't send dusk/dawn) but I've never actually seen one of them (new batteries).  Can you set the debugging level to 10 in the config file, restart the server, and capture the logs?  You could do that around the time a dusk/dawn message would arrive.

Also - did you successfully run pair() on each device?  Those messages are on higher group numbers so they don't show up by default - they have to be paired to the modem.  And they're a bit tricky since they aren't awake.  I've found that I need to start everything up, then push a remote button or trigger the sensor, then quickly (?10 sec?) send a pair command using the command line tool to get it to go through.  At least w/ my mini-remote, I had to do that a couple of times to get it to work.  It only needs to be done once.  

You can also check the link db by running 'print-db' on the modem and the device (when it's awake).  There needs to be links from device group (1-3) as the controller to the modem as the responder or the modem won't report those messages.  (group 1 is motion, 2 is light, 3 is battery).

**Comment by Louis-Demers** [comment]
Ok, my ignorance is gong to be evident.  Since we both have motion and mini-remote, i'll work with that.  here are the db of the modem and the motion sensor.... Most of these links were done by my previous home automation (Indigo) (removed dozens of other entries)

```
bash-4.4# insteon-mqtt  /config/insteon-mqtt/config.yaml print-db modem
Commanding Modem device 3c.4b.24 (modem) cmd=print_db
3c.4b.24 modem database
ModemDb:
  ID: 3f.49.62  grp: 1  type: RESP  data: 0x00 0x00 0x00 (mini remote  8)
  ID: 3f.cf.49  grp: 1  type: RESP  data: 0x00 0x00 0x00 (motion sensor)
  ID: 3f.cf.49  grp: 2  type: CTRL  data: 0x02 0x00 0x00
  ID: 3f.cf.49  grp: 3  type: CTRL  data: 0x03 0x00 0x00
GroupMap
  1 -> ['3f.33.69', '44.8a.14', '3f.47.43', '44.89.29']
  254 -> ['2e.8c.a3', '14.5c.a2', '23.51.73', '3f.33.69', '3f.0b.64', '3f.43.bc', '28.66.35', '14.8a.1c', '14.49.53', '2b.fd.9d', '2b.fa.2e']
  2 -> ['3f.33.69', '3f.cf.49']
  3 -> ['3f.cf.49']
Complete

bash-4.4# insteon-mqtt  /config/insteon-mqtt/config.yaml print-db 3f.49.62
Commanding mini_remote_8 device 3f.49.62 (remote_4) cmd=print_db
3f.49.62 (remote_4) device database
DeviceDb: (delta None)
Unused:
Last:
  0fff: 00.00.00 grp:   0 type: RESP data: 0x00 0x00 0x00 (UNUSED) (LAST)
GroupMap

Complete

bash-4.4# insteon-mqtt  /config/insteon-mqtt/config.yaml print-db 3f.cf.49
Commanding battery_sensor device 3f.cf.49 (int_gf_office_motion) cmd=print_db
3f.cf.49 (int_gf_office_motion) device database
DeviceDb: (delta None)
  0fff: 3c.4b.24 grp:   1 type: CTRL data: 0x03 0x00 0x00
Unused:
Last:
  0ff7: 00.00.00 grp:   0 type: RESP data: 0x00 0x00 0x00 (UNUSED) (LAST)
GroupMap
  1 -> ['3c.4b.24']

Complete
```

Q1) how do i interpret the lines above , i.e. first line,  modem is the responder to 3f.49.62 ?

Q2) I'm able to remove entries in the modem db , i.e. i was able to delete the 2 tel entries and create  2 new responder ones if i use the oneway options

my modem now has
```
  ID: 3f.cf.49  grp: 1  type: RESP  data: 0x00 0x00 0x00
  ID: 3f.cf.49  grp: 2  type: RESP  data: 0x02 0x00 0x00
  ID: 3f.cf.49  grp: 3  type: RESP  data: 0x03 0x00 0x00

```

Q3) i tried to remove and add responder and controller to the device, also tried most commands provided  by your api and about only print-db, get-devices, on and off on already linked switches.  I always get

```
bash-4.4# insteon-mqtt  /config/insteon-mqtt/config.yaml db-add -o 3f.cf.49 3 ctrl modem 3
Commanding battery_sensor device 3f.cf.49 (int_gf_office_motion) cmd=db_add_ctrl_of
Handler timed out 1 of 3 sent: Std: 3f.cf.49, Type.DIRECT, 19 00 
Handler timed out 2 of 3 sent: Std: 3f.cf.49, Type.DIRECT, 19 00 
Handler timed out 3 of 3 sent: Std: 3f.cf.49, Type.DIRECT, 19 00 
Handler timed out - no more retries (3 sent)
ERROR: Command timed out
```
Q4) the join, pair, .... refresh give the similar errors.
```
bash-4.4# insteon-mqtt  /config/insteon-mqtt/config.yaml refresh -f  3f.cf.49
Commanding battery_sensor device 3f.cf.49 (int_gf_office_motion) cmd=refresh
Handler timed out 1 of 3 sent: Std: 3f.cf.49, Type.DIRECT, 19 00 
Handler timed out 2 of 3 sent: Std: 3f.cf.49, Type.DIRECT, 19 00 
Handler timed out 3 of 3 sent: Std: 3f.cf.49, Type.DIRECT, 19 00 
Handler timed out - no more retries (3 sent)
ERROR: Command timed out

```
Also during all these tests, the motion sensor is next to my keyboard so i know it is awake.

**Comment by TD22057** [comment]
Those original links don't look right (at least in my experience).  The necessary links for a motion sensor are:
1) model ctrl -> sensor resp group 1.  This let's the model send commands to the sensor to make changes
2) sensor ctrl group 1 -> modem resp.  Also required for commanding and for sensor to report changes
3) sensor ctrl group 2,3-> modem resp.  Required for dusk/dawn (group 2) and battery (group 3).

The battery sensors fail to respond a lot.  They trigger and sleep very fast so just having there doesn't mean that much.  They also tend to time out and stop responding for some time after triggering.  Normally I have to wait for the motion sensor to reset (it has some timeout where it won't sense motion for some time after triggering), then trigger the sensor, then quickly send it a command.  Usually takes a couple of tries to get it to respond.  Same w/ mini remotes - at least with those pushing a button wakes the remote up.  When I finish #31, message will queue up until the device wakes which will help.

**Comment by Louis-Demers** [comment]
Well, i did a db-add on the modem and its database is now (does it look like it should ?)

```
  ID: 3f.cf.49  grp: 1  type: RESP  data: 0x00 0x00 0x00
  ID: 3f.cf.49  grp: 1  type: CTRL  data: 0x01 0x00 0x00
  ID: 3f.cf.49  grp: 2  type: RESP  data: 0x02 0x00 0x00
  ID: 3f.cf.49  grp: 3  type: RESP  data: 0x03 0x00 0x00

```
and tried multiple times 
```
insteon-mqtt /config/insteon-mqtt/config.yaml db-add int_gf_office_motion 3 ctrl modem 3
Commanding battery_sensor device 3f.cf.49 (int_gf_office_motion) cmd=db_add_ctrl_of
Handler timed out 1 of 3 sent: Std: 3f.cf.49, Type.DIRECT, 19 00 
Handler timed out 2 of 3 sent: Std: 3f.cf.49, Type.DIRECT, 19 00 
Handler timed out 3 of 3 sent: Std: 3f.cf.49, Type.DIRECT, 19 00 
Handler timed out - no more retries (3 sent)
ERROR: Command timed out
```

my sensor still shows this database

```
insteon-mqtt /config/insteon-mqtt/config.yaml print-db int_gf_office_motion
Commanding battery_sensor device 3f.cf.49 (int_gf_office_motion) cmd=print_db
3f.cf.49 (int_gf_office_motion) device database
DeviceDb: (delta 25)
  0fff: 3c.4b.24 grp:   1 type: CTRL data: 0x03 0x00 0x00
Unused:
Last:
  0ff7: 00.00.00 grp:   0 type: RESP data: 0x00 0x00 0x00 (UNUSED) (LAST)
GroupMap
  1 -> ['3c.4b.24']
Complete
```

I'v tried many combination of sleep, wait, trigger sensor without success...
Can you confirm that my modem database now looks the way it should ?

**Comment by TD22057** [comment]
Yes - but the point is that all the entries have to be paired - one on the controller and one on the responder.  The modem is fine because it's always awake.  The entries on the device are wrong.

What I see is that the device is not a responder to the modem for group 1.  That means it was never linked so you can't send it commands to change the database.  You have the link allowing the motion sensor to send data to the modem (group 1) but not the one to allow the modem to send change commands to the sensor.  Do a manual link from the modem -> sensor.  Send a linking command to the modem (or hold the modem set button), then hold the set button on the sensor until it beeps.  That will create the modem->sensor group 1 link.  Then you can send a regular pair command to the sensor to build the missing links (groups 2 and 3).

**Comment by Louis-Demers** [comment]
Thanks, I had tried what you suggest , and tried again without success. both by typing the linking command and by physically pressing modem and device buttons. The device never becomes a responder to the modem. In fact when i print the database of one of my working remote i get 

```
bash-4.4# insteon-mqtt /config/insteon-mqtt/config.yaml print-db remote_3
Commanding mini_remote_8 device 44.8a.14 (remote_3) cmd=print_db
44.8a.14 (remote_3) device database
DeviceDb: (delta None)
Unused:
Last:
  0fff: 00.00.00 grp:   0 type: RESP data: 0x00 0x00 0x00 (UNUSED) (LAST)
GroupMap
Complete

```

yet monitoring my mqtt server i see the button presses. That should not be.

I give up for now. my brain is turning to mush and im getting frustrated. Clearly something is escaping me.

**Comment by TD22057** [comment]
I think what you're seeing just means that the db file that insteon-mqtt has (which basically has no entries) is not what's actually on the device.  So getting refresh to work for that device is the key - once the db is current it will be fine (I think).  I'll try and work on bug #31 later this week - that would allow queuing up a refresh command until the device appears which I believe will make it more reliable to deal with battery devices.

**Comment by krkeegan** [comment]
PR #240 likely solves this.
