### ISSUE TITLE
Registering Hub messages from PLM

### ISSUE THREAD

**Issue by kbsprout** [TD22057/insteon-mqtt#141]
I have a 2245-222 Hub and decided after installing insteon-mqtt that I'd have better luck with the PLM, so I added the 2413U.   The 2413U is working well and I'm getting messages from all the devices that I've listed in config.yaml and paired, whether I control them directly or via the PLM or the mqtt commands.

However, if the devices are controlled via my 2245-222 Hub, the 2413U and insteon-mqtt get no message on the new state of the devices.  Is there a way to setup the Hub and PLM to be paired such that the PLM has a record of all messages being sent by the Hub?  Alternatively, shouldn't the remote device inform the PLM that it's status has changed regardless of how it was changed?

**Comment by TD22057** [comment]
Nope.  AFAIK, Insteon doesn't work like that.  And no - devices don't report state changes that are triggered by scene commands.  That's one of the features of this library is that it keeps track of the scene links and reports the changes even though the devices didn't say they changed.  But it can only do that if the scene trigger goes through the PLM.
