### ISSUE TITLE
Docker images not available for 0.6.8

### ISSUE THREAD

**Issue by dale3h** [TD22057/insteon-mqtt#148]
The latest add-on [config.json](/hassio/config.json) fails to install properly because the last known tagged version of the `lnr0626/{arch}-insteon-mqtt` images is 0.6.7.

**Comment by Louis-Demers** [comment]
I believe the repository is different now...

td22057/{arch}-insteon-mqtt

**Comment by dale3h** [comment]
I saw that repo as well, but noticed the config file still pointed to lnr0626. I don’t use Insteon, so I am unable to test it. I just noticed this problem when someone came to me for help with getting it going.

**Comment by Louis-Demers** [comment]
indeed, i used the following to update to 0.6.8 and imagine future updates will be coming from there as well.

```
{
    "name": "Insteon MQTT",
    "description": "Python Insteon PLM <-> MQTT bridge",
    "slug": "insteon-mqtt",
    "version": "0.6.8",
    "startup": "services",
    "arch": ["armhf"],
    "boot": "auto",
    "auto_uart": true,
    "map": ["config:rw"],
    "options": {},
    "schema": {},
    "image": "td22057/{arch}-insteon-mqtt"
}
```

**Comment by TD22057** [comment]
This is fixed on the dev branch and will be updated when 0.6.9 is released.
