### ISSUE TITLE
Support changing/reporting KeypadLinc button LED states

### ISSUE THREAD

**Issue by TD22057** [TD22057/insteon-mqtt#15]
Support remote changing of KeypadLinc button LED sttes.  Command is an OutExtended with D1 = button, D2=0x09, D3=0x01 (on) or 0x00 (off).

Questions for you: should changing the LED be the same as clicking the button?  Because a different way to achieve this is to just send a simulate group broadcast command (see issue #9) which would then (I think) update the LED state automatically.

Another question (which I probably can't answer until my KeypadLinc arrives): does changing the LED state toggle the internal state of the button?  i.e. normally the button sends an on, then off command (it alternates).  My guess is that if you change the LED state remotely, it will change the next command that get's sent to be the opposite of the LED state.  If that's true, it might make more sense to just trigger the scene.

Thoughts?

**Comment by bfranske** [comment]
> should changing the LED be the same as clicking the button? Because a different way to achieve this is to just send a simulate group broadcast command (see issue #9) which would then (I think) update the LED state automatically.

Yes, I think so. As long as things work as you suggest below it only makes sense to change the status by triggering the scene I think.

> does changing the LED state toggle the internal state of the button?

Like you, I can't answer for certain (unless you have some debug code/procedure you'd like me to try on mine) but I strongly suspect that it is as you suppose and the LED state is simply showing the keypadlinc's internal state for the scene and therefore changing it will change the next command it sends. If this is true it seems that just triggering the scene to update the LED would have the same result and would also update the status on any other devices monitoring that scene which it seems you would want.

**Comment by TD22057** [comment]
OK - thanks.  I'll work on #9 then and we can see if that fixes it.  Hopefully my keypadlinc will show up this week and I can try it out.

**Comment by larizzo** [comment]
Yea I agree I honestly wouldn’t focus on changing LED alone I’d think it makes more sense to control the group/scene and have the LED reflect that. I was originally thinking that just the LED was enough but I think it would confuse most people and cause you to implement two behaviours for the KeypadLinc.

I know when I pair my garage door with my keypad and I open my garage door using the remote the status is updated on my keypad so I assume that it’s receiving a group broadcast and responding by turning on the LED. I could try and capture this it might be easier for you to do it with your own keypad. If you want me to capture that let me know.

**Comment by TD22057** [comment]
FYI - Once again the insteon dev guide is wrong.  According to it, sending 0x2e 0x00 0x03 0x09 0x01 should set the button 3 LED to on.  The message is ACK'ed but nothing happens.  Turns out you have to send only button 0x01 and the field after 0x09 is not what the dev guide says (which is 0=off, 1=on) but the whole LED bit mask.  

The LED bits do control the local scene state.  Say button 3 turned on.  If button 3 is pressed again, it will send an off command.  But if you change the led state to off, then the next button 3 press will send on again.

**Comment by TD22057** [comment]
Added MQTT command:
```
   { "cmd": "set_button_led", "button" : button, "is_on" : true/false }
```
to turn a button (1-8) led on or off.  NOTE: This doesn't "click the button" - that will be handled by scene simulation in #9.  This just changes the LED (and internal on/off) state of the button.

**Comment by larizzo** [comment]
What payload in Home-Assistant can I set to get insteon-mqtt to activate the LED?

**Comment by TD22057** [comment]
There isn't one -  I just realized that I didn't do this very well.  The LED isn't a light - it's the state of the switch.  So I'm going to change the keypadlinc so that it has 7 switches + 1 dimmer or 8 switches and have them all behave the same with MQTT templates and HASS integration.  For a regular switch, calling it directly turns the load on or off but doesn't send out the scene command as if it was clicked.  The keypadlinc should behave the same - so calling button 3 directly turns it "on" (which in this case just turns the LED on) - but doesn't emit the scene.  

Then when I finish #9, each actuator will have two possible command inputs - a direct on/off and a scene on/off which can both be called via MQTT or HASS.

**Comment by larizzo** [comment]
Ahh k that's how I understood you were doing it from the message you wrote. Don't do any work to just turn on the LED (for me anyway) work on #9 unless the code can be reused or it's preliminary. I'm in no rush to get the keypad working. I wish I could help more on the coding part. I'm very new to python, I could maybe start reading the code and see what I can pick up maybe I'll be able to help eventually.

**Comment by TD22057** [comment]
OK - This is now fixed.  I changed the keypadlinc to be a dimmer + 8 buttons (i.e. switches).  The dimmer uses the dimmer configuration values and the buttons use keypadlinc config value that is similar to the switch system.  So sending:
```
topic: insteon/aa.bb.cc/set/3
payload: { "cmd" : "on/off" }
```
will turn the button on or off.  Since buttons have no load, this just turns the LED on and off.

**Comment by larizzo** [comment]
Tested, working well the LED is turning on and off. It doesn't trigger the scene that's attached to that button but as you mentioned that's a future enhancement. Thanks for the great work!
