### ISSUE TITLE
Factory Reset Insteon Devices (Other than Modem)

### ISSUE THREAD

**Issue by house97** [TD22057/insteon-mqtt#152]
Currently, the factory-reset command is supported only on the modem.  In certain circumstances, it would be beneficial to factory reset another device, if possible.
I have no idea if this can be performed by PLM command, but now that initiating remote pairing is possible, a remote factory reset could be a valuable tool.

**Comment by TD22057** [comment]
Sorry, as far as I can see in the docs, there is no remote command to do that.  Feel free to re-open this if you can find the command.
