### ISSUE TITLE
Are Simulated Scenes Leftover Code?

### ISSUE THREAD

**Issue by krkeegan** [TD22057/insteon-mqtt#162]
Is this code:

https://github.com/TD22057/insteon-mqtt/blob/42f3933566fb2bcdbe80de7e6f5ff8ff35ecdea0/insteon_mqtt/device/KeypadLinc.py#L151

Just leftover code?  I see we handle set_button_led for keypadlincs using a direct message.  Using a modem scene to change the leds was an old school way of doing it.  But it wouldn't work as coded up here.  Each individual button would require its own modem scene.  The way it is designed here, the modem scene 0x02 would turn on button_b on all keypadlincs, since they would all be linked to the same scene.

Anyways, just noticed this as I was working.

**Comment by TD22057** [comment]
Agreed.  I'm not sure why I thought that was necessary.  It's now commented out on the dev branch.  I've left it in (but commented out) for now since I don't have a keypadlinc setup for testing.
