### ISSUE TITLE
Add way to adjust ramp rate after link created

### ISSUE THREAD

**Issue by lizaoreo** [TD22057/insteon-mqtt#168]
Per the below post, I'd like to see a way to change this.  I've got some devices that are dimmers that I occasionally use in places (like the Christmas tree) where I want them to just be instant on/off rather than ramping up.

https://community.home-assistant.io/t/new-insteon-plm-modem-integration-option-via-mqtt/34979/95?u=lizaoreo

**Comment by TD22057** [comment]
FYI - you might also want to the look at the device docs page.  If you're using HA, you can send an MQTT command w/ the instant or fast payload option without adjusting the link. https://github.com/TD22057/insteon-mqtt/blob/master/docs/mqtt.md#dimmers

**Comment by TD22057** [comment]
FYI this already appears to work fine.  I had a link from a KeyPadLinc button 5 to a dimmer to go to 50%.  I ran this command:
```
insteon-mqtt config.yaml db-add sw1 1 resp kp1 5 -o --level 255 --ramp 28
```
The -o means one way (i.e. don't change the keypadlinc).  This changed the level and ramp rate to the input values on the dimmer without removing or creating a new entry.
