### ISSUE TITLE
Engine 0 devices fail refresh using Python 3.4

### ISSUE THREAD

**Issue by bubtheengineer** [TD22057/insteon-mqtt#176]
I'm running into a problem getting my Togglelinc devices to successfully pair with the modem using the pair command.  They seem to fail during the device refresh when the device db is seen to be out of sync with the local copy.  There are no json files in the data directory for these devices.

A few details:
- These Togglelincs are from a little old ( circa 2007 )
- Model info shows the following: dev_cat: 0x1, sub_cat: 0x17, firmware: 0x2a
- I've got seven of these devices, and all show the exact same behavior.
- I bought a dual-band dimmer to eliminate the possibility of phase problems or line noise.  I've also put the modem onto the same circuit as the togglelinc and get the same result.
- I am able to manually link the modem and togglelincs using the 'linking' command for the modem and the device buttons.  But this doesn't update the local db.
- I have no problems controlling the togglelincs from the modem after manually linking them.

I've attached the log excerpt from an attempted pair (following a successful join).

[insteon_pair_error.txt](https://github.com/TD22057/insteon-mqtt/files/4020482/insteon_pair_error.txt)

Since I'm able to control these devices even though they fail to pair, I assume the local device db isn't critical, but I'd like to know what is the impact of not having it?

**Comment by TD22057** [comment]
The local device is crucial.  It's what tells insteon-mqtt what other devices are going to change when a scene is triggered.

I ran some tests and it's a bug in Python 3.4.  I might be able to hack a fix around it but it would be better for you to upgrade the version of Python you're using.

**Comment by bubtheengineer** [comment]
Thanks for the quick reply.  I’ll upgrade to a newer version and reply back.

**Comment by bubtheengineer** [comment]
I upgrade to Python 3.7 and the problem is solved.  Thanks again for your help.
