### ISSUE TITLE
Thermostat with Home Assistant

### ISSUE THREAD

**Issue by HerbOtto** [TD22057/insteon-mqtt#177]
I'm relatively new to Home Assistant - has anyone successfully interfaced Insteon-MQTT with it?  I can read status but not having much luck setting temperatures, modes, etc.  The documentation included on the webpages and config.yaml reference params which are not supported by HA (eg. heat_sp_command_topic)

Thanks!
-Herb

**Comment by HerbOtto** [comment]
Had a typo which swapped command and state. Ugh. Closed!

**Comment by HerbOtto** [comment]
Reopened: The issue wasn’t just the typo but rather the format in which Insteon-MQTT wants the temperature for heat_sp_command.  Seems HA sends just the value as payload (67) to the topic but Insteon-MQTT wants a JSON formatted string: {“temp_f”:67}.  I’m probably missing something really obvious here - for you HA experts out there - have you solved this issue?  The HA HVAC “climate” topic doesn’t support a template for temperature set commands.

**Comment by TD22057** [comment]
I think you're missing how the IM input templates work.  They take whatever HA sends and modify it to match up with what IM needs.  If HA sends "67" then that's what's in the `value` variable passed to the template.  So the IM template input of `heat_sp_payload: '{ "temp_f" : {{value}} }'` will replace `{{value}}` with `67` so the resulting input to IM is `{ "temp_f" : 67 }` which is the correct JSON format.

**Comment by HerbOtto** [comment]
Well that was easy - thanks for the info in the local input templates - for some reason I thought they were not working, turned out to be a subtle (yet another) typo in the command topic.  All is well.

Closed - again.
