### ISSUE TITLE
Hass.io PLM Config

### ISSUE THREAD

**Issue by respectTheCode** [TD22057/insteon-mqtt#180]
I am trying to get this setup with hass.io but I can't seem to figure out what I should have the port set to in my config.yaml.

It looks like the only device that the docker container has access to is `/dev/ttyAMA0` but that does not work.

How should this be configured?

**Comment by respectTheCode** [comment]
Ok it was a dumb issue on my end. I had the PLM plugged into the wrong Pi.

For anyone else that stumbles on this... Plug it in before starting Insteon-mqtt and use `/dev/ttyUSB0`. If the PLM isn't plugged in when insteon-mqtt starts you will need to restart it for it to work.

**Comment by krkeegan** [comment]
Ha!  We have all done things like that.  Thanks for admitting it and making us all feel more normal.
