### ISSUE TITLE
Multiple PLMs ... one for MQTT and one for ISY?

### ISSUE THREAD

**Issue by roopesh** [TD22057/insteon-mqtt#190]
Sorry if this isn't the right place to ask this question.  Please redirect me to the appropriate forum.

I have an ISY994i that I plan to continue to use along with HA.  Can I have two PLMs (one for HA/MQTT and one for the ISY) and keep them in sync?

The reason I ask is the Insteon module in HA gets out of sync and is slow.  Wondering if insteon-mqtt will help solve that.

**Comment by TD22057** [comment]
Well AFAIK, this system shouldn't get out of sync and is extremely fast (part of why it was written the way it was).  You can certainly tell IM to talk to one modem but I have no idea if Insteon can support multiple modems on the same network.  It's might work if you link every device to both modems but I have no idea - you'd have to experiment with it yourself.

**Comment by krkeegan** [comment]
I think you could do what Ted says and it would work.  If you use the scenes feature you may need to add the ISY to a bunch of scenes so it will stay updated.

A little and promotion here, I have very good understanding of how insteon works having written insteon code for 7 years now.  So I believe I know all the tricks to keep the communications running smoothly and I would be surprised if insteon-mqtt can't stay in sync.

**Comment by roopesh** [comment]
OK I finally got around to doing this... and here's what I'm running into: forget that it took me far too long to get it up & running (mosquitto issue).
1. I have to add every device to the config.yaml? Is that correct?  I thought maybe I'd be able to just send a slew of join/pair commands.  So everytime I add a device I have to add it to the config.yaml?
2. If I use m ISY994i to turn a device on/off, insteon-mqtt doesn't know about it.  I realize, it makes sense, because my ISY isn't publishing to a MQTT topic.  But that's how I'm getting out of sync...

**Comment by roopesh** [comment]
@TD22057 or @krkeegan Is the suggestion to use scenes to keep everything in sync?

**Comment by krkeegan** [comment]
1. Yes, the way Insteon-MQTT is designed, all devices must be listed in the config.yaml file.  For security reasons, Insteon isn't an auto-discovery platform.  The only alternative is to use the Insteon method of holding the buttons of a device when you want to join it.  Insteon-MQTT doesn't support that method and I wouldn't expect it to be added anytime soon if ever.

2. Yeah, that is the problem of having multiple controllers.  The only answer, and I don't know if ISY994i supports this, is to control the devices from the ISY99 using groups.  For example group 2 would control the kitchen and would also have the Insteon-MQTT modem listed as a responder.  It would then see the command to turn on the kitchen light and update its status.  The ISY99 is probably limited to ~250 groups, so I hope you don't have too many devices.
