### ISSUE TITLE
Finish Implementation of Reason Attribute

### ISSUE THREAD

**Issue by elperepat** [TD22057/insteon-mqtt#199]
I updated insteon-mqtt and just seen that I could get the reason of a change of state. Great! It works for swiches and dimmers, but I can't get it to work completely for keypadlincs:

In my config.yaml I have:

`btn_state_payload: '{ "state": "{{on_str.upper()}}", "reason" : "{{reason}}" }'`

and I get the following mqtt message:

`{ "state": "ON", "reason" : "" }`

I'm expecting "command" like for the switches and dimmers

That's when I send a mqtt command to set the output. When I press the button on the keypadlinc, I get the correct reason: 

`{ "state": "ON", "reason" : "device" }`

Anything I could do to help?

Thanks for the great work!

Patrick

**Comment by krkeegan** [comment]
That is because "reason" hasn't been incorporated everywhere in the code yet.  The default response is an empty string.  The command reason probably hasn't been passed through properly.

It would help if someone went through and diligently looked to see that anyplace where reason could be passed that it is for all of the devices.

**Comment by krkeegan** [comment]
OK, I am starting to look at this.  This reason feature is complicated and maybe not well implemented in spots.  I see why this is happening with the KPL.  I need to think about whether I want to try and implement the reason feature in a better manner or if I should just patch this error.  I will have an answer tomorrow.

**Comment by krkeegan** [comment]
Alright, the reason feature is fully implemented in the code, it should work everywhere now.  Please create an issue if you find a place where it is not working as expected.
