### ISSUE TITLE
bulk editing

### ISSUE THREAD

**Issue by jtmoderate876** [TD22057/insteon-mqtt#200]
What is the best approach to bulk edit everything to use a new PLM?

I'm replacing a failed PLM so I have a lot of linking. I don't have the newer backup @TD22057 referred to here:

> At least w/ the latest update you can back up your whole network which should make it easier to handle a dead modem in the future (not much help now of course).

_Originally posted by @TD22057 in https://github.com/TD22057/insteon-mqtt/issues/77#issuecomment-598265302_

Can I / should I write a big command line batch file (maybe creating it in excel first)?

Or perhaps MQTT somehow but that feels like I would need to write a separate program to process MQTT?

Is there anything else built in that I'm missing?
(I'm thinking batch command line)

**Comment by krkeegan** [comment]
Jeff, I would checkout the import_scenes and sync functions starting here: https://github.com/TD22057/insteon-mqtt/blob/master/docs/scenes.md

That will help you recreate any modem scenes if you have any.  If you don't you can skip that.

Sadly, there is not a join_all and pair_all functions yet.  But we should probably add those.  So yes a batch file would likely work the best.

**Comment by jtmoderate876** [comment]
> Jeff, I would checkout the import_scenes and sync functions starting here: https://github.com/TD22057/insteon-mqtt/blob/master/docs/scenes.md
> 
> That will help you recreate any modem scenes if you have any. If you don't you can skip that.
> 
> Sadly, there is not a join_all and pair_all functions yet. But we should probably add those. So yes a batch file would likely work the best.

Thanks Kevin. I went for it with mostly OK results.
I created a google spreadsheet, put all my Insteon IDs in the B column, duplicated and sorted thos so each appears twice sequentially, copy pasted join and pair commands so every other line says join then pair, then concatenated the command line and the Insteon ID with: (in the C column) =a1&b1

![image](https://user-images.githubusercontent.com/16329872/76809045-8d913000-67b7-11ea-9aa2-f6d9efbd45d8.png)



/opt/insteon-mqtt/bin/insteon-mqtt config.yaml join | aa.bb.cc | /opt/insteon-mqtt/bin/insteon-mqtt config.yaml join aa.bb.cc
-- | -- | --
/opt/insteon-mqtt/bin/insteon-mqtt config.yaml pair | aa.bb.cc | /opt/insteon-mqtt/bin/insteon-mqtt config.yaml pair aa.bb.cc

It took a long time to run (certainly more than an hour, maybe two) against my 70+ devices and I have a few comms errors but for the most part all my node-red to insteon-mqtt is working.

I noticed some keypad "extra" buttons not working so that is probably the scene thing you are talking about that I missed.

I didn't have the dead PLM but perhaps I could have somehow through  insteon-mqtt captured those scenes from the switches? I don't know.

So I have a little more work reconnecting those but must say the bulk edit via batch file worked surprisingly well - given inevitable comms collisions and whatnot when you script for 2 hours straight.

I'm pretty happy - but in hindsight I could have done something to salvage the scenes.

**Comment by jtmoderate876** [comment]
Come to think of it, all the scenes are in the switches, just not the PLM. I should probably download and explore ways to use thos.

**Comment by krkeegan** [comment]
The scenes in the switches should still be in good shape

For the keypadlincs with some buttons not working.  Rerun pair on those devices to fix that.

**Comment by balthisar** [comment]
> Sadly, there is not a join_all and pair_all functions yet. But we should probably add those. So yes a batch file would likely work the best.

While playing around with migrating from Indigo to this solution, I came up with this:

```
#!/usr/bin/perl

use warnings 'all';
use strict;

if ($#ARGV+1 != 1)
{
    print "Usage: $0 config_file.yaml\n";
    exit 1;
}

if (! -r $ARGV[0])
{
    print "$ARGV[0] can't be read or is missing.\n";
    exit 1;
}

my $config = $ARGV[0];
my %hash;
open my $fh, "<", $config  or die "Can't open $config: $!";

while (my $line = <$fh>)
{
    if ($line =~ /^ *- (..\...\...)/)
    {
        $hash{"$1"} = "$1";
    }
}

close $fh;

foreach my $key (keys %hash)
{
    my $command;

    $command = "insteon-mqtt $config join $key";
    print "$command\n";
    system("$command");

    $command = "insteon-mqtt $config pair $key";
    print "$command\n";
    system("$command");
}
```
Given the yaml configuration file that's needed anyway, this will join and pair everything in that file that's not commented out. The regex is a little naive and could be improved, but it handles my case.

Luckily perl is included in the Docker container that seems semi-official; native installs will have Perl, but I'm not sure how hass.io works. For Docker, just exec into the running container.

**Comment by krkeegan** [comment]
There are now `join_all` and `pair_all` commands that should resolve the need for this.
