### ISSUE TITLE
Missing group 1 on import?

### ISSUE THREAD

**Issue by balthisar** [TD22057/insteon-mqtt#203]
When using `import_scenes_all`, I seem to be missing group 1 from my PLM. Per the documentation of the `scenes.yaml` file, this is intentional:

> Each modem scene needs to have its own unique group number from 2-253.

Why is this? I already have group 1 programmed via Indigo  (from which I'm migrating). This isn't an off-by-one error; the rest of the groups' imported numbers match the groups programmed by Indigo, and there's no other mention of the device name or address elsewhere in the file. The group is just missing.

I suppose it's no big deal to re-create this as another group, but I just want to make sure that I'm not misunderstanding something before I go wrecking all my existing scenes.

Thanks.

**Comment by krkeegan** [comment]
Have you configured a scene on group 1?

We don't use group 0 or 1 as a scene which is why the group number list is from 2-253.  Group 0/1 are links from the plm to a device that are made during the 'join' process.  They are links that are necessary to allow us to communicate with i2cs devices.  As a result,  in a well setup system, all i2cs devices are linked to group 0/1 and turning on that scene would have the effect of turning on every i2cs device.

It sounds like maybe Indigo worked around this by possibly only using group 0?  I don't know.

**Comment by balthisar** [comment]
When I import the existing scenes from the PLM, the file is actually populated with group 254 as the controller for everything (seems correct), but these look one-way. I suppose if groups 0 and 1 are handling this and it's hidden from the file, that would make sense.

Maybe Indigo "secretly" remapped group _n_ to 1, just so there would be a group 1, but it seems like I would see it imported into the yaml file, whereas it's just completely missing.

This is interesting... if I use a new `scenes.yaml` populated like this (_only_ this):

```
  - controllers:
      - modem
    responders:
      - basement server room light switch
      - basement storage light switch
```

I would expect to overwrite nearly everything and start fresh. But after `sync_all` and `import_scenes_all` again, my yaml file still has all of the existing groups, as well as that strange group 254. 

I'd rather not factory reset my 2413U and manually re-add 32 devices, but I suppose I could.

**Comment by balthisar** [comment]
Posting this for search, in case others run into similar issues, and then closing. Thanks.
* * *
Having dug into it a bit deeper, the use of groups 0, 1, or 254 are completely arbitrary and up to the entire automation solution to use as they like. Apparently Indigo used 254 for the same purposes as insteon-mqtt uses groups 0 and 1, which probably is a carryover from previous Insteon libraries.

Pretty much other than having to redefine group 1 as another group, things work just like they're supposed to. However…

I still don't know why the example from my previous post didn't overwrite everything, but oh, well.

And re-importing into a fresh scenes.yaml overwrites names given to scenes, but I use scene numbers, even if this is against the advice in the readme. I might open different issues for these; I'm happy to update docs if I have the right information.
