### ISSUE TITLE
WishList: EZFlora Insteon Sprinkler Controller Support

### ISSUE THREAD

**Issue by ejosterberg** [TD22057/insteon-mqtt#204]
On my wish list would be support for the EZFlora Sprinkler controller.
I'd be happy to debug code and may be able to send/loan a spare controller if it's easier.
I've located documentation for the command set used: https://docs.smartenit.com/ezflora/EZFlora_Command_Set.pdf
With some hand holding, I may be able to muster up some Python skill myself, but maybe this would be cleaner and faster to ask someone who knows what their doing.
Love the project here. Thank you for your time and effort. I hope to remove my ISY controller at some point.

**Comment by krkeegan** [comment]
This would be a good amount of work to add.  The EZFlora has a lot of custom functions.  It would certainly require the developer to have access to a device for testing.

I am sorry, but I don't have the desire to do this amount of work for a device I don't use.
