### ISSUE TITLE
get_flags for dimmers, switches?

### ISSUE THREAD

**Issue by balthisar** [TD22057/insteon-mqtt#206]
Any ideas on how to troubleshoot this?

`% insteon-mqtt insteon_mqtt.yaml get-flags 42.d6.b2`

~~~
Commanding dimmer device 42.d6.b2 (office light switch) cmd=get_flags
Device 42.d6.b2 operating flags: 00000000
Operation complete
~~~

I get the same for my switch devices, and the only difference for a hidden door sensor is 00000001 instead of the above.

I would expect to see my current LED levels, ramp rates, etc. Am I wrong about my expectations?

I'm simply trying to catalogue all my current settings, so that I can write a backup-restore script.

**Comment by TD22057** [comment]
The default get flags handler for each device just reports the cmd2 entry - they aren't that smart.  I haven't had any need to get those flags so never bothered to try and code up something to get/set every single feature for each device.

**Comment by krkeegan** [comment]
I am going to condense this with #207.  I should be able to test your PR soon and then we can merge it.
