### ISSUE TITLE
Support ramp rate (feature request)

### ISSUE THREAD

**Issue by balthisar** [TD22057/insteon-mqtt#207]
While playing with #206, I realize that there's currently no support for setting the ramp rate for local control of the switch with set_flags. Dimmers, for example, default to 0.5 seconds.

It looks like this could be a simple addition. Looking at `Dimmy.py`, for example, `set_on_level` looks like a perfect prototype for support. Simply set D2 to 0x05, and the new `set_ramp_level` (or whatever) should just work. That's the Insteon side; I'm not sure how to add support via MQTT or the command line.

I'd be willing to dig into it, but I would only promise support for dimmers, as I have nothing else to test against. It would also take me at least a few weeks, because I'm currently in the midst of a transition from Indigo to Insteon-MQTT + HASS, and I'm not really setup for Python development (no time like the near present to add PyCharm to my repertoire).

Of course, if this isn't a feature you feel worth adding, please feel free to close.

**Comment by krkeegan** [comment]
Support Merged with #235
