### ISSUE TITLE
Remote and mqtt retain

### ISSUE THREAD

**Issue by djfjeff** [TD22057/insteon-mqtt#210]
I am using an older version of insteon-mqtt in my environment and I was looking at upgrading and what changed since my version. One thing that I saw was a way to not retain message for remote button.

This is an issue I currently have because if my daughter turn on her light with the remote and I turn it off with the switch, the ON message from the remote is still retained in MQTT. So if I restart mosquitto or Home Assistant or reboot my server, the light turn back on when reading back the MQTT state.

However, I do not see how to disable the retain message for the remote in the new version. What should I put in my config.yaml for my remote?

**Comment by fancygaphtrn** [comment]
I am not a developer of this, but I have a work around.

I create automation in Home Assistant to call the mqtt service and publish a message any time the light turns on or off.   2 automatons for me.

Example:
`- id: '1556218406416'
  alias: Tod remote sync entity mqtt
  trigger:
  - entity_id: switch.tplink_sw4
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      payload: 'ON'
      qos: 1
      retain: true
      topic: insteon/13.de.d1/state/2
    service: mqtt.publish
`

**Comment by TD22057** [comment]
I think the remote should never mark a message as retained since there is no way to poll the remote's state on startup.  I've updated the code to always send retain=false for the remote messages.
