### ISSUE TITLE
Motion II Sensor - Battery Status

### ISSUE THREAD

**Issue by HerbOtto** [TD22057/insteon-mqtt#214]
I'm trying to get the battery status from the newer Insteon Motion II PIRs - 2844-222.  It doesn't seem to be sending a group message indicating battery status - yet the older 2842-222 is sending battery along w/dusk.  Specifically I'm trying to do this from Home Assistant.  

Is this at all possible? The 2844 unit may require an extended command to request the battery status [0x2e, 0x00].  If Insteon-MQTT doesn't support battery status - I wonder if there is any way to request the unit's battery status via python by sending/receiving the extended command?

**Comment by TD22057** [comment]
I'd say start by making sure the log level is debug and then trip the motion sensor.  See if you can find the battery status anywhere in it.  Maybe I'm just not extracting it.  If that doesn't work, then we'll have to trigger a request to the sensor when we get a message from it (so we know it's awake) to request the battery state.

I don't have one of those devices which makes it impossible for me to try out.

**Comment by HerbOtto** [comment]
My motion sensor II (office_motion) is at: 4a.73.d1.

Here’s the log of activity - note I only receive the state MQTT message when subscribing to Insteon/4a.73.d1/#

2020-08-16 09:15:55 INFO Protocol: Read 0x50: Std: 4a.73.d1 Type.ALL_LINK_CLEANUP grp: 01 cmd: 11 01
2020-08-16 09:15:55 DEBUG Protocol: Setting next write time: 1597583755.356485
2020-08-16 09:15:55 DEBUG MsgHistory: Received 0 hops, total 0 for 3 entries
2020-08-16 09:15:55 INFO Protocol: Read 0x50: Std: 4a.73.d1 Type.ALL_LINK_CLEANUP grp: 01 cmd: 11 01
2020-08-16 09:15:55 DEBUG Protocol: Setting next write time: 1597583755.468160
2020-08-16 09:15:55 DEBUG MsgHistory: Received 0 hops, total 0 for 4 entries
2020-08-16 09:15:55 INFO Broadcast: Handling all link broadcast for 4a.73.d1 'office_motion'
2020-08-16 09:15:55 INFO BatterySensor: BatterySensor 4a.73.d1 broadcast cmd 17 grp: 1
2020-08-16 09:15:55 INFO BatterySensor: Setting device 4a.73.d1 (office_motion) on:True
2020-08-16 09:15:55 INFO BatterySensor: MQTT received on/off change 4a.73.d1 (office_motion) on: True
2020-08-16 09:15:55 DEBUG Mqtt: MQTT publish insteon/4a.73.d1/state ON qos=1 ret=1
2020-08-16 09:15:55 DEBUG Base: Found 1 responders in group 1
2020-08-16 09:15:55 DEBUG Base: Group 1 -> ['49.fa.f8']
2020-08-16 09:15:55 INFO Base: 4a.73.d1 (office_motion) broadcast to 49.fa.f8 for group 1

It seems you see the message but are not publishing the MQTT status?

-Herb

**Comment by krkeegan** [comment]
I will try and see if this work with #282, I suspect it might.

**Comment by krkeegan** [comment]
I poked around a bit.  I am able to find the illuminance data, and previously found the flags for the device.  But I don't immediately see anything that looks like 3.0v, unless they have multiplied the value by 70ish, which is possible.

I will grab my bench power supply over the weekend.  I should be able to figure out the battery data with that.

There is also apparently a thermostat available on the device as well.  I am not sure what the benefit of the illuminance and thermostat values are given that you can only get them when the device is awake.  Unless it remains awake when powered by the 5v usb.

Finally, I also noticed that when using the hub, the hub creates a ctrl record for group 255 on the device.  I wonder if this triggers any sort of heartbeat or battery update from the device.

**Comment by HerbOtto** [comment]
A while back I wrote an experimental plugin for Indigo which tried to sample the battery levels [OpenHAB actually does this].  I had to send the following command when the device woke:

   `reply = indigo.insteon.sendRawExtended(instnAddr, [0x2E, 0x00], waitForExtendedReply=True)`
The battery level was returned as shown...
    `batteryLevel = reply.replyBytes[13]`
The CR123 in the device is 3.3V
   ` volts = float(batteryLevel) * 3.3 / 255.0`

One issue as you mentioned above is the timing of attempting this capture - also it extends the wake time for the device which may adversely affect battery life [not a big trade off if we can get the actual voltage back]. These things run on low voltages - I've replaced units which just died with voltages as low as 1.5(ish).  I typically sent the extended message whenever the device reported motion.

I haven't seen a heartbeat from this device but I could be mistaken.

-H

**Comment by krkeegan** [comment]
Alright, a bench power supply made quick work of this.  D13 is indeed the voltage the values are:
```
D9 = 3.00v
C7 = 2.75v
B0 = 2.50v
A0 = 2.25v
90 = 2.00v
8D = 1.95v
86 = 1.85v
84 = 1.82v (From here down, the LED on the device is amber, indicating a low battery)
82 = 1.79v
80 = 1.75v
```
This results in a formula of `D13/72 = Voltage`, this results in the highest error being .05v and the average error being .007v.  The values below 1.75v start to deviate a bit and the same for values above 3.25.

I did not see any broadcast from the device when dropping the voltage below 1.85v.  But the LED and the other flags identify anything below 1.85v as a low battery.

I note that CR123 nominal voltage should be 3.0v given the LiMnO2 chemistry.  If you are using rechargeable Li-Ion, you will likely see more than 3v.

**Comment by HerbOtto** [comment]
You findings seem to match what i did in the past with Indigo.
Why was this closed - did you post a change to support the battery status? 
Thanks,
-H

**Comment by krkeegan** [comment]
Yup, as noted above, support was merged into the dev branch and will eventually be pushed to master in the next update in the next few days.

**Comment by HerbOtto** [comment]
That’s great news! So are you supporting the current ok/low battery flag or perhaps an additional voltage reading message as well?

**Comment by krkeegan** [comment]
At the moment, it just emits on the standard battery topic with an is_battery_low boolean.  I would like to add voltage to the template for the battery topic, but have not gotten around to that yet.

You can however set your desired "low_voltage" level if you want to alter it.  See the notes in docs/mqtt.md.
