### ISSUE TITLE
KeypadLinc Button States

### ISSUE THREAD

**Issue by respectTheCode** [TD22057/insteon-mqtt#215]
I have recently moved from and ISY over to Insteon MQTT. At this point I have the system basically in the same state I was in on the ISY. That is to say that when turning things on and off from the switch/keypads the keypad leds stay in sync but when controlling from Home Assistant they don't update.

After doing the `import_scenes` I found that my network was a huge mess (I kind of expected this because I was having strange issues). Instead of keeping it, I started a fresh scenes.yml and synced all of my devices. This appears to have worked perfectly.

From reading the default config file it looks like I should be using the `insteon/{{address}}/scene` topic to but this doesn't seem to work correctly. It seems that the scene topic controls all of the responders except for the address that you sent the command to. I have been using the `insteon/{{address}}/set` and `insteon/{{address}}/level` topics but this does not send updates to the other responders.

From the Readme it is implied that it doesn't matter how a device is controlled the scene will always be updated. Again this doesn't appear to be happening.

My question is simply is there a problem with my setup or how should I be controlling devices from HA?

**Comment by TD22057** [comment]
I'm not exactly sure what you're reporting.  To start with, don't include HA in the mix.  It just adds complexity.  Try sending the MQTT messages you want directly and see what happens.  Run with the logs on and see what they report.

Are you saying that you send a KeypadLinc scene command and the scene triggers but the button light on the keypad doesn't update?  If yes, what group?  Group 1 (the main button) is a special case so it matters.  And do you have a dimmer or non-dimmer keypad linc?

There was some extra code int he KPL setup that used to tell the modem to be a controller for each KPL button - that was removed at some point and labeled "not necessary".  Maybe that was a mistake.  I'll try and get my KPL re-installed and test it out.
