### ISSUE TITLE
Add support for Insteon siren device

### ISSUE THREAD

**Issue by philletourneau** [TD22057/insteon-mqtt#217]
Is there a way to configure and use the Insteon Siren with insteon-mqtt?

https://www.insteon.com/siren

**Comment by philletourneau** [comment]
Here's the developer documentation: http://cache.insteon.com/developer/2868-222dev-112816-en.pdf

**Comment by philletourneau** [comment]
I somehow missed the earlier issue where someone was working on Siren integration. Hope that code can be made to work!

**Comment by TD22057** [comment]
Also see: https://github.com/TD22057/insteon-mqtt/issues/124

FYI - I don't own a siren so it will be up to someone else to try and make this work.

**Comment by philletourneau** [comment]
ok...
