### ISSUE TITLE
Need `pip3 install wheel` for Raspbian?

### ISSUE THREAD

**Issue by j3kestrel** [TD22057/insteon-mqtt#22]
I attempting to install this on a clean/new Raspberry Pi 3B with current Raspbian.  When I got to `pip install .` in the Quick Install, I received this error:
```
Collecting MarkupSafe>=0.23 (from Jinja2>=2.1->insteon-mqtt==0.5.2)
  Downloading https://www.piwheels.hostedpi.com/simple/markupsafe/MarkupSafe-1.0-cp35-cp35m-linux_armv7l.whl
Building wheels for collected packages: insteon-mqtt
  Running setup.py bdist_wheel for insteon-mqtt ... error
  Complete output from command /home/tyson/proj/insteon-mqtt/venv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-05lvtxq1-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpy5f28coipip-wheel- --python-tag cp35:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for insteon-mqtt
  Running setup.py clean for insteon-mqtt
Failed to build insteon-mqtt
Installing collected packages: MarkupSafe, Jinja2, paho-mqtt, pyserial, pyyaml, insteon-mqtt
  Running setup.py install for insteon-mqtt ... done
Successfully installed Jinja2-2.10 MarkupSafe-1.0 insteon-mqtt-0.5.2 paho-mqtt-1.3.1 pyserial-3.4 pyyaml-3.12
(venv) tyson@watatic:~/proj/insteon-mqtt$
```
I believe I cleared up the problem with `pip3 install wheel`.  The following attempt at `pip install .` appeared to work.

Note that `python3 -m venv venv` also failed, needing `sudo apt install python3-venv`.

**Comment by TD22057** [comment]
I've updated to docs for this.  What version of python3 is on rasbian?  venv is a standard lib package that has been in all versions >= python 3.3.

**Comment by j3kestrel** [comment]
```
python3 --version
Python 3.5.3
```

**Comment by TD22057** [comment]
Weird.  https://docs.python.org/3/library/venv.html shows venv being built in component since python 3.3.

**Comment by bfranske** [comment]
FYI pip install wheel was also required on a fresh build I just did from the dev branch on Debian 9 as well.

**Comment by crxporter** [comment]
I am FINALLY getting around to moving my setup over to insteon-mqtt but was hit with this error today when trying to install on a Debian VM. I tried all of the various installs listed above - still got the error:

```
error: invalid command 'bdist_wheel'
```

I may try a fresh Ubuntu VM later but have a fresh Pi coming tomorrow - hopefully the install goes better on Raspbian, that will be my production system anyway.
