### ISSUE TITLE
Required hardware

### ISSUE THREAD

**Issue by MrGibbage** [TD22057/insteon-mqtt#223]
Thinking about trying this out. I am confused about a few things in the HW requirements:

> Have an Insteon PLM modem (serial or USB) or one of the older hubs that supports a PML port (usually 9761) on a fixed IP address.

I have an old USB PLM, but I never felt is was very reliable. I have a NEWER ISY994i network hub which does have a fixed IP address. I have no idea what a "PML" port is though, and google isn't very helpful either. Did you mean "PLM" port? The ISY does expose ports 80 & 443, but that's it as far as I know.

Does insteon-mqtt support the ISY994i? The ISY is very reliable and I'd prefer to use it, if possible. Or should I use the USB PLM that I have?

Skip

**Comment by TD22057** [comment]
PLM = power line modem

AFAIK, there is no way to use an ISY for this - it just doesn't allow it.  It's doing the same thing as Insteon-MQTT - talking to the insteon devices directly.  If you want to use Insteon-MQTT, you have to use a PLM modem.  

Some of the older insteon hubs (not ISY - that's a separate box) exposed the underlying PLM modem and port to talk directly to the hardware.  Newer insteon hubs do not do this so.  USB PLM's are generally completely reliable as long as the hardware is working.  Some older models had capacitor issues which would fail after some amount of time.

**Comment by MrGibbage** [comment]
Thanks. It's been a few years since I last used my PLM, but I remember that I needed to "cross link" each device with the PLM. That is, set each device as a responder to the PLM, and set the PLM as a responder to each device. Will I need to do that again?

I just looked and I have two 2413U PLMs. One is v2.0 and the other is v1.0. I guess I'll try the 2.0 first. Thanks again!
