### ISSUE TITLE
Where to enter commands?

### ISSUE THREAD

**Issue by MrGibbage** [TD22057/insteon-mqtt#224]
Total newb question, I'm sure. From the instructions here:
https://github.com/TD22057/insteon-mqtt/blob/master/docs/mqtt.md#required-device-initialization

> From the command line these actions can be performed as follows:
> 
> insteon-mqtt config.yaml join aa.bb.cc
> insteon-mqtt config.yaml pair aa.bb.cc
> insteon-mqtt config.yaml sync aa.bb.cc
> 

Where is this command line? It won't run in the zsh shell. The add-on is started and running without any errors.

**Comment by jkmaxwell** [comment]
I'm having this issue too. There used to be a place in the add-on to do it but it appears to have vanished. When I go to command line, I can't find the binary to link to run it via CLI

This is for those of us who have installed it as an add-on in hassio.

**Comment by krkeegan** [comment]
Home Assistant -> Configuration -> Integrations -> MQTT -> Configuration

**Comment by jkmaxwell** [comment]
i love you. thank you for that @krkeegan. Bookmarked:

https://path.to.hassio/config/mqtt

**Comment by krkeegan** [comment]
#238 also adds a nice feature that I like a lot for Home Assistant use.
