### ISSUE TITLE
DeviceRefresh.msg_recieved.on_done() broken?

### ISSUE THREAD

**Issue by j3kestrel** [TD22057/insteon-mqtt#23]
`DeviceDbGet.msg_received()` calls `on_done()` with a `success` and a string message.  DeviceRefresh.msg_received.on_done() seems to expect `success` as the first arg, but seems to expect the `msg` object to have a `cmd1` attribute.  `set_delta()` will  expect `cmd1` to be a `delta`.  ...but 'msg' is just a string.

I know far to little about the design of this project to guess what was supposed to happen here.

It may be relevant that I have `startup_refresh: True` in `configuration.yaml`.  I get one exception per configured/listed device.

**Comment by TD22057** [comment]
Please install the dev branch until the 0.6 release is out.  If you cloned the repo, you can do `git checkout dev` to switch.  That has been fixed already (and extensively reworked as part of other updates).

**Comment by j3kestrel** [comment]
Much better!  Thank you!
