### ISSUE TITLE
Update Cached DB Delta Upon Modifications to Device DB

### ISSUE THREAD

**Issue by jonsmirl** [TD22057/insteon-mqtt#232]
Why doesn't the DB tag match on the second re-pairing?

1) Device 50.d0.0d db out of date (got 3 vs None), refreshing
2) Device 50.d0.0d db out of date (got 5 vs 3), refreshing
3) Device database is current at delta 5

(venv) jonsmirl@ares:~/aosp/insteon-mqtt$ insteon-mqtt config.yaml join 50.d0.0d
Commanding switch device 50.d0.0d (2nd / green / green closet) cmd=join
Device 50.d0.0d engine version: Unknown, using I2CS
Operation Complete
(venv) jonsmirl@ares:~/aosp/insteon-mqtt$ insteon-mqtt config.yaml pair 50.d0.0d
Commanding switch device 50.d0.0d (2nd / green / green closet) cmd=pair
Switch 50.d0.0d (2nd / green / green closet) refresh on=False
Device 50.d0.0d db out of date (got 3 vs None), refreshing
Entry: 0fff: 3c.48.88 grp:   0 type: RESP data: 0xff 0x1f 0x01
Entry: 0ff7: 3c.48.88 grp:  64 type: RESP data: 0xff 0x1f 0x01
Entry: 0fef: 3c.48.88 grp:   1 type: CTRL data: 0xff 0x1f 0x01
Entry: 0fe7: 53.bf.6b grp:   1 type: CTRL data: 0x03 0x1c 0x01
Entry: 0fdf: 53.bf.6b grp:   1 type: RESP data: 0x00 0x1c 0x01
Entry: 0fd7: 00.00.00 grp:   0 type: RESP data: 0x00 0x00 0x00 (UNUSED) (LAST)
50.d0.0d database download complete
DeviceDb: (delta 3)
  0fdf: 53.bf.6b grp:   1 type: RESP data: 0x00 0x1c 0x01
  0fe7: 53.bf.6b grp:   1 type: CTRL data: 0x03 0x1c 0x01
  0fef: 3c.48.88 grp:   1 type: CTRL data: 0xff 0x1f 0x01
  0ff7: 3c.48.88 grp:  64 type: RESP data: 0xff 0x1f 0x01
  0fff: 3c.48.88 grp:   0 type: RESP data: 0xff 0x1f 0x01
Unused:
Last:
  0fd7: 00.00.00 grp:   0 type: RESP data: 0x00 0x00 0x00 (UNUSED) (LAST)
GroupMap
  1 -> ['3c.48.88', '53.bf.6b']

Device 50.d0.0d received model information: SWITCHED_LIGHTING (0x02): '2477S' (0x2a) 'SwitchLinc Relay (Dual-Band)' firmware: 0x45
Switch paired
(venv) jonsmirl@ares:~/aosp/insteon-mqtt$ insteon-mqtt config.yaml pair 50.d0.0d
Commanding switch device 50.d0.0d (2nd / green / green closet) cmd=pair
Switch 50.d0.0d (2nd / green / green closet) refresh on=False
Device 50.d0.0d db out of date (got 5 vs 3), refreshing
Entry: 0fff: 3c.48.88 grp:   0 type: RESP data: 0xff 0x1f 0x01
Entry: 0ff7: 3c.48.88 grp:  64 type: RESP data: 0xff 0x1f 0x01
Entry: 0ff7: 3c.48.88 grp:  64 type: RESP data: 0xff 0x1f 0x01
Entry: 0fef: 3c.48.88 grp:   1 type: CTRL data: 0xff 0x1f 0x01
Entry: 0fe7: 53.bf.6b grp:   1 type: CTRL data: 0x03 0x00 0x01
Entry: 0fdf: 53.bf.6b grp:   1 type: RESP data: 0xff 0x00 0x01
Entry: 0fd7: 00.00.00 grp:   0 type: RESP data: 0x00 0x00 0x00 (UNUSED) (LAST)
50.d0.0d database download complete
DeviceDb: (delta 5)
  0fdf: 53.bf.6b grp:   1 type: RESP data: 0xff 0x00 0x01
  0fe7: 53.bf.6b grp:   1 type: CTRL data: 0x03 0x00 0x01
  0fef: 3c.48.88 grp:   1 type: CTRL data: 0xff 0x1f 0x01
  0ff7: 3c.48.88 grp:  64 type: RESP data: 0xff 0x1f 0x01
  0fff: 3c.48.88 grp:   0 type: RESP data: 0xff 0x1f 0x01
Unused:
Last:
  0fd7: 00.00.00 grp:   0 type: RESP data: 0x00 0x00 0x00 (UNUSED) (LAST)
GroupMap
  1 -> ['3c.48.88', '53.bf.6b']

Device 50.d0.0d add db already exists for 53.bf.6b grp 1 RESP
Modem add db already exists for 50.d0.0d grp 1 CTRL
Device 50.d0.0d add db already exists for 53.bf.6b grp 1 CTRL
Modem add db already exists for 50.d0.0d grp 1 RESP
Switch paired
(venv) jonsmirl@ares:~/aosp/insteon-mqtt$ insteon-mqtt config.yaml pair 50.d0.0d
Commanding switch device 50.d0.0d (2nd / green / green closet) cmd=pair
Device database is current at delta 5
Switch 50.d0.0d (2nd / green / green closet) refresh on=False
Device 50.d0.0d add db already exists for 53.bf.6b grp 1 RESP
Modem add db already exists for 50.d0.0d grp 1 CTRL
Device 50.d0.0d add db already exists for 53.bf.6b grp 1 CTRL
Modem add db already exists for 50.d0.0d grp 1 RESP
Switch paired
(venv) jonsmirl@ares:~/aosp/insteon-mqtt$

**Comment by krkeegan** [comment]
#56 was never fixed.

This should be an easy fix.
