### ISSUE TITLE
Versions 0.7.3 and 0.7.4 do not appear in Home Assistant add-on config

### ISSUE THREAD

**Issue by tstabrawa** [TD22057/insteon-mqtt#278]
As far as I can tell, this seems to be due to the corresponding docker images not being pushed to hub.docker.com.  For example, the amd64 image shows that it was last updated February 22nd, 2020, when version 0.7.2 was released:

https://hub.docker.com/r/td22057/amd64-insteon-mqtt/tags?page=1&ordering=last_updated

**Comment by krkeegan** [comment]
They do not, the docker images are maintained by someone else based on the
username.

I just install and build the image locally.  If you git checkout into
add-ons/insteon-mqtt and remove the image line from the config.json file
home assistant will build the image locally.

**Comment by tstabrawa** [comment]
Well, the username of the docker images matches the username of this repo.  I assume that means that Ted has been the one to publish the images in the past.  Maybe there's a way to have images auto-generated / pushed when release versions are tagged?

**Comment by krkeegan** [comment]
I think that can be done through actions as well.  We should probably also add a repository.json as outlined here https://developers.home-assistant.io/docs/add-ons/repository too.  Adding a repository to the supervisor seems like a better user experience than ssh-ing the config.json file over manually each time.

**Comment by krkeegan** [comment]
This is a known issue I am working on,  0.7.2 is the latest version that is available on the docker hub.

In the interim, you can build the image locally:
1. Delete the old add on
1. download the entire release and unzip it into /addons/insteon-mqtt
2. edit hassio/config and remove the entire line `"image": "td22057/{arch}-insteon-mqtt"` 
3. delete the trailing comma on the line above what you just deleted
4. Go to supervisor-> add-on store and click the menu button in the top right and select refresh.
5. You should see the insteon-mqtt add-on, click it and install it
6. It may take a few seconds to build.

You should be all set.

**Comment by krkeegan** [comment]
Alright, 0.7.3 and 0.7.4 have been uploaded to the docker hub and should be available for installation or upgrade shortly.

I will need to make some fixes to our docker build process tomorrow, a few things changed since we last used this.
