### ISSUE TITLE
error: invalid choice ' config.yaml

### ISSUE THREAD

**Issue by djryan012** [TD22057/insteon-mqtt#28]
I got thru the entire install process but got an error when running insteon-mqtt start config.yaml. Config is setup correctly, except I think it doesn't know how to talk to my 2014 hub. I can use the insteon terminal just fine but useing the "connectToMyHub()" connection which i couldnt find in insteon-mqtt.
>'def connectToMyHub():
    #connects to my insteon hub modem at pre-defined address
    connectToHub("192.168.0.xxx", 25105, 1000, "hubuser", "hubpassword")

Here is the error i got
>'(insteon-mqtt) insteon@ubuntu:/opt/insteon-mqtt$ insteon-mqtt start config.yaml
usage: insteon-mqtt [-h]
                    config.yaml
                    {start,refresh-all,linking,refresh,get-flags,set-flags,on,set,off,up,down,scene,pair,db-add,db-delete,set-button-led,print-db}
                    ...
insteon-mqtt: error: invalid choice: 'config.yaml' (choose from 'start', 'refresh-all', 'linking', 'refresh', 'get-flags', 'set-flags', 'on', 'set', 'off', 'up', 'down', 'scene', 'pair', 'db-add', 'db-delete', 'set-button-led', 'print-db')

Not sure why getting error if start is a choice and is in command line.

**Comment by TD22057** [comment]
The error is saying that the order is wrong.  I moved the config.yaml before the commands because it made things simpler to run from the command line and missed some references in the docs.
Run `insteon-mqtt config.yaml start`

**Comment by bfranske** [comment]
Just ran across this myself this morning, see my issue #27
