### ISSUE TITLE
Update problem

### ISSUE THREAD

**Issue by MrGibbage** [TD22057/insteon-mqtt#289]
When I try to update to 0.7.4, I get the following error:

20-12-29 13:34:35 ERROR (SyncWorker_0) [supervisor.docker.interface] Can't install td22057/armhf-insteon-mqtt:0.7.4 -> 404 Client Error for http+docker://localhost/v1.40/images/create?tag=0.7.4&fromImage=td22057%2Farmhf-insteon-mqtt: Not Found ("manifest for td22057/armhf-insteon-mqtt:0.7.4 not found: manifest unknown: manifest unknown").

I have updated the addons/insteon-mqtt with the new 0.7.4 update and rebooted a couple of times.

**Comment by krkeegan** [comment]
Sorry yes this is a known issue I am working on,  0.7.2 is the latest version that is available on the docker hub.

In the interim, you can build the image locally:
1. Delete the old add on
1. download the entire release and unzip it into /addons/insteon-mqtt
2. edit hassio/config and remove the entire line `"image": "td22057/{arch}-insteon-mqtt"` 
3. delete the trailing comma on the line above what you just deleted
4. Go to supervisor-> add-on store and click the menu button in the top right and select refresh.
5. You should see the insteon-mqtt add-on, click it and install it
6. It may take a few seconds to build.

You should be all set.

I am closing this in favor of #278

**Comment by krkeegan** [comment]
Alright, 0.7.3 and 0.7.4 have been uploaded to the docker hub and should be available for installation shortly.

I will need to make some fixes to our docker build process tomorrow, a few things changed since we last used this.
