### ISSUE TITLE
Can command with insteon/command/{{addr}} but not insteon/{addr}/set

### ISSUE THREAD

**Issue by tommycw1** [TD22057/insteon-mqtt#291]
Hello,

Been using Insteon for many years under openHAB and am exploring using this bridge and MQTT rather than the native openHAB Insteon binding.

I have installed this bridge and have several lights up and running.

An example light I have is this:

from config.yaml

```
# Dimming devices (outlets, wall switches, lamp modules, etc).
    dimmer:
      - 3D.F7.A1: 'Computer Room'
```

When I physically turn off/on the dimmer switch I get status reported in the log:

```
2020-12-30 17:21:29 INFO Protocol: Read 0x50: Std: 3d.f7.a1 Type.ALL_LINK_BROADCAST grp: 01 cmd: 13 00
2020-12-30 17:21:29 INFO Broadcast: Handling all link broadcast for 3d.f7.a1 'computer room'
2020-12-30 17:21:29 INFO Dimmer: Dimmer 3d.f7.a1 broadcast grp: 1 on: False mode: normal
2020-12-30 17:21:29 INFO Dimmer: Setting device 3d.f7.a1 (computer room) on=0 normal device
2020-12-30 17:21:29 INFO Dimmer: MQTT received level change 3d.f7.a1 (computer room) level: 0 device
2020-12-30 17:21:29 INFO Base: 3d.f7.a1 (computer room) broadcast to 40.d1.6e for group 1
2020-12-30 17:21:29 INFO Protocol: Read 0x50: Std: 3d.f7.a1 Type.ALL_LINK_CLEANUP grp: 01 cmd: 13 01
2020-12-30 17:21:29 INFO Protocol: Read 0x50: Std: 3d.f7.a1 Type.ALL_LINK_CLEANUP grp: 01 cmd: 13 01
2020-12-30 17:21:29 INFO Broadcast: Handling all link broadcast for 3d.f7.a1 'computer room'
2020-12-30 17:21:29 INFO Dimmer: Dimmer 3d.f7.a1 broadcast grp: 1 on: False mode: normal
2020-12-30 17:21:29 INFO Dimmer: Setting device 3d.f7.a1 (computer room) on=0 normal device
2020-12-30 17:21:29 INFO Dimmer: MQTT received level change 3d.f7.a1 (computer room) level: 0 device
2020-12-30 17:21:29 INFO Base: 3d.f7.a1 (computer room) broadcast to 40.d1.6e for group 1
2020-12-30 17:21:30 INFO Protocol: Read 0x50: Std: 3d.f7.a1 Type.ALL_LINK_BROADCAST grp: 01 cmd: 06 00
2020-12-30 17:21:30 INFO Broadcast: Handling all link broadcast for 3d.f7.a1 'computer room'
2020-12-30 17:21:30 INFO Dimmer: Dimmer 3d.f7.a1 broadcast ACK grp: 1
2020-12-30 17:21:31 INFO Protocol: Read 0x50: Std: 3d.f7.a1 Type.ALL_LINK_BROADCAST grp: 01 cmd: 11 00
2020-12-30 17:21:31 INFO Broadcast: Handling all link broadcast for 3d.f7.a1 'computer room'
2020-12-30 17:21:31 INFO Dimmer: Dimmer 3d.f7.a1 broadcast grp: 1 on: True mode: normal
2020-12-30 17:21:31 INFO Dimmer: Setting device 3d.f7.a1 (computer room) on=255 normal device
2020-12-30 17:21:31 INFO Dimmer: MQTT received level change 3d.f7.a1 (computer room) level: 255 device
2020-12-30 17:21:31 INFO Base: 3d.f7.a1 (computer room) broadcast to 40.d1.6e for group 1
2020-12-30 17:21:31 INFO Protocol: Read 0x50: Std: 3d.f7.a1 Type.ALL_LINK_CLEANUP grp: 01 cmd: 11 01
2020-12-30 17:21:31 INFO Protocol: Read 0x50: Std: 3d.f7.a1 Type.ALL_LINK_BROADCAST grp: 01 cmd: 06 00
2020-12-30 17:21:31 INFO Broadcast: Handling all link broadcast for 3d.f7.a1 'computer room'
2020-12-30 17:21:31 INFO Dimmer: Dimmer 3d.f7.a1 broadcast ACK grp: 1
```
and via mqtt (note I added in the mode in the topic)

```
insteon/3d.f7.a1/normal/state
{ "state" : "OFF", "brightness" : 0 }

insteon/3d.f7.a1/normal/state
{ "state" : "ON", "brightness" : 255 }
```

I can also command the light off/on via mqtt (leaving out credentials)

```
mosquitto_pub -h 192.168.1.200 -t "insteon/command/3D.F7.A1" -m '{ "cmd" : "off" }'
mosquitto_pub -h 192.168.1.200 -t "insteon/command/3D.F7.A1" -m '{ "cmd" : "on" }'
```

What I've noticed is that in the docs it is stated that the topic 

`insteon/command/3D.F7.A1`

should really only be used form the command line and that all home automation should use 

`insteon/3D.F7.A1/set`

for switching 

or

`insteon/3D.F7.A1/level`

to set a specific dim level.

the issue I have is that sending 

`mosquitto_pub -h 192.168.1.200 -t "insteon/3D.F7.A1/set" -m '{ "cmd" : "off" }'`
or
`mosquitto_pub -h 192.168.1.200 -t "insteon/3D.F7.A1/set" -m '{ "cmd" : "on" }'`
or
`mosquitto_pub -h 192.168.1.200 "insteon/3D.F7.A1/level" -m '{ "cmd" : "off", "level" : 0 }'`
or
`mosquitto_pub -h 192.168.1.200 "insteon/3D.F7.A1/level" -m '{ "cmd" : "on", "level" : 255 }'`

produce any change to the device, and also nothing in the log - even with the log level set to debug:

I can see that insteon<->mqtt has subscribed to these topics from my mosquitto broker's log:

```
1609367556: Received SUBSCRIBE from insteon-mqtt
1609367556: 	insteon/3d.f7.a1/set (QoS 1)
1609367556: Sending SUBACK to insteon-mqtt
1609367556: Received SUBSCRIBE from insteon-mqtt
1609367556: 	insteon/3d.f7.a1/level (QoS 1)
1609367556: Sending SUBACK to insteon-mqtt
1609367556: Received SUBSCRIBE from insteon-mqtt
1609367556: 	insteon/3d.f7.a1/scene (QoS 1)
```

The dimmer section of my config.yaml seems correct and all I've changed in it was adding mode to the state topic, I haven't modified the command topics at all:

```
dimmer:
    # Output state change topic and payload.  This message is sent
    # whenever the device state changes for any reason.  Available
    # variables for templating are:
    #   address = 'aa.bb.cc'
    #   name = 'device name'
    #   on = 0/1
    #   on_str = 'off'/'on'
    #   level_255 = 0-255
    #   level_100 = 0-100
    #   mode = 'normal'/'fast'/'instant'
    #   fast = 0/1
    #   instant = 0/1
    #   reason = 'device'/'scene'/'command'/'refresh'/'...'
    state_topic: 'insteon/{{address}}/{{mode}}/state'
    state_payload: >
            { "state" : "{{on_str.upper()}}", "brightness" : {{level_255}} }

    # Manual mode (holding down a button) is triggered once when the button
    # is held and once when it's released.  Available variables for
    # templating are address (see above), name (see above), and:
    #   manual_str = 'up'/'off'/'down'
    #   manual = 1/0/-1
    #   manual_openhab = 2/1/0
    #manual_state_topic: 'insteon/{{address}}/manual_state'
    #manual_state_payload: '{{manual_str.upper()}}'

    # Input on/off command.  Similar functionality to the cmd_topic but only
    # for turning the device on and off.  If reason is input, is will be
    # passed through to the state_payload.  The output of passing the payload
    # through the template must match the following:
    #   { "cmd" : "on"/"off", ["mode" : 'normal'/'fast'/'instant'],
    #             ["fast" : 1/0], ["instant" : 1/0], ["reason" : "..."] } }
    # Available variables for templating are:
    #   address = 'aa.bb.cc'
    #   name = 'device name'
    #   value = the input payload
    #   json = the input payload converted to json.  Use json.VAR to extract
    #          a variable from a json payload.
    # NOTE: this isn't used by the HA example above - it's only useful when
    # treating the dimmer as an on/off switch and sending ON/OFF payloads
    on_off_topic: 'insteon/{{address}}/set'
    on_off_payload: '{ "cmd" : "{{value.lower()}}" }'

    # Input dimming on/off command.  Similar functionality to the cmd_topic
    # but only for turning the device on and off and setting the level.  If
    # reason is input, is will be passed through to the state_payload.  The
    # output of passing the payload through the template must match the
    # following:
    #   { "cmd" : "on"/"off", "level" : LEVEL,
    #                         ["mode" : 'normal'/'fast'/'instant'],
    #                         ["fast" : 1/0], ["instant" : 1/0] }
    # where:
    #   LEVEL = 0->255 dimmer level
    # Available variables for templating are:
    #   address = 'aa.bb.cc'
    #   name = 'device name'
    #   value = the input payload
    #   json = the input payload converted to json.  Use json.VAR to extract
    #          a variable from a json payload.
    level_topic: 'insteon/{{address}}/level'
    # NOTE: HASS JSON switch doesn't send brightness in some cases
    # when actuated so handle that here in the template code.  The
    # other HASS MQTT options also have this problem.
    level_payload: >
       { "cmd" : "{{json.state.lower()}}",
         "level" : {% if json.brightness is defined %}
                      {{json.brightness}}
                   {% else %}
                      255
                   {% endif %} }

    # Scene on/off command.  This triggers the scene broadcast on the switch
    # in the same way clicking the button would.  The inputs are the same as
    # those for the on_off topic and payload.
    scene_topic: 'insteon/{{address}}/scene'
    scene_payload: '{ "cmd" : "{{value.lower()}}" }'
```

I'm not sure what I am missing here and with noting in the log, I'm not sure how to debug.

I was working around this by using the insteon/command topic in my openHAB integration but when I tried to integrate my keypad there seems to be no way to command any of the scene buttons with this workaround.

**Comment by krkeegan** [comment]
Hmm, that should definitely cause an error. I suspect StdErr is being redirected somewhere else, possibly to the screen?  Anyways, templating can be confusing, I suspect this is a common mistake.  In short the commands you want are:

`mosquitto_pub -h 192.168.1.200 -t "insteon/3D.F7.A1/set" -m 'off'`
and
`mosquitto_pub -h 192.168.1.200 "insteon/3D.F7.A1/level" -m '{ "state" : "on", "brightness" : 128 }'`

The instructions in what you posted above are correct, but remember, the input templates for `set` and `level` are for converting what is sent in the payload into what the program requires.  They allow you to convert nearly any payload into what the program requires.  They contain everything you need to figure out what your payload should contain, but they are not a template of your payload, they are a template for what the program expects.  

So let's take this section and focus on it:
```
    # Input on/off command.  Similar functionality to the cmd_topic but only
    # for turning the device on and off.  If reason is input, is will be
    # passed through to the state_payload.  The output of passing the payload
    # through the template must match the following:
    #   { "cmd" : "on"/"off", ["mode" : 'normal'/'fast'/'instant'],
    #             ["fast" : 1/0], ["instant" : 1/0], ["reason" : "..."] } }
    # Available variables for templating are:
    #   address = 'aa.bb.cc'
    #   name = 'device name'
    #   value = the input payload
    #   json = the input payload converted to json.  Use json.VAR to extract
    #          a variable from a json payload.
```

Note the phrase __The output of passing the payload through the template must match the following__
`{ "cmd" : "on"/"off", ["mode" : 'normal'/'fast'/'instant'], ["fast" : 1/0], ["instant" : 1/0], ["reason" : "..."] } }`

The template you have by default is `on_off_payload: '{ "cmd" : "{{value.lower()}}" }'`

Breaking that down, we see that `value = the input payload`, as described in the comments. So, the resulting output from the template will be `{"cmd" : "<whatever you send in payload in lower case>"}`  Since cmd requires "on" or "off", your payload needs to be `on` or `off` case insensitive.

Moving on to the level template it is defined as 
```
{ "cmd" : "{{json.state.lower()}}",
         "level" : {% if json.brightness is defined %}
                      {{json.brightness}}
                   {% else %}
                      255
                   {% endif %} }
```

Breaking that down, we see that `json = the input payload converted to json. Use json.VAR to extract a variable from a json payload.`  In the template, I see json variables for __state__ and __brightness__ so you need to send those in your json object.

**Comment by tommycw1** [comment]
Thanks for the quick reply!

I have my log set to:

```
logging:
  # 10=DEBUG, 20=INFO, 30=WARNING, 40=ERROR
  level: 20

  # Print messages to the screen.
  screen: False

  # Print messages to a file.
  file: /var/log/insteon_mqtt.log
```


> In short the commands you want are:
> `mosquitto_pub -h 192.168.1.200 -t "insteon/3D.F7.A1/set" -m 'off'`
> and
> `mosquitto_pub -h 192.168.1.200 -t"insteon/3D.F7.A1/level" -m '{ "state" : "on", "brightness" : 128 }'`

I tried both of these commands and neither of these produce changes on the device or any output to /var/log/insteon_mqtt.log.  I did verify these are hitting the mqtt broker and verified my set up still works with 

`mosquitto_pub -h 192.168.1.200 -t "insteon/command/3D.F7.A1" -m '{ "cmd" : "off" }'`

**Comment by krkeegan** [comment]
Sorry, I didn't realize you also had a capitalization issue too:

`mosquitto_pub -h 192.168.1.200 -t "insteon/3d.f7.a1/set" -m 'off'`

`mosquitto_pub -h 192.168.1.200 -t"insteon/3d.f7.a1/level" -m '{ "state" : "on", "brightness" : 128 }'`

**Comment by tommycw1** [comment]
> had a capitalization issue too:

Yep, that was it!  Thanks for the help.

Interesting that using the set and level MQTT topics, the unit address is case sensitive but using the insteon/command topic, the address is not case sensitive.
