### ISSUE TITLE
insteon-mqtt entities

### ISSUE THREAD

**Issue by MrGibbage** [TD22057/insteon-mqtt#304]
When I go to home-assistant->Configuration->Entities, my insteon lights do not show up there. I can see all of my security system sensors, and my google home devices, etc, but no lights. This causes a problem, because nabucasa home assistant cloud can't see them. Similarly, I don't think I can add insteon-mqtt devices to a Lovelace dashboard because they don't show up as entities.

I thought if I added the mqtt integration, that would enable my mqtt devices to show up as entities in HASS, but it seems that integration is really for auto-discovery of mqtt devices??? 

Ultimately, I think my question is "How do I get my insteon devices to show up as entities in Home Assistant?"

By the way, I do know about the separate Insteon cloud integration. I've tried it and it works. But I'd rather get this all working over MQTT if possible so I can ditch the cloud on this.

**Comment by krkeegan** [comment]
I don't use Nabu Casa, but I would be very surprised if that is the only way you can add items.  Again, I would check in the HA forums, perhaps ask about manually adding devices to nabu casa?

Also, again please if you are asking for support questions, please use the [Discussions](https://github.com/TD22057/insteon-mqtt/discussions) page.  That way any answer will remain for others to see.
