### ISSUE TITLE
KPLs aren't receiving commands

### ISSUE THREAD

**Issue by MrGibbage** [TD22057/insteon-mqtt#317]
I think I got all of my "timed-out" errors fixed from yesterday. I haven't seen a single one today. But now I am having a different problem with my KPLs.
I have two KPLs and they are both having this problem. I have joined/paired them, but when I send a command to them, they don't receive them. Nothing in the logs at all.
Here's a link to a screenshot of MQTT explorer:
https://imgur.com/EdJVSyx
```
(reverse order)

insteon/4c.f9.cb/level/1
{ "state" : "ON" }
insteon/command/4c.f9.cb
{ "cmd" : "pair" }
insteon/command/4c.f9.cb
{ "cmd" : "join" }
```
As you can see, I just joined/paired my KPL, but when I send the ON command to the level topic, nothing happens in the logs at all. It's like I'm sending it to the complete wrong address or something. But when I physically press the paddle, the changes do show up in the state topic. Of course, the physical light isn't responding either.

I'd paste the logs, but there's nothing to show. When I send the command nothing shows up in the log.

Any ideas? My money's on I'm doing something stoopid.

**Comment by krkeegan** [comment]
If you don't see anything in the log it means that the MQTT listener is not listening to the topic you wrote to.  Looking at the default config for the KPL topic is looks like
```
dimmer_level_topic: 'insteon/{{address}}/set/1'
```

Not sure why the different, but you want to use `insteon/4c.f9.cb/set/1`

**Comment by MrGibbage** [comment]
Yep, that was it. 

I'm trying to be more self-sufficient, but I guess I'm not there yet. I read the documentation from here:
https://github.com/TD22057/insteon-mqtt/blob/master/docs/mqtt.md#KeypadLinc

And it said to use /level/1 for dimmer control. Am I reading that wrong? I do see where it says to use /set/1 for on-off state change, which I had overlooked. By the way, I am sending { "state" : "ON", "brightness", NNN } to the /set/1 topic and it works fine, which if I am reading that section correctly, would not be the correct way to do it. Good chance I don't know what I'm doing.

I am really, REALLY appreciating your help!!! I hope that I am not too much of a pain. I think in another day or two, I should have everything working.

**Comment by krkeegan** [comment]
Nope you are correct, the documentation is wrong.

No problem.

**Comment by krkeegan** [comment]
Well, or the default in config.yaml is wrong, one of the two.
