### ISSUE TITLE
sync_all and now I have multiple scenes with the same group number

### ISSUE THREAD

**Issue by MrGibbage** [TD22057/insteon-mqtt#321]
I think I must have done something wrong. I was editing my scenes.yaml file and added some new scenes. I put all of the new scenes after the last numbered scene. But when I ran sync_all, I now have all of the new scenes with the same group number. I don't suppose I can just go in and edit those numbers can I? Or should I run sync_all again? Or something else?

In the future, should I only add one scene at a time to prevent that from happening?

**Comment by krkeegan** [comment]
Hmm, its possible that the code for generating a new group # isn't incrementing when assigning the numbers.  In that case, adding multiple new modem controlled scenes without group numbers would put them all in the next available group.

Let me look into that.

**Comment by MrGibbage** [comment]
Thanks. If I need to delete everything off the modem and start over, it's not a big deal. I'm still very much getting things set up.

**Comment by krkeegan** [comment]
PR #326 should fix that.  You don't have to wipe your modem, but you will need to revert those changes in scenes.yaml.  Likely drop the single new scene that was added that was an amalgamation of all of them.  And then re-add the new ones.

**Comment by krkeegan** [comment]
I thought of another bug scenario last night.  Not sure if you would have encountered it yet, but I pushed a new commit which will also fix that issue.
