### ISSUE TITLE
KeypadLinc dimmer vs switch and "button 1"

### ISSUE THREAD

**Issue by j3kestrel** [TD22057/insteon-mqtt#33]
There are two types of KeypadLinc, a dimmer (2486D) and a switch (2487S):
http://cache.insteon.com/pdf/2486D.pdf
http://cache.insteon.com/pdf/2487S.pdf

When using the switch, the returned state for button 1 includes a brightness in the data and no button number in the topic name.

```
insteon/15.63.c5/state { "state" : "ON", "brightness" : 255 }
insteon/15.63.c5/state/6 ON
insteon/15.63.c5/state/6 OFF
insteon/15.63.c5/state { "state" : "OFF", "brightness" : 0 }
```

Based on the KeypadLinc documentation, I expected all topics to include a button.  Button one does respond to topics with a button number:
```
insteon/15.63.c5/set/1 ON
insteon/15.63.c5/state { "state" : "ON", "brightness" : 255 }
```
It does not respond to a topic with no button number.

The KeypadLinc is derived from Dimmer support.
* Should the switch version respond as dimmer or should a switch or be a different class?
* Should button 1 include its button number in its topic?

I originally jumped into this with the intent of fixing it and submitting a pull request, but I'm not sure what the intent is.

I suspect that this issue has been there for a while, but I didn't notice because the system does respond to commands and my system has limited sensitivity to these switches that we don't use too often.

**Comment by j3kestrel** [comment]
I'm not certain, but I suspect that this happened in response to testing a set command with no group/button number in the topic?

```
Feb 11 14:13:41 watatic insteon-mqtt[29348]: 2018-02-11 14:13:41 DEBUG Dimmer: Dimmer 15.63.c5 ACK: Std: 15.63.c5->49.f7.37 Type.DIRECT_ACK cmd: 11 ff
Feb 11 14:13:41 watatic insteon-mqtt[29348]: 2018-02-11 14:13:41 INFO Dimmer: Setting device 15.63.c5 (gr_south_valance) on=255
Feb 11 14:13:41 watatic insteon-mqtt[29348]: 2018-02-11 14:13:41 INFO Dimmer: MQTT received level change 15.63.c5 (gr_south_valance) = 255
Feb 11 14:13:41 watatic insteon-mqtt[29348]: 2018-02-11 14:13:41 DEBUG Mqtt: MQTT publish insteon/15.63.c5/state { "state" : "ON", "brightness" : 255 } qos=1 ret=1
Feb 11 14:13:41 watatic insteon-mqtt[29348]: 2018-02-11 14:13:41 DEBUG Protocol: Write handler finished
Feb 11 14:13:41 watatic insteon-mqtt[29348]: 2018-02-11 14:13:41 DEBUG Mqtt: MQTT writing
Feb 11 14:17:24 watatic insteon-mqtt[29348]: Traceback (most recent call last):
Feb 11 14:17:24 watatic insteon-mqtt[29348]:   File "/opt/insteon-mqtt/bin/insteon-mqtt", line 5, in <module>
Feb 11 14:17:24 watatic insteon-mqtt[29348]:     status = insteon_mqtt.cmd_line.main()
Feb 11 14:17:24 watatic insteon-mqtt[29348]:   File "/opt/insteon-mqtt/lib/python3.5/site-packages/insteon_mqtt/cmd_line/main.py", line 266, in main
Feb 11 14:17:24 watatic insteon-mqtt[29348]:     return args.func(args, cfg)
Feb 11 14:17:24 watatic insteon-mqtt[29348]:   File "/opt/insteon-mqtt/lib/python3.5/site-packages/insteon_mqtt/cmd_line/start.py", line 46, in start
Feb 11 14:17:24 watatic insteon-mqtt[29348]:     loop.select()
Feb 11 14:17:24 watatic insteon-mqtt[29348]:   File "/opt/insteon-mqtt/lib/python3.5/site-packages/insteon_mqtt/network/poll.py", line 208, in select
Feb 11 14:17:24 watatic insteon-mqtt[29348]:     if link.read_from_link() == -1:
Feb 11 14:17:24 watatic insteon-mqtt[29348]:   File "/opt/insteon-mqtt/lib/python3.5/site-packages/insteon_mqtt/network/Mqtt.py", line 221, in read_from_link
Feb 11 14:17:24 watatic insteon-mqtt[29348]:     status = self.client.loop_read()
Feb 11 14:17:24 watatic insteon-mqtt[29348]:   File "/opt/insteon-mqtt/lib/python3.5/site-packages/paho/mqtt/client.py", line 1284, in loop_read
Feb 11 14:17:24 watatic insteon-mqtt[29348]:     rc = self._packet_read()
Feb 11 14:17:24 watatic insteon-mqtt[29348]:   File "/opt/insteon-mqtt/lib/python3.5/site-packages/paho/mqtt/client.py", line 1849, in _packet_read
Feb 11 14:17:24 watatic insteon-mqtt[29348]:     rc = self._packet_handle()
Feb 11 14:17:24 watatic insteon-mqtt[29348]:   File "/opt/insteon-mqtt/lib/python3.5/site-packages/paho/mqtt/client.py", line 2305, in _packet_handle
Feb 11 14:17:24 watatic insteon-mqtt[29348]:     return self._handle_publish()
Feb 11 14:17:24 watatic insteon-mqtt[29348]:   File "/opt/insteon-mqtt/lib/python3.5/site-packages/paho/mqtt/client.py", line 2500, in _handle_publish
Feb 11 14:17:24 watatic insteon-mqtt[29348]:     self._handle_on_message(message)
Feb 11 14:17:24 watatic insteon-mqtt[29348]:   File "/opt/insteon-mqtt/lib/python3.5/site-packages/paho/mqtt/client.py", line 2642, in _handle_on_message
Feb 11 14:17:24 watatic insteon-mqtt[29348]:     callback(self, self._userdata, message)
Feb 11 14:17:24 watatic insteon-mqtt[29348]: TypeError: handle_set() missing 1 required positional argument: 'group'
Feb 11 14:17:24 watatic systemd[1]: insteon-mqtt.service: Main process exited, code=exited, status=1/FAILURE
Feb 11 14:17:24 watatic systemd[1]: insteon-mqtt.service: Unit entered failed state.
Feb 11 14:17:24 watatic systemd[1]: insteon-mqtt.service: Failed with result 'exit-code'.
```

**Comment by j3kestrel** [comment]
Required Hass configuration for a KeypadLinc switch:
```
switch:
  - platform: mqtt
    name          : 'gr_south_valance'
    command_topic : 'insteon/15.63.c5/set/1'
    state_topic   : 'insteon/15.63.c5/state'
    value_template: '{{value_json.state}}'
    retain        : false
```

**Comment by j3kestrel** [comment]
It seems we need to at least get the topic names correct and consistent.  It seems that if the KeypadLinc class could override the state topic, that would solve this problem.  I haven't had time to look carefully to see if there is a nice way to do this.

I think that I would prefer that a switch report data as a switch and a dimmer report data as a dimmer.

FWIW, I previously also had a KeypadLinc Dimmer, but it died and has been replaced with Hue and Zwave equipment.

**Comment by TD22057** [comment]
OK - I think this is fixed now.  I ended up making KeypadLinc a standalone input with it's own definitions.  Config file now has "keypad_linc_sw" for devices that are switches (existing "keypad_linc" for dimmers).  That flag controls what happens for button 1 outputs.  It will either use the btn_ or dimmer_ config inputs depending on the device type.  

This is a breaking change - existing config files won't read the dimmer config for inputs so config files will have to be updated.

KeypadLinc MQTT config inputs:

    # on/off switch (btn 1-8 or 2-8) output
    btn_state_topic: 'insteon/{{address}}/state/{{button}}'
    btn_state_payload: '{{on_str.upper()}}'
 
    # button load (btn 1) or LED (btn 2-8) input
    btn_on_off_topic: 'insteon/{{address}}/set/{{button}}'
    btn_on_off_payload: '{ "cmd" : "{{value.lower()}}" }'

    # dimmer (btn 1) output
    dimmer_state_topic: 'insteon/{{address}}/state/1'
    dimmer_state_payload: >
       { "state" : "{{on_str.upper()}}", "brightness" : {{level_255}} }

    # dimmer (btn 1) input
    dimmer_level_topic: 'insteon/{{address}}/level/1'
    dimmer_level_payload: ...

    # scene input
    btn_scene_topic: 'insteon/{{address}}/scene/{{button}}'
    btn_scene_payload: '{ "cmd" : "{{value.lower()}}" }'

**Comment by j3kestrel** [comment]
Thank you!  I've been seeing a lot of activity on this project, but I have been too busy to be helpful.  I will try to test this evening.
