### ISSUE TITLE
keypad not joining 

### ISSUE THREAD

**Issue by pmgendron** [TD22057/insteon-mqtt#345]
hi, 

I'm trying to add some keypads and I'm having an issue. Somehow, only the main load button is acknowledged and broadcasted to the MQTT server. Nothing shows up in the logs or in MQTT when I press the other buttons. 

I factory-reseted the modem and the keypad and tried join / pair again. here's the output of those commands:

**join**

`(insteon-mqtt) pm@insteon-mqtt:/opt/insteon-mqtt$ insteon-mqtt config.yaml join 2a.14.a3`
`Commanding keypad_linc device 2a.14.a3 (keypad salon) cmd=join`
`Device 2a.14.a3 engine version: i2c`
`Device joined.`

**pair**

`(insteon-mqtt) pm@insteon-mqtt:/opt/insteon-mqtt$ insteon-mqtt config.yaml pair 2a.14.a3`
`Commanding keypad_linc device 2a.14.a3 (keypad salon) cmd=pair`
`KeypadLinc 2a.14.a3 setting LED bits 11000000`
`KeypadLinc 2a.14.a3 refresh at level 0`
`Device 2a.14.a3 db out of date (got 22 vs 21), refreshing`
`Commanding Modem device 4c.18.06 (modem) cmd=scene`
`Entry: 0fff: 4c.18.06 (modem)          grp:   1 type: RESP data: 0x00 0x1c 0x01`
`Entry: 0ff7: 4c.18.06 (modem)          grp:   1 type: CTRL data: 0x03 0x00 0x01`
`Entry: 0fef: 4c.18.06 (modem)          grp:   2 type: CTRL data: 0x03 0x00 0x02`
`Entry: 0fe7: 4c.18.06 (modem)          grp:   3 type: CTRL data: 0x03 0x00 0x03`
`Entry: 0fdf: 4c.18.06 (modem)          grp:   4 type: CTRL data: 0x03 0x00 0x04`
`Entry: 0fd7: 4c.18.06 (modem)          grp:   5 type: CTRL data: 0x03 0x00 0x05`
`Entry: 0fcf: 4c.18.06 (modem)          grp:   6 type: CTRL data: 0x03 0x00 0x06`
`Entry: 0fc7: 4c.18.06 (modem)          grp:   7 type: CTRL data: 0x03 0x00 0x07`
`Entry: 0fbf: 4c.18.06 (modem)          grp:   8 type: CTRL data: 0x03 0x00 0x08`
`Entry: 0fb7: 00.00.00                  grp:   0 type: RESP data: 0x00 0x00 0x00 (UNUSED) (LAST)`
`2a.14.a3 database download complete`
`DeviceDb: (delta 22)`
`  0fbf: 4c.18.06 (modem)          grp:   8 type: CTRL data: 0x03 0x00 0x08`
`  0fc7: 4c.18.06 (modem)          grp:   7 type: CTRL data: 0x03 0x00 0x07`
`  0fcf: 4c.18.06 (modem)          grp:   6 type: CTRL data: 0x03 0x00 0x06`
`  0fd7: 4c.18.06 (modem)          grp:   5 type: CTRL data: 0x03 0x00 0x05`
`  0fdf: 4c.18.06 (modem)          grp:   4 type: CTRL data: 0x03 0x00 0x04`
`  0fe7: 4c.18.06 (modem)          grp:   3 type: CTRL data: 0x03 0x00 0x03`
`  0fef: 4c.18.06 (modem)          grp:   2 type: CTRL data: 0x03 0x00 0x02`
`  0ff7: 4c.18.06 (modem)          grp:   1 type: CTRL data: 0x03 0x00 0x01`
`  0fff: 4c.18.06 (modem)          grp:   1 type: RESP data: 0x00 0x1c 0x01`
`Unused:`
`  0fb7: 00.00.00                  grp:   0 type: RESP data: 0x00 0x00 0x00 (UNUSED) (LAST)`
`Last:`
`  0fb7: 00.00.00                  grp:   0 type: RESP data: 0x00 0x00 0x00 (UNUSED) (LAST)`
`GroupMap`
`  1 -> ['4c.18.06 (modem)']`
`  2 -> ['4c.18.06 (modem)']`
`  3 -> ['4c.18.06 (modem)']`
`  4 -> ['4c.18.06 (modem)']`
`  5 -> ['4c.18.06 (modem)']`
`  6 -> ['4c.18.06 (modem)']`
`  7 -> ['4c.18.06 (modem)']`
`  8 -> ['4c.18.06 (modem)']`
`ERROR: Scene command failed`
`Device paired`

I don't know how to solve this issue. 

thanks in advance for your time and assistance!

**Comment by krkeegan** [comment]
The pair command seems to be working just fine.  It looks like you maybe have some automation that is trying to trigger a modem scene `Commanding Modem device 4c.18.06 (modem) cmd=scene` that is triggered by a change on the keypadlinc maybe, it looks like it was triggered by a level of off on the keypadlinc here.

I think your error is in how you are sending that scene command.  What does that command look like?

**Comment by krkeegan** [comment]
If the only issue is failing to see the commands from the other buttons, they are all linked fine.  I suspect you watching the wrong mqtt topic.  One trick is to watch all the topics at once, so subscribe to topic `insteon/#` and you will see your command.

Otherwise change your logging level in your config file to `10` and paste the log output that results when you press a button.

**Comment by pmgendron** [comment]
Thank you for the reply! I managed to get the join / pair commands to work. 

When I press any button on any keypad (other than the load button) nothing is logged in Insteon-mqtt. I know the buttons / keypads work as I can manually program them as a scene controller.

**Comment by krkeegan** [comment]
Ok what are the results of this?

> Otherwise change your logging level in your config file to `10` and paste the log output that results when you press a button.

**Comment by krkeegan** [comment]
Closing this as stale.  If you still need help, please send the results of the log after altering the logging level as mentioned above.
