### ISSUE TITLE
MQTT topic subscriptions are not established

### ISSUE THREAD

**Issue by kpfleming** [TD22057/insteon-mqtt#350]
https://github.com/TD22057/insteon-mqtt/blob/0771befc54ba67423fca3bd6050cbfd88f3d5478/insteon_mqtt/network/Mqtt.py#L293

I noticed that my system had stopped working properly a few weeks ago, but didn't get a chance to track down the cause until today. The line referenced above was part of a commit to change the subscription behavior to only happen after `_on_connect` is called in the MQTT network link... however, on my system that function is not being invoked by the paho-mqtt client.

I've got:

paho-mqtt==1.5.1
insteon-mqtt @ git+https://github.com/td22057/insteon-mqtt@4203ec2a6c926df7d1b07d0684b07aea289e8a52 (latest 'dev' branch as of today)

I've added a `breakpoint()` as the first code line in `_on_connect`, and it's not being invoked. However, the MQTT connection *is* established, and insteon-mqtt properly publishes the states of the Insteon devices (and their state changes from local control events). It just never subscribes to the topics for the devices, so any commands I send via MQTT are ignored.

Can anyone suggest a possible reason why paho-mqtt is failing to invoke this callback?

**Comment by kpfleming** [comment]
Problem also exists with paho-mqtt 1.5.0, so it was not introduced in the recent 1.5.1 release.

**Comment by TD22057** [comment]
This could be because paho is now using the `_on_connect` method name internally.  I haven't had time to test that but swapping our client names to not match the base class variable names could fix this.

**Comment by kpfleming** [comment]
I changed all four `_on_<foo>` function names in network/Mqtt.py to start with `pm_on` instead, but there was no change in behavior.

I'll dive into the paho-mqtt code today to see if I can figure out what is going on.

**Comment by kpfleming** [comment]
Haven't found anything obvious yet, but just to be certain it wasn't a Python issue I installed Python 3.8.7 and tried with that. Same behavior, so I don't think this is related to Python 3.9.1 (which is what I have been using).

**Comment by kpfleming** [comment]
Found it! This only happens when the client ID has been explicitly set, because that calls `client.reinitialize()` on the MQTT client, which erases the previously-set callback functions. I'll send a PR to fix this.
