### ISSUE TITLE
How do i edit my home assistant config.yaml to add my devices as MQTT devices?

### ISSUE THREAD

**Issue by yonigold1** [TD22057/insteon-mqtt#357]
Hey im a bit of a newb when it comes to home assistant and I'm struggling to figure out how to complete the setup of this addon however I'm having difficulties understanding and completing step 12 of the [HA_Addon_Instructions.](https://github.com/TD22057/insteon-mqtt/blob/master/docs/HA_Addon_Instructions.md) if someone could help walk me through what to do for this step i would **greatly** appreciate it as I'm stumped. :/
My ultimate goal is to get these devices to show up in Apple Homekit once they show up in HA

**Comment by yonigold1** [comment]
if anyone could give me a hand when they can i would REALLY appreciate it 🙏

**Comment by yonigold1** [comment]
@krkeegan or @TD22057 are one of you able to help me? i've got the commands working ( pair 'light' or on 'light' ) what i can't seem to get to work is then getting the switches to work through home assistant itself (which i ultimately want to end up adding the switches and lights to homekit). I've read over all the instructions and i'm just really lost as my HA configuration.yaml is where i seem to get stumped. 
Please give me a hand.
Jailbreaker58

**Comment by krkeegan** [comment]
I am away from my computer doing housework today so I am only on my phone.  I will be back tomorrow.  In the meantime, you haven't provided much detail on what you have tried or what isn't working. Home assistant has lots of documentation about how to setup and test mqtt devices.  If this is a Home Assistant question there are usually hundreds or people on the Home Assistant discord or forum.

https://www.home-assistant.io/integrations/switch.mqtt/

https://www.home-assistant.io/docs/mqtt/testing/

**Comment by yonigold1** [comment]
So I figured it out but I have a quick question I have found that sometimes the status of the lights falls out of sync with the what the actual light status is. Is there a way to setup automatic polling?

**Comment by krkeegan** [comment]
If it is not remaining in sync, it means that the modem is not receiving some message from the devices.  Consider 1) placing the modem in a more central location to the devices, 2) using insteon range extenders, 3) installing more devices to increase the mesh size, 4) replacing the troublesome devices (sometimes as devices age, they respond less well).

As for automatic polling, no, there is no function for that.  You can setup some sort of automation in Home Assistant that periodically sends a refresh command to the relevant device.  topic `insteon/command/[device]` payload `{"cmd":"refresh"}`.

**Comment by yonigold1** [comment]
So i have a lot of Insteon devices around my house enough that the mesh shoult be enough however a few of them are somewhat old and some are really new I've noticed its really hit or miss with them it can be a new one that shows an incorrect status or an old one. 

As for the refresh command can you give me a bit more detail on how to do that? I'm a bit of a newbie and don't even know how to set up a refresh command.

Thanks for your help :)

**Comment by yonigold1** [comment]
So i figured out the refresh command 😅
my next question is how can i get home assistant to run the refresh all command ever 1 or ever 30 min?

**Comment by krkeegan** [comment]
So, be careful.  The more traffic you add to your insteon network, the more likely you are to have problems.  Refreshing all of your devices takes some amount of time.  If you activate a device during that time, the response may be delayed or lost.  I also have found, although cannot prove, that devices can get "overloaded" and start to act poorly when there is a lot of traffic. Generally I discourage this type of thing.  But I realize that for some devices it may be necessary.

Anyways, the guys at HomeAssistant can provide help with how to automate things.  I think you need to figure out how to created a timed automation that calls the mqtt service.

**Comment by TD22057** [comment]
IMO you should not need to do a refresh or schedule one.  The whole point of IM is that everything is kept in sync automatically.  If devices are getting out of sync, it's either because you're controlling them through some other system (like another hub maybe) or messages are being lost.  So in the first case, the answer is simple - only use one controller to manage insteon devices.  In the second case, you'll be a lot happier if you spend a little time figuring why they're out of sync and messages aren't arriving.  If you the network is flaky (messages not going through), you'll just have other problems down the road.  So I'd strongly suggest you spend a little time figuring out why a device is out of sync.  

Be sure you have debug level logging on and the moment a device is out of sync, look at the logs and search for that device's ID and look at the messages.  Identify how you  changed the state of the device in the first place and see if the model received that information (from a physical button click) or sent the command to change the state in the first place (from a virtual command).

**Comment by yonigold1** [comment]
Okay, thank you both very much for the advice I had a Hub V2 connected however I will now remove it and turn it off so it won't interfere. The times I found the devices were incorrect states was mostly with an older model switch and when I actually press the switch sometimes it wouldn't refresh. However, all the old switches I have seem to have some hiccups every now and then so I guess ill just have to look past it. I have about 20 Insteon switches installed (i have about 10 more to install) so I would say my Insteon network is pretty big. I guess the old ones just get crappier over time 🙄
