### ISSUE TITLE
Warnings from home assistant supervisor-2021.03.4

### ISSUE THREAD

**Issue by djfjeff** [TD22057/insteon-mqtt#362]
These warnings appear in the supervisor logs with the latest insteon-mqtt 0.8.0 addons :
~~~
21-03-10 11:22:02 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/git/83fc19e1/config.yaml: Invalid Add-on config!. Got ordereddict([('logging', ordereddict([('level', 10)])), ('insteon', ordereddict([('port', '/dev/insteon'), ('use_hub', False), ('hub_ip', '192.168.1.1'), ('hub_user', 'username'), ('hub_password', 'password'), ('storage', 'data'), ('startup_refresh', False), ('devices', ordereddict([('switch', [ordereddict([('3a.29.84', 'xmas tree')]), ordereddict([('26.48.ff', 'xmas stairs')]), ordereddict([('37.2d.20', 'deck')])]), ('dimmer', [ordereddict([('12.29.84', 'lamp2')]), '48.3d.46', ordereddict([(...
21-03-10 11:22:03 WARNING (MainThread) [supervisor.store.data] Can't read /data/addons/git/83fc19e1/config.yaml: Invalid Add-on config!. Got ordereddict([('logging', ordereddict([('level', 10)])), ('insteon', ordereddict([('port', '/dev/insteon'), ('use_hub', False), ('hub_ip', '192.168.1.1'), ('hub_user', 'username'), ('hub_password', 'password'), ('storage', 'data'), ('startup_refresh', False), ('devices', ordereddict([('switch', [ordereddict([('3a.29.84', 'xmas tree')]), ordereddict([('26.48.ff', 'xmas stairs')]), ordereddict([('37.2d.20', 'deck')])]), ('dimmer', [ordereddict([('12.29.84', 'lamp2')]), '48.3d.46', ordereddict([(...
~~~

The addons still works fine but I don't remember seeing those before.

**Comment by krkeegan** [comment]
Ahh.  It looks like HomeAssistant now allows the add-on config to be in yaml format.  So now our default config.yaml that is used for our application is being read by the supervisor.

It doesn't look like there is anyway to tell the supervisor to ignore this file.  It is read before the docker script is run, so we can't use the script to remove the file on installation.

I think this leaves us with three solutions:

1. Rename the file - we could call it config-default.yaml or something.  Users are not directly using this file anyways.
2. Move the file to a subdirectory - it could go in the docs folder, but it might be less noticed by users if we do this.
3. Do nothing - HA seems to handle things ok right now.  But it may not in the future, this is my least favorite option.

Let me know what everyone's preferred solution is.

**Comment by djfjeff** [comment]
I would personally go for the rename (option 1) but I think if you leave the .yaml extension, it might still get processed by HA. It could be renamed to something like config.yaml.example

**Comment by krkeegan** [comment]
The HA files used by the supervisor are:
```
addon_name/
  translations/
    en.(json/yaml/yml)
  apparmor.txt
  build.(json/yaml/yml)
  CHANGELOG.md
  config.(json/yaml/yml)
  DOCS.md
  Dockerfile
  icon.png
  logo.png
  README.md
  run.sh
```
https://developers.home-assistant.io/docs/add-ons/configuration

**Comment by djfjeff** [comment]
In this case, I would say that any name not in this list will be OK. In the end, it is just to remove the warning message from the logs as it does not cause issue anyway.
