### ISSUE TITLE
HA Add-on Armhf image for 0.8.2 is not available on Docker Hub

### ISSUE THREAD

**Issue by embak** [TD22057/insteon-mqtt#375]
**Describe the bug**
Insteon-MQTT HA add-on update to 0.8.2 from the add-on info page failed.

Armhf 0.8.2 docker image is not present on Docker Hub:
https://hub.docker.com/r/td22057/armhf-insteon-mqtt
same for aarch64:
https://hub.docker.com/r/td22057/aarch64-insteon-mqtt

**To Reproduce**
1. Go to 'Insteon-MQTT Add-On Info'
2. Click on 'Update'
3. The update pop-up will appear
4. Confirm the update
5. The update popup will disappear quickly
6. See error in Supervisor logs

**Log Output**
```txt
21-04-02 12:41:21 INFO (SyncWorker_7) [supervisor.docker.interface] Updating image td22057/armhf-insteon-mqtt:0.8.1 to td22057/armhf-insteon-mqtt:0.8.2
21-04-02 12:41:21 INFO (SyncWorker_7) [supervisor.docker.interface] Downloading docker image td22057/armhf-insteon-mqtt with tag 0.8.2.
21-04-02 12:41:22 ERROR (SyncWorker_7) [supervisor.docker.interface] Can't install td22057/armhf-insteon-mqtt:0.8.2 -> 404 Client Error for http+docker://localhost/v1.40/images/create?tag=0.8.2&fromImage=td22057%2Farmhf-insteon-mqtt: Not Found ("manifest for td22057/armhf-insteon-mqtt:0.8.2 not found: manifest unknown: manifest unknown").
```

**Hardware Details**
- What OS is Insteon-MQTT runnning on?  HASSIO
- Running Insteon-MQTT 0.8.1 on RPI 3B as an HA add-on.

**Comment by krkeegan** [comment]
Yup for `armhf` and `aarch64` I am getting the following from the build script

```
standard_init_linux.go:211: exec user process caused "no such file or directory"
The command '/bin/ash -o pipefail -c apk --no-cache add python3-dev' returned a non-zero code: 1
```

Both `i386` and `amd64` continue to work just fine.  Not sure what the issue is yet.

**Comment by krkeegan** [comment]
It seems to fail on any call to `apk add` it doesn't matter what the package is.

**Comment by krkeegan** [comment]
I am also now noticing this in the log `WARNING: Can't enable crosscompiling feature`.

Poking around the builder repo I don't see any issues that match our problems.  I see some commits relating to cross-compiling and I wonder if that is affecting us.

I am not a docker expert, so this may take quite some time to resolve.

**Comment by krkeegan** [comment]
OK, I am still not sure what is going on, but I was able to force some things to work by rolling back the builder and base images a few versions.  You should be able to download the images from docker now.

In short I had to do this:
1. Change the builder image from `latest` to `2021.02.0` in the build-docker.sh script
2. I then manually changed the base images from `latest` to `3.9` in the Dockerfile.  If we wanted to script this I think we could create a `build.json` file the the images that work.

> Fixing only one of these two did not work, I had to do both steps.

But I think the larger issue is to figure out why this is happening, if this is just my machine that is having build issues.  I don't see any other issues or comments on the builder repo or the docker-base repo.  I will keep poking at it and if I can get anything more concrete I will post an image to the relevant repo.

**Comment by embak** [comment]
I did update successfully my insteon-mqtt HA add-on to 0.8.2 on my RPi 3B.
Sorry, but I am not familiar enough with the docker builder process and base images to be of any help.
Let me know of your progress.
Thanks.

**Comment by krkeegan** [comment]
Well now it just appears to work again without any changes.  I am assuming that something has changed on my machine to make this work again.  Who knows.

Aren't intermittent problems fun?

**Comment by krkeegan** [comment]
This is happening again.... 

I am poking at it again, hoping that it will just work again.  So far clearing the docker images and containers did not do it.

**Comment by krkeegan** [comment]
I get a slightly different error this time around:

```
standard_init_linux.go:219: exec user process caused: exec format error
The command '/bin/ash -o pipefail -c apk --no-cache add python3-dev' returned a non-zero code: 1
```

**Comment by krkeegan** [comment]
ok, this time I was able to solve it by running the builder on the host docker daemon rather than the docker-in-docker design they have setup.  The build script looks like this instead

```
docker run --rm --privileged \
  -v ~/.docker:/root/.docker \
  -v /var/run/docker.sock:/var/run/docker.sock:ro homeassistant/amd64-builder \
  --all -r https://github.com/TD22057/insteon-mqtt -b master
```

I am going to wait and see if this still works next time before updating the build script.  It seems to be something about my machine that won't let the `armhf` or `aarch64` images build in the docker-in-docker design.
