### ISSUE TITLE
Support for network PLM

### ISSUE THREAD

**Issue by djfjeff** [TD22057/insteon-mqtt#38]
Hi,

I wanted to know if you were planing to add support for network PLM (basically the old hub that expose the PLM on port 9761 on the network).

The PLM binding in OpenHab support it (and insteon-terminal too) so I was wondering if it could be something you could add.

Thanks!

**Comment by djfjeff** [comment]
My bad, I just got through all the documentation and just saw that it is supported!!! Thank you!

Maybe one small question, is it safe for me to run this with my database already in my hub or do I need to start fresh? Will I be able to continue to use the Insteon Hub app on my phone after it?

Thanks a lot for your development.

**Comment by TD22057** [comment]
It should work (but I don't own one).  And yes, it works fine with the hub.
