### ISSUE TITLE
Backup/Restore PLM

### ISSUE THREAD

**Issue by pashdown** [TD22057/insteon-mqtt#380]
**Is your feature request related to a problem? Please describe.**
Had a PLM die and now I'm painfully joining/pairing my entire network again.  Is there a quicker way?

**Describe the solution you'd like**
A command that would join/pair everything in my database to a new PLM.

**Describe alternatives you've considered**
Tried to paste to the Home Assistant addon, but it all went on one line.  I suppose I could login to the docker possibly and script this?

**Comment by krkeegan** [comment]
No sorry there is no `join-all` or `pair-all` command.  It is possible though, so I will add this as a feature request.
