### ISSUE TITLE
Cyclic Import Error Related to Version

### ISSUE THREAD

**Issue by krkeegan** [TD22057/insteon-mqtt#386]
**Describe the bug**
When I introduced the version feature, I caused a pylint bug that I only just noticed:
```
insteon_mqtt/handler/DeviceDbModify.py:1:0: R0401: Cyclic import (insteon_mqtt -> insteon_mqtt.cmd_line -> insteon_mqtt.cmd_line.main -> insteon_mqtt.cmd_line.start -> insteon_mqtt.Modem) (cyclic-import)
```

It is caused by `import insteon_mqtt` in the `cmd_line.main` and `Modem`.  Those imports are needed to get the `__version__` from the base module.  But this causes a cyclic import.

This is outside my expertise.  But I came up with two solutions.

1. Use `__main__` while elegant, doesn't seem very ideal or smart.  See the [Cyclic_Opt1 Branch](https://github.com/TD22057/insteon-mqtt/compare/dev...krkeegan:Cyclic_Opt1) for the changes.
2. Move `__version__` out of the base module into its own module `version.py`.  See the [Cyclic_Opt2 Branch](https://github.com/TD22057/insteon-mqtt/compare/dev...krkeegan:Cyclic_Opt2) for the changes.

Option 2 is my preferred solution.  But I don't know if there are issues with moving the `__version__` variable outside of the base module.

If there are other solutions I am happy to consider them too.

This was caused by commit 9e9f7061c47b2174bcd0e9e8cbee21aa49d47eaa

**To Reproduce**
Run `pylint insteon_mqtt`

**Expected behavior**
Not to get an error

**Additional context**
While the error doesn't seem to cause adverse issues at the moment, it certainly could.

**Comment by TD22057** [comment]
The short answer we (i.e. in my job) always follow is this: never use absolute imports in a package.  So option 2 is a much better option.  Another approach which we use a lot is to have a `const.py` file or something like that that has enums and other constants (things w/ no code or dependencies) and put the version there so it can be imported from a command line file.  Either that or a separate version file is the best way to go

**Comment by krkeegan** [comment]
Perfect, I like that solution.  I renamed the file, it is quite sparse, but at least it could serve some other purpose in the future.
