### ISSUE TITLE
New validation fail on DNS in MQTT broker

### ISSUE THREAD

**Issue by djfjeff** [TD22057/insteon-mqtt#403]
With the latest 0.9.1 version, the validation fail if I put a DNS in the MQTT broker field. For example, with either `core-mosquitto` or `core-mosquitto.local.hass.io`, the following error show up in the logs :

```
An error occured while trying to validate your configuration file.  Please
review the errors below and fix the error.  InsteonMQTT cannot run until this
error is fixed.
mqtt: 
  broker: 
  - unknown field
[cmd] /opt/insteon-mqtt/hassio/entrypoint.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

If I put the IP address, InsteonMQTT start up fine.

**Comment by krkeegan** [comment]
Yup, I definitely did that.  That was a complete lack of imagination on my part.  I will push a fix shortly.

**Comment by krkeegan** [comment]
Alright 0.9.2 has been pushed.  It solves this issue.  Sorry about that.

**Comment by djfjeff** [comment]
No problem, 0.9.2 solved the issue on my side, thanks!
