### ISSUE TITLE
Add Message De-Duplication

### ISSUE THREAD

**Issue by krkeegan** [TD22057/insteon-mqtt#42]
I see that this is mentioned as a future enhancement in the docs already.  This is a bit more of an issue for i1 devices, particularly with database management.  This is because i1 devices send numerous standard length messages to get a complete link record.  To compound the problem, the messages sent from the device all look identical with the exception of the single data byte requested.  There is no state information.

I have previously written de-duplication processes that work decently well.  They look at the following factors:
- Cache recently received messages 
  - Messages are saved in the cache until the amount of time for any remaining hops_left has passed.  (87 milliseconds for standard length message hops and 187 milliseconds for extended length message hops seems to empirically be right, even though it doesn't match the insteon spec)
- Compare all incoming messages and ignore with warning duplicate messages
  - Messages are declared to be duplicates if everything about the message is the same with the exception of the max_hops and hops_left flags

**Comment by TD22057** [comment]
Fixed in PR #44.
