### ISSUE TITLE
auto_uart is depreciated

### ISSUE THREAD

**Issue by pashdown** [TD22057/insteon-mqtt#429]
**Describe the bug**
21-06-02 23:07:53 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of Insteon MQTT

**To Reproduce**
Version 1.0
Home Assistant supervisor logs

**Expected behavior**
No error.

**Log Output**

```txt
21-06-02 23:07:53 WARNING (MainThread) [supervisor.addons.validate] Add-on config 'auto_uart' is deprecated, use 'uart'. Please report this to the maintainer of Insteon MQTT

```

**Comment by krkeegan** [comment]
This was fixed back in 0.7.6.  https://github.com/TD22057/insteon-mqtt/commit/a853b187b2b85bd3bd401913ad0648aa6bc4c1bf

Have you installed InsteonMQTT by pointing the supervisor at the repository?

**Comment by pashdown** [comment]
Looks like I have a 0.7.2 that is haunting my install.  I am pointing to the repository, and 1.0.0 is installed, but 0.7.2 also remains.  Any idea how to purge it safely?

**Comment by pashdown** [comment]
I removed addons/insteon-mqtt and the error has gone away.  This however, remains.

![image](https://user-images.githubusercontent.com/175150/120908264-8f961780-c625-11eb-9d63-4f00309ec276.png)

**Comment by krkeegan** [comment]
Maybe try a reload?  I dunno, check the Home Assistant forums, I am sure they have the answer.
