### ISSUE TITLE
Supervisor still only shows 0.7.4

### ISSUE THREAD

**Issue by jkmaxwell** [TD22057/insteon-mqtt#436]
re: https://github.com/TD22057/insteon-mqtt/blob/master/docs/HA_Addon_Instructions.md

Supervisor is not showing an update available. I see that 1.0.0 is the current version. I have no issues with any other add-ons. Please let me know how I can help debug.

**Comment by krkeegan** [comment]
I suspect you did not install InsteonMQTT following the instructions on the page you cited.

Navigate in HomeAssistant to `Supervisor -> Addon Store`

Where does InsteonMQTT appear on that page?  It should appear under a section called **Insteon MQTT Repository**:

![image](https://user-images.githubusercontent.com/3046315/124655157-559e7800-de54-11eb-8113-85dff3ac7507.png)

If it appears under **Local Addons** you need to uninstall that addon and install it following the instructions on:

https://github.com/TD22057/insteon-mqtt/blob/master/docs/HA_Addon_Instructions.md

The correct version will then show up in the Add On:

![image](https://user-images.githubusercontent.com/3046315/124655443-b2019780-de54-11eb-9bab-bacf4ed859dc.png)

**Comment by jkmaxwell** [comment]
@krkeegan yes, i did install through the add-on store. sorry -- i know you must deal with all sorts of problems between chair and keyboard, and this sounded like that pattern. it wasn't.

i'll reinstall anyway. if you are curious to debug please let me know.
