### ISSUE TITLE
Add Availability Topic

### ISSUE THREAD

**Issue by krkeegan** [TD22057/insteon-mqtt#446]
**Describe the solution you'd like**
HomeAssistant MQTT entities have an option to specify an `availability_topic` which by default expects the payload `online` or `offline`.  In essence, when this payload is `offline` the entity will be listed as 'unavailable' in its state and will be greyed out in the front end.

I believe that most integrations use code to:
1. publish `online` on connection to the mqtt broker,
2. publish `offline` on a clean disconnect from the mqtt broker,
3. and use a last_will to cause `offline` to be published if the connection fails.

This seems like a mildly useful feature.  InsteonMQTT doesn't crash at this point (at least for me).  But if a user has InsteonMQTT running on a seperate machine from the broker, then it is possible that network errors could cause issues.  Or power issues could happen as well.

The nice thing is that this would give an indication in the front end of an issue and would accurately reflect that any changes would not be acted on.

You could also create a simple `binary_sensor` that tracked or had some automation triggered by the availability of InsteonMQTT.

The coding seems simple enough, I don't see a reason not to do this.

**Comment by tstabrawa** [comment]
For people using hubs, this could possibly be further enhanced to update the availability based on connectivity to the hub -- or generalized to change availability whenever there are connectivity problems detected with the modem (e.g. someone unplugs a USB PLM and the serial device disappears).
