### ISSUE TITLE
Support Insteon Bulbs

### ISSUE THREAD

**Issue by peasem** [TD22057/insteon-mqtt#452]
I have a couple of Insteon Bulbs (2672's) that I would like to control with Insteon-mqtt. Please consider supporting them.

**Comment by krkeegan** [comment]
Have you tried setting them up as dimmers?  I suspect they will just work.

If not, it may be a good chance for you to learn some python.

**Comment by peasem** [comment]
Yes, that works. I should have tried that, but did not see Bulbs in the list of supported devices and moved on to other things. Thanks for the support.
