### ISSUE TITLE
insteon-mqtt command missing?

### ISSUE THREAD

**Issue by kskenyon** [TD22057/insteon-mqtt#466]
I get a "not found" error when I enter insteon-mqtt command.  Running in Docker on arm64.

**Comment by larizzo** [comment]
You should include the command you are running, it could help troubleshoot. It sounds like the system might not be able to find your executable, you could try running `which insteon-mqtt` to see if the command is in your path. If you are running a container are you inside the container?

**Comment by kskenyon** [comment]
Duh, I wasn’t inside the container.

Sorry for the bother. 

Kevin
