### ISSUE TITLE
Integration broken after Home Assistant Core upgrade

### ISSUE THREAD

**Issue by UniKyrn** [TD22057/insteon-mqtt#476]
I'd been using the integration for about two weeks, slowly adding devices.  When the notification that Core 2022.2.4 was available, I upgraded.  Nothing has worked since and restoring from back did work either.

First issue, it forgot the address of the PLM, I had to manually configure it for the first time.

Second issue, it won't talk to the PLM still.

I run insteon-mqtt tool and get the following error(s).

>>>insteon-mqtt config.yaml get-devices
Commanding Modem device 07.8b.35 (modem) cmd=get_devices
{"07.8b.35": {"type": "modem", "label": "modem"}}
Complete

>>>insteon-mqtt config.yaml join 52.a7.61
Commanding dimmer device 52.a7.61 (dining room ceiling light) cmd=join
Handler timed out 1 of 3 sent: Std: 52.a7.61, Type.DIRECT mh:3 hl:3, 0d 00 
Handler timed out 2 of 3 sent: Std: 52.a7.61, Type.DIRECT mh:3 hl:3, 0d 00 
Handler timed out 3 of 3 sent: Std: 52.a7.61, Type.DIRECT mh:3 hl:3, 0d 00 
ERROR: Handler timed out - no more retries (3 sent)
ERROR: Command timed out

The devices I have configured all exist in MQTT, I just can't control them via the PLM any more.

Any recommendations on where to look next?

devices.yaml

    # Dimming devices (outlets, wall switches, lamp modules, etc).
    dimmer:
      - 03.d0.7a: 'Office Ceiling Light'
      - 3e.96.df: 'Office Art Light'
      - 03.78.2f: 'Upstairs Hallway Ceiling Light'
      - 52.d3.89: 'Main Bathroom Light'
      - 51.38.db: 'Master Bathroom Light'
      - 52.a7.61: 'Dining Room Ceiling Light'
      - 0a.fa.64: 'Kitchen Sink Light'
      
    switch:
      - 05.55.bf: 'Main Bathroom Fan'
      - 04.48.ff: 'Master Bathroom Fan'
      - 46.d9.e3: 'Kitchen Ceiling Light'

    motion:
      - 54.59.f7: 'Main Bathroom Motion Sensor'
      - 55.86.88: 'Master Bathroom Motion Sensor'

config.yaml

insteon:
  ###### Modem
  # You can use either a PLM Modem or an Insteon Hub, but not both.

  # PLM Modem option (Serial or USB)
  port: '/dev/ttyUSB1'
  #address: 07.8b.35    # USB PLM
  address: 52.19.b8     # USB Stick

...

mqtt:
  broker: 199.249.225.20
  #broker: 127.0.0.1
  port: 1883
  # Optional broker login data.
  username: mqtt-user
  password: mqtt-pass

Currently running on Core 2022.2.5 since the restore to 2022.2.3 didn't help.

**Comment by krkeegan** [comment]
I don't think this is related to any updates.

This error:
```
Commanding dimmer device 52.a7.61 (dining room ceiling light) cmd=join
Handler timed out 1 of 3 sent: Std: 52.a7.61, Type.DIRECT mh:3 hl:3, 0d 00
Handler timed out 2 of 3 sent: Std: 52.a7.61, Type.DIRECT mh:3 hl:3, 0d 00
Handler timed out 3 of 3 sent: Std: 52.a7.61, Type.DIRECT mh:3 hl:3, 0d 00
ERROR: Handler timed out - no more retries (3 sent)
```

Indicates that the PLM cannot communicate with that device.  Possible reasons are:
- Not enough insteon devices in your network to relay the message
- RF interference near the PLM or the device
- The PLM broke

Possible solutions:
- Try restarting the machine.
- Move a device closer to the PLM to see if that helps, interference near device
- Move the PLM, see if nearby interference is the issue

> First issue, it forgot the address of the PLM, I had to manually configure it for the first time.

I would love to know what that error looked like.

It can't "forget" the address.  It requests the address of the PLM on startup.  If what you saw was that it was not able to get the address of the PLM on startup.  The the PLM being broken is a good candidate for the problem, or at minimum you have some sort of usb/serial communication issue going on.

**Comment by UniKyrn** [comment]
Spent the day digging into this again.  Maybe not directly, but the update was involved somehow.  The root problem was that the config-base.yaml got removed, which broke just about everything.  I restored it and everything came back to life.

No idea how that file went missing though ...
