### ISSUE TITLE
Cannot start server with empty scenes.yaml file

### ISSUE THREAD

**Issue by kpfleming** [TD22057/insteon-mqtt#482]
**Describe the bug**
Cannot start server with an empty scenes.yaml file.

**To Reproduce**
1. Add `scenes: !rel_path scenes.yaml` to `config.yaml`.
2. Run `touch scenes.yaml` to create the file.
3. Start insteon-mqtt.

**Expected behavior**
Server should start up and behave as if no scenes are defined (since none are).

**Log Output**
```txt
Feb 25 13:37:48 garage-ha22 insteon-mqtt[42740]:                  ------- Validation Error -------
Feb 25 13:37:48 garage-ha22 insteon-mqtt[42740]: An error occured while trying to validate your scenes file.  Please
Feb 25 13:37:48 garage-ha22 insteon-mqtt[42740]: review the errors below and fix the error.  InsteonMQTT cannot run until this
Feb 25 13:37:48 garage-ha22 insteon-mqtt[42740]: error is fixed.
Feb 25 13:37:48 garage-ha22 insteon-mqtt[42740]: scenes:
Feb 25 13:37:48 garage-ha22 insteon-mqtt[42740]: - null value not allowed
```

My intention was to import all (manually created) links between devices as a starting point, but it appears that I'll have to create a 'dummy' scene first.

A simple fix would probably be to trim all leading/trailing whitespace from the contents read from `scenes.yaml` and if the result is empty, skip the validation step.

**Comment by Juggler00** [comment]
I'm experiencing this issues on 1.1.1. Will the fix be pushed in the near future?

**Comment by krkeegan** [comment]
Yes I will be releasing 1.2.0 in the next month or so to address new changes in HA starting in 2023.8.0.
