### ISSUE TITLE
Support for In-LineLinc dimmer devices

### ISSUE THREAD

**Issue by johnsturgeon** [TD22057/insteon-mqtt#487]
**Is your feature request related to a problem? Please describe.**
I just installed the add on and I noticed that one of my switches was not configured properly.  I added it to the 'dimmer' section since it's a dimmer.

**Describe the solution you'd like**
Either handle an in-linelinc device as a straight up dimmer, or enable a new class of devices

https://www.insteon.com/dimmer-in-linelinc

**Comment by johnsturgeon** [comment]
For the record, it *does* seem to be handling the dimming correctly
<img width="401" alt="image" src="https://user-images.githubusercontent.com/9746310/156671280-0634a3cf-8e00-4173-b74d-2dee01605849.png">
so I actually don't think it's a show stopper, but it would be nice to have it recognized

**Comment by krkeegan** [comment]
If there are unique features that are present on an in-line dimmer that are not available on a dimmer, feel free sub-class dimmer and add those features and submit a pull request.  I don't have access to one.

**Comment by johnsturgeon** [comment]
There are no unique features from that of a dimmer, but it was not recognized on 'scan'
<img width="660" alt="image" src="https://user-images.githubusercontent.com/9746310/156675212-7820cc56-808e-4986-8b4a-e2d18c2e3a16.png">

**Comment by johnsturgeon** [comment]
Awesome, I'll take a look at the file and figure it out.  Thanks.
