### ISSUE TITLE
Support for battery reporting on Mini-Remote 4

### ISSUE THREAD

**Issue by djfjeff** [TD22057/insteon-mqtt#49]
It seems the Mini-Remote 4 does not send the battery heartbeat like other battery powered Insteon product. A workaround is to query the battery state when the remote is awake (after getting a button press for example).

I found this on the subject : https://krkeegan.com/insteon-remotelinc-2-lacks-the-heartbeat-feature/

**Comment by krkeegan** [comment]
Perl is an awful language, and the code in Misterhouse is a swamp.  But yes you are correct, D10 is indeed the battery level.
