### ISSUE TITLE
Incorrect indentation in sample discovery templates in docs/discovery.md

### ISSUE THREAD

**Issue by dssinger** [TD22057/insteon-mqtt#499]
The examples for "Six Button KeypadLinc" and "Setting Switches as Lights" are incorrectly indented - the `discovery_entities` line in each one (and everything under it) should be indented two spaces so that the examples can be copied verbatim into the configuration file

**Comment by krkeegan** [comment]
These example were replaced in 9a2979a by `discovery_overrides`.  Which is contained in [docs/discovery_customization_config.md](https://github.com/TD22057/insteon-mqtt/commit/9a2979a7aff213aa31a270f448cdf48c3e167541#diff-bea3a491e1026a985bff225192efbbd5fdbd25bc2764ab89492619130fc5d61e).  Which is included in the next release.
