### ISSUE TITLE
Miss group 4 for Leak Sensor

### ISSUE THREAD

**Issue by djfjeff** [TD22057/insteon-mqtt#50]
I successfully paired my Leak Sensor but it seems to miss the group 4 which is the heartbeat one :

Here is a portion of my modem data file (28.4c.xx is my leak sensor) :
    {
      "addr": "28.4c.xx",
      "group": 1,
      "is_controller": true,
      "data": [
        1,
        0,
        0
      ]
    },
    {
      "addr": "28.4c.xx",
      "group": 2,
      "is_controller": false,
      "data": [
        2,
        0,
        0
      ]
    },
    {
      "addr": "28.4c.xx",
      "group": 1,
      "is_controller": false,
      "data": [
        1,
        0,
        0
      ]
    },
    {
      "addr": "28.4c.xx",
      "group": 3,
      "is_controller": false,
      "data": [
        3,
        0,
        0
      ]
    }

Here is my leak sensor data file :

{
  "address": "28.4c.xx",
  "delta": 17,
  "used": [
    {
      "addr": "49.f7.xx",
      "group": 1,
      "mem_loc": 4095,
      "db_flags": {
        "in_use": true,
        "is_controller": false,
        "is_last_rec": false
      },
      "data": [
        255,
        0,
        1
      ]
    },
    {
      "addr": "49.f7.xx",
      "group": 255,
      "mem_loc": 4087,
      "db_flags": {
        "in_use": true,
        "is_controller": true,
        "is_last_rec": false
      },
      "data": [
        3,
        0,
        0
      ]
    },
    {
      "addr": "49.f7.xx",
      "group": 1,
      "mem_loc": 4079,
      "db_flags": {
        "in_use": true,
        "is_controller": true,
        "is_last_rec": false
      },
      "data": [
        3,
        0,
        1
      ]
    },
    {
      "addr": "49.f7.xx",
      "group": 2,
      "mem_loc": 4071,
      "db_flags": {
        "in_use": true,
        "is_controller": true,
        "is_last_rec": false
      },
      "data": [
        3,
        0,
        2
      ]
    },
    {
      "addr": "49.f7.xx",
      "group": 3,
      "mem_loc": 4063,
      "db_flags": {
        "in_use": true,
        "is_controller": true,
        "is_last_rec": false
      },
      "data": [
        3,
        0,
        3
      ]
    }
  ],
  "unused": [],
  "last": {
    "addr": "00.00.00",
    "group": 0,
    "mem_loc": 4055,
    "db_flags": {
      "in_use": false,
      "is_controller": false,
      "is_last_rec": true
    },
    "data": [
      0,
      0,
      0
    ]
  }
}

**Comment by djfjeff** [comment]
I must state that having group 4 (so the heartbeat) is really useful to make sure the device is still functional. I have Leak Sensor in place that are hard to reach so making sure they check-in everyday is important.

**Comment by krkeegan** [comment]
I have to look back at my prior notes. I know the leak sensor has a heartbeat, but it may not require pairing to group 4.  Insteon sadly doesn't follow its own standards as much as we would like.

**Comment by djfjeff** [comment]
When I was using OpenHab, if I recall correctly, the heartbeat was coming from group 4. In fact, I don't think the Leak Sensor support the low battery on group 3.

**Comment by krkeegan** [comment]
It looks like it is a broadcast message.  See page 11

https://cache.insteon.com/developer/2852-222dev-102013-en.pdf

**Comment by djfjeff** [comment]
Ok, we will see in 24 hours if I get the information from the heartbeat.

I thought that even with a broadcast, we still need to add modem and device entry for the group. At least, this is what was told in the documentation for OpenHab ( https://github.com/openhab/openhab1-addons/wiki/insteon-plm-binding#water-leak-sensors ).

Also, do you know why I get a controller on group 255 set on my leak sensor when pairing with insteon-mqtt (I did a factory reset before pairing)?

**Comment by djfjeff** [comment]
I can confirm that insteon-mqtt did not receive or process the heartbeat from the leak sensor.

After reading the doc, it seems :

- On the leak sensor, we should only need the CTRL/RESP pair for group 1 with the modem (basic linking) and that's all. It seems there is no need to define group 2, 3 and 4 on the leak sensor itself.

- On the modem, we should be CTRL/RESP on group 1 and RESP on group 2 and 4. No need for group 3 as it seems the Leak Sensor does not support the low battery option.

**Comment by djfjeff** [comment]
@krkeegan Can you confirm my last post about what I think we need for the Leak Sensor? I am still not confident I understand the Insteon protocol and documentation 100%.

If my previous statement is OK, I will try to submit a PR to make it work.

**Comment by krkeegan** [comment]
I think your description of the leak sensor accurately matches the docs.  I have a leak sensor, but haven't had a chance to check if it matches this (sometimes the insteon docs are wrong).

I agree the leak sensor only needs the link pair for group 1

I think the modem only needs group 1 as well.  The insteon spec doesn't really envision half-links in the way you describe, but what you describe wouldn't cause any issues.  I just don't think it is needed.  I am pretty sure the Modem will report the receipt of the broadcast message even without links for groups 2 and 3 defined.

**Comment by djfjeff** [comment]
@krkeegan Thanks for the feedback, I will try to start working on this. Testing if half-links are needed will be easy without any modification of the code. I will simply remove the group 2 link that we currently set and validate that we still receive wet event. If yes, it means the modem still report those to insteon-mqtt correctly and should do the same for group 4 heartbeat.

**Comment by djfjeff** [comment]
Working on this, almost finished (need to checkout for 24 hours to make sure we grab the heartbeat correctly).

However, I can already confirm that the modem need to be a RESP for group 2 and 4 to make this work. Without this, wet event were ignored (and I suppose heartbeat event would be too).

**Comment by krkeegan** [comment]
Hmm, interesting.  Maybe I still have my modem in promiscuous mode.

**Comment by djfjeff** [comment]
@krkeegan my code seems to be working fine. One last thing that I want to validate before committing. No matter how I try to link the Leak Sensor and the modem (with the Set button or with the linking command), the database for the Leak Sensor report group 255.

Are you aware of this? Is it something normal with the Leak Sensor? It is the first time that I encounter this.

**Comment by krkeegan** [comment]
Sorry can you explain more?

This is a controller link or a responded link?  Which device reports group 255?

**Comment by djfjeff** [comment]
If you take a look at my first post, the leak sensor database written by insteon-mqtt have a controller on group 255.

I really don't know how it get there. It is there even if I link the leak sensor and the modem with the Set button (and do a refresh to get the database).

The modem database has the correct group 1 entry.

**Comment by TD22057** [comment]
I saw some weird links from the smoke bridge as well (don't remember exactly what they were though).  My guess is that some of the older/less popular devices didn't get the best firmware updates over time and behave slightly differently.  Or it could be something else - from reading the ISY forums, it sounds like Insteon doesn't keep any of their docs up to date and only shares memos about behavior changes with paying dev customers.

With PR #60 merged, can we close this out?

**Comment by djfjeff** [comment]
Yes, I will go ahead and close it. Thanks!
