### ISSUE TITLE
New Home Assistant Warning

### ISSUE THREAD

**Issue by yonigold1** [TD22057/insteon-mqtt#506]
Hello I have been using this plugin for about over a year now and it has to be the best thing that's happened to my smart home. 

Everything was and is currently working however after updating to HomeAssistant 2022.9.0 there are 2 warnings for my mqtt insteon devices.
![image](https://user-images.githubusercontent.com/34217684/189463651-f7390d6a-f3ae-4f25-8897-3649f4ae83ee.png)
![image](https://user-images.githubusercontent.com/34217684/189463653-692eadff-1d34-4cc3-a298-97cdc427143f.png)

These are the two warnings.

Is there a fix that i can do to make these go away.

**Comment by balthisar** [comment]
There's a big link to Documentation on those warning panels that will tell you what to do.

Within ha, you'll migrate your devices to something like:

    mqtt:
        switch:

Instead of the current

    switch:
        - platform: mqtt
