### ISSUE TITLE
Documentation on how to remove device from the modem

### ISSUE THREAD

**Issue by djfjeff** [TD22057/insteon-mqtt#508]
I use insteon-mqtt for a long time and I have a lot of devices added and configured the way I want.

However, we did some major home work in the last few months and I now need to clean up my Insteon environment. In short, I have a few switch that were "lost" in the process and 2 of them don't work after reinstallation.

I was wondering what would be the best way to remove them from my insteon-mqtt environment? I want to make sure the modem db is up to date and not only remove them from the config file. I don't want to have lingering links in the modem db.

Thanks!

**Comment by djfjeff** [comment]
Any ideas? It seems everything I tried only remove the device in appearance, not in the modem DB directly.

**Comment by EnGamma** [comment]
Insteon-mqtt has a modem sync command that modifies device database, in
this case the modem, to match the insteon-mqtt device file settings.
Pretty sure this should work.

**Comment by djfjeff** [comment]
From the doc, it seems the sync command work from the scenes.yaml config file and not sync the whole DB. Is that what you meant?

**Comment by TD22057** [comment]
You didn't describe how you're using it (stand alone, HASS add on, etc) so it's hard to tell you exactly what to do.  If you can use the command line tool, you can run the factor reset command to clear something completely and start over.  Or you can use the db-delete command to remove single links from the modem database for old devices.  The command line tool just sends an MQTT command to the insteon-mqtt process so you can manually send those commands yourself as well.  See: https://github.com/TD22057/insteon-mqtt/blob/master/docs/mqtt.md#delete-the-device-as-a-controller-of-another-device for the mqtt command to delete a device.

**Comment by djfjeff** [comment]
I use it with HASS but I also interact with the CLI and MQTT when I need.

I don't want to start over completely as I have ~50 devices. Also, this is why I want to keep my modem DB clean and remove the lost devices to not accumulate junk over time.

If I understand correctly, for a light switch with address xx.yy.zz, I would use the following command to remove it from the modem :

~~~
insteon-mqtt config.yaml db-delete -o xx.yy.zz ctrl 1
insteon-mqtt config.yaml db-delete -o xx.yy.zz resp 1
~~~

I am not sure I understand what addr2 mean in the db-delete command :
~~~
positional arguments:
  addr1          Address of the device to delete.
  {ctrl,resp}    'ctrl' for addr1 as controller of addr2. 'resp' for addr1 as
                 responder to addr2.
  addr2          Address of the device to delete from the db.
  group          Group (button) number on the controller (i.e. the db group
                 number).
~~~

**Comment by TD22057** [comment]
addr1 is the device to modify, addr2 is the device to remove from addr1's
link db.  So addr1 is the modem, addr2 is the device to remove from the
modem's db.

**Comment by djfjeff** [comment]
Thank you, that did the tricks!
