### ISSUE TITLE
Assertion in ResponderBase.py rejects mqtt JSON string value for mode (normal,fast,instant)

### ISSUE THREAD

**Issue by EnGamma** [TD22057/insteon-mqtt#512]
**Describe the bug**
Assertion in ResponderBase.py rejects mqtt JSON string value for mode (normal,fast,instant)

**To Reproduce**
1. send MQTT message insteon/command/dimmer_1 b'{"cmd": "on","mode":"instant"}'
2. "instant" is not accepted by assertion statement in ResponderBase.py
3. The MQTT topic you posted to 'insteon/command/dimmer_1'
4. The MQTT payload you posted to the topic: '{"cmd": "on","mode":"instant"}'
5. See error output below

**Expected behavior**
string values to be accepted, converted if necessary to on_off.MODE types to pass assertion check

**Log Output**
Please change your logging level to 10 by editing Logging.level in your config.yaml file.

```txt
# Put your relevant logging output below this line
2023-05-04 16:04:18.955 INFO Mqtt: MQTT message insteon/command/dimmer_1 b'{"cmd": "on","mode":"instant"}'
2023-05-04 16:04:18.956 UI Mqtt: Commanding dimmer device 3a.83.7e (dimmer_1) cmd=on
2023-05-04 16:04:18.956 INFO ResponderBase: Device 3a.83.7e grp: 1 cmd: on instant
2023-05-04 16:04:18.957 ERROR Mqtt: Error running command on on device 3a.83.7e (dimmer_1)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/insteon_mqtt/mqtt/Mqtt.py", line 332, in handle_cmd
    cmd_func(on_done=on_done, **data)
  File "/usr/local/lib/python3.9/site-packages/insteon_mqtt/device/base/ResponderBase.py", line 116, in on
    assert isinstance(mode, on_off.Mode)
AssertionError


```

**Your Configuration**
What are the relevant entries in your config.yaml?  Please include the device definition of the device affected.
```yaml
# Put your relevant config.yaml text below this line
# not applicable
```

**Hardware Details**
- What OS is Insteon-MQTT runnning on?
Running in insteon-mqtt docker container on a Raspberry Pi 4

- The model of your Modem, see https://github.com/TD22057/insteon-mqtt/blob/master/docs/mqtt.md#get-device-model-information
```txt
# Please paste the output of get-model for the modem below this line
Modem 3d.9a.1c model information: NETWORK_BRIDGES (0x03): '2413U' (0x15) 'PowerLinc USB Modem (Dual Band)'
```

- The model of the affected Device, see https://github.com/TD22057/insteon-mqtt/blob/master/docs/mqtt.md#get-device-model-information
```txt
# Please paste the output of get-model for the affected device below this line
Device 3a.83.7e received model information: DIMMABLE_LIGHTING (0x01): '2457D2' (0x0e) 'LampLinc (Dual-Band)' firmware: 0x43
```

**Additional context**

**Comment by EnGamma** [comment]
I've since discovered that this assertion failure also occurs when instant and fast on modes are triggered from command line with the -i and -f switches.  (Not surprising since command line generates the same JSON mqtt message that I reported previously, but I thought perhaps the command line mode would bypass this problem, but it doesn't.)  Again, this problem occurs because the assertion allows only named constant objects, not strings, and there is no conversion of the JSON string to the required object.

`insteon-mqtt config/config.yaml on -i <dev_addr>`

**Comment by krkeegan** [comment]
Yeah that is a bug, I will fix that.

If you can, using the `/set` or `/level` topics would be better for this as they contain more logic and controls.  The intent of the command topic was to provide raw access to configuration functions and to provide an interface for the command line it doesn't have as many guardrails.
