### ISSUE TITLE
Pairing the keypadlinc using insteon-mqtt change the flags

### ISSUE THREAD

**Issue by djfjeff** [TD22057/insteon-mqtt#54]
I saw that when I pair my Keypad 8 buttons with insteon-mqtt (so link both side and pair), the background LED on the keypad shutdown. Wondering why it happen, I checked the flags in insteon-terminal. After pairing the keypad, here are the flags :

>>> hallway_keypad.readFlags1()
sent msg: OUT:Cmd:0x62|toAddress:42.17.xx|messageFlags:0x0F=DIRECT:3:3|command1:0x1F|command2:0x01|
>>> read flags1 got flags1: Plock ON|LED on TX ON|Resume Dim bit ON|LED OFF|KeyBeep OFF|RF Disable OFF|Powerline Disable OFF

After a factory reset, here are the default flags :

>>> hallway_keypad.readFlags1()
sent msg: OUT:Cmd:0x62|toAddress:42.17.xx|messageFlags:0x0F=DIRECT:3:3|command1:0x1F|command2:0x01|
>>> read flags1 got flags1: Plock OFF|LED on TX ON|Resum Dim bit OFF|LED ON|KeyBeep OFF|RF Disable OFF|Powerline Disable OFF

So another keypad, there is even the RF disabled :

>>> hallway_keypad.readFlags1()                                                                                                                                                                                      
sent msg: OUT:Cmd:0x62|toAddress:42.16.xx|messageFlags:0x0F=DIRECT:3:3|command1:0x1F|command2:0x01|                                                                                                                  
>>> read flags1 got flags1: Plock OFF|LED on TX ON|Resume Dim bit ON|LED ON|KeyBeep OFF|RF Disable ON|Powerline Disable OFF

**Comment by djfjeff** [comment]
BTW, the flags also get weird if I play with the keypad settings (adding a controller or responder for example) in insteon-terminal.

Is there a way that I can send raw Insteon command to set the flags back correctly?

**Comment by TD22057** [comment]
Only backlight is supported right now: https://github.com/TD22057/insteon-mqtt/blob/dev/doc/mqtt.md#get-and-set-operating-flags.  Adding the other flag controls should be pretty simple.  I can't see why doing the pair would change anything - they should be totally separate commands.

FYI I didn't see anything like this in my Keypadlincs.  I have a new one and one from a couple of years ago and the backlight stays the same - I didn't check the detailed flags but I will try to later this weekend.

**Comment by djfjeff** [comment]
Ok, I factory reset it and pair it again. The LED did not shutdown but the flags changed anyway in the output in insteon-terminal.

Maybe it's a display thing and the flags are not really changed. I think it is worth to investigate that anyway.

**Comment by TD22057** [comment]
Do the reset and pair then run get-flags using the command line tool.  I get eight 0's for the flags in my keypadlinc - not sure if that's the right default or not.

**Comment by djfjeff** [comment]
This is what I get with get-flags on both my keypad :

Commanding KeypadLinc device 42.17.xx (hallway_keypad) cmd=get_flags
Device 42.17.xx operating flags: 00001000
Operation complete

Don't really know what it means. The weird thing is insteon-mqtt report both of my keypad flags as : 00001000

However, insteon-terminal readflags1() command report different for both keypad.

First keypad : >>> read flags1 got flags1: Plock OFF|LED on TX OFF|Resum Dim bit OFF|LED ON|KeyBeep ON|RF Disable OFF|Powerline Disable OFF

Second keypad : >>> read flags1 got flags1: Plock OFF|LED on TX ON|Resume Dim bit ON|LED OFF|KeyBeep ON|RF Disable OFF|Powerline Disable OFF


I don't know who is right with the flags. It seems insteon-terminal change the flags everytime,

**Comment by TD22057** [comment]
I'm going to claim that it's an insteon-terminal issue.  Here's the docs from the keypadlinc dev guide:
   ```
   bit 0 = Plock
   bit 1 = LED on TX
   bit 2 = Resume Dim bit
   bit 3 = N/A
   bit 4 = LED OFF
   bit 5 = KeyBeep
   bit 6 = RF Disable
   bit 7 = Powerline Disable
   ```
So the only bit that insteon-mqtt is reporting set is bit 3 (N/A) which I would assume is fine.  I'm not sure what insteon-terminal is reading.

**Comment by djfjeff** [comment]
Thanks, make complete sense. I will go ahead and close this and try to see where insteon-terminal read this.
