### ISSUE TITLE
Request and Save Dev_Cat, Sub_Cat, and Firmware

### ISSUE THREAD

**Issue by krkeegan** [TD22057/insteon-mqtt#55]
There are differences in the features supported overtime for the same device.  We haven't come across it yet, but at some point we may need to know the details of a device in order to know what commands are supported.

**Comment by TD22057** [comment]
Some notes on this:  
1) add dev_cat, sub_cat, and firmware to the device database.  Default is None.
2) record those values when a linking message is received
3) add product data request message class and handler
4) in refresh(), if fields are not set in device database, send a product data request message as part of the refresh message sequence

**Comment by TD22057** [comment]
Fixed in PR #102
