### ISSUE TITLE
Should We Update the Link Delta After Writing to Device?

### ISSUE THREAD

**Issue by krkeegan** [TD22057/insteon-mqtt#56]
The delta on the device increments by 1 every time something is written to the eeprom on device.  This write can be a link entry or a change in flags.

Currently, when we write link entries to the device, we do not update our internal state of the device delta.  Since we know what we did, we could increment the internal state accordingly.  Of course, in doing so, we would not get the backup confirmation that the data was correctly written.

But I think this is necessary.  Eventually we are going to get to a state where we will want to write multiple link entries to a device serially.  In the current scheme, this would mean `get status, write, get status, refresh, write, ...`  That is a lot of overhead.  A better version is `get status, write, get status (delta matches our increment), write, ...`. An even better version is, `get status, write, write, write`, and only at the conclusion of a sequential writing process `get status` to confirm it matches our internal state.

Thoughts?

**Comment by TD22057** [comment]
Yeah - I thought about this but wasn't sure.  It would eliminate a lot of extra down loads but I was worried that it might get out of sync so I decided it was safer to just do the extra download.  I kind of feel like changing the device db doesn't happen very often (at least at my house) so it doesn't matter that much.  I could go either way with it to be honest.

**Comment by TD22057** [comment]
I haven't had time to really work on the scene management system (creating scenes in config files and pushing them out) but that's the scenario where your suggestion is really important (refresh, write, write, etc).  So when I have some more time and get back to working on that, I'll do some experiments and work on it then.

**Comment by TD22057** [comment]
After thinking about this more, I think we should update it.  If things get out of sync, a refresh with the force flag set will always reset things.  It's pretty annoying to have to keep reading the db out when we already know what state it's in.

**Comment by krkeegan** [comment]
Yeah, as you noted before, this is basically required if we are doing scene management.

**Comment by TD22057** [comment]
Looking through the code, this is now the behavior so I'm closing this.  (not sure if we made this mod during the scene code or if I did it earlier- either way it's there)
