### ISSUE TITLE
MQTT login username from config.yaml mismatch in code

### ISSUE THREAD

**Issue by tommyjlong** [TD22057/insteon-mqtt#59]
config.yaml 
   mosquitto login user name is "username".

In /cmd_line/util.py line 26, 27 
change:
    if config["mqtt"].get("user", None):
        user = config["mqtt"]["user"]
to: 
    if config["mqtt"].get("username", None):  
        user = config["mqtt"]["username"]

**Comment by lizaoreo** [comment]
If I wanted to make the changes myself, would I just navigate to /opt/insteon-mqtt/lib/python3.5/site-packages/insteon_mqtt/cmd_line, open up and edit the lines in util.py to reflect the changes and be done?  Or is there some kind of compile process to reflect the changes in the actual program?

**Comment by TD22057** [comment]
@lizaoreo - yes you can just edit the file and it work fine.  Or you can download the dev branch which now as the fix in it.
