### ISSUE TITLE
Create hass.io component for Home Assistant

### ISSUE THREAD

**Issue by TD22057** [TD22057/insteon-mqtt#63]
hass.io: https://www.home-assistant.io/hassio/
Tutorial: https://www.home-assistant.io/developers/hassio/addon_tutorial/
More config: https://www.home-assistant.io/developers/hassio/addon_config/

**Comment by larizzo** [comment]
You can use this to get you started: https://github.com/larizzo/docker-insteon-mqtt

**Comment by lnr0626** [comment]
Would you accept a PR for this? I'd find this useful for my own setup, and can work on it as time allows. Only limitation is that I am using one of the old hubs with the ethernet PLM interface, and don't have any USB/serial PLMs to test with.

**Comment by TD22057** [comment]
Sure - the device shouldn't make any difference in the docker set up.

**Comment by billchurch** [comment]
+1 for hassio add-on. I am happy to help formalize this as an add-on if needed. Has someone already done a PR on this?

**Comment by billchurch** [comment]
Answering my own question, looks like #76 has it

**Comment by TD22057** [comment]
I'm calling this closed w/ the merge of PR #76.  If there are any problems, please open a new issue.
