### ISSUE TITLE
Support for setting the on-level of a dimmer without turning the light on

### ISSUE THREAD

**Issue by lnr0626** [TD22057/insteon-mqtt#70]
This is possible programmatically using an extended set/get command (0x2e) with D2 = 0x06 and D3 as the on level, but it does not look like this is supported.

**Comment by TD22057** [comment]
Fixed.  set-flags command now supports on_level=[0-255] to set the on level for dimmers and keypadlincs.  Example command line:
  ` ./scripts/insteon-mqtt config.yaml set-flags dim1 on_level=128`
