### ISSUE TITLE
How do I view the log?

### ISSUE THREAD

**Issue by jtmoderate876** [TD22057/insteon-mqtt#73]
The only way I know is:
sudo systemctl status insteon-mqtt

but that, of course, gives me the service status plus just the last couple lines of log.

I am running on a rpi using 4/2018 standard raspbian and am not linux savvy.
Things that might be obvious to many may not be obvious to me.
Thx.

**Comment by TD22057** [comment]
https://unix.stackexchange.com/questions/225401/how-to-see-full-log-from-systemctl-status-service

Or look in your config.yaml file - there is an option to write the log to a specific file which you can then look at (use the command 'less /path/to/file').  I'd also recommend running it in a window with logs active for a little while to make sure things are working first. Once everything is operating fine, then make it a service and start it automatically.

**Comment by jtmoderate876** [comment]
I didn't know I could see the log if I didn't run as a service.
I will manually start it in  awindow and that should take care of it!
Thank you.

And by the way, I can't tell you how much hope insteon-mqtt has given me in what was a software mess.
The fact that you wrote it because of Home Assistant yet did such a great job that I can use it directly in node-red via MQTT is awesome.
I'm not a python programmer but your professional examples make me want to learn.
Thanks for the excellent work you do!
