### ISSUE TITLE
socket error when running on windows [fix included]

### ISSUE THREAD

**Issue by TLMNicolas** [TD22057/insteon-mqtt#78]
I tried running the insteon-mqtt under windows but a file descriptor error.
Looks like python sockets under windows dont support fileno() the same way as linux.
Found this heplful link https://github.com/docker/docker-py/issues/1997

The fix (not sure how propert is) that worked for me was based on that link as well.
I dont know how to wrap it in proper OS detection, but here is the change if it helps anyone else:

In network/Serial.py:
read_from_link()
```
#data = os.read(self._fd, self.read_buf_size)
data = self.client.read(self.read_buf_size)
```
write_to_link()
```
#num = os.write(self._fd, data)
num  = self.client.write(data)
```

Thanks for the project. Hoping to use it with HomeAssistant and my 2242 hub (HA's insteon plugin doesnt seem to work for my 2242 and it is always polling which i dont like)

**Comment by TLMNicolas** [comment]
Based on another issue I had on windows, here is an updated fix that should be able to properly detect OS and act accordingly...

Serial.py:
add this to the top with the other imports:
`import platform`

write_to_link()
```
if platform.system() != 'Windows':
              num = os.write(self._fd, data)
            else:
              num  = self.client.write(data)
```

read_from_link()
```
if platform.system() != 'Windows':
              data = os.read(self._fd, self.read_buf_size)
            else:
              data = self.client.read(self.read_buf_size)
```

Remember to keep proper indentation.

**Comment by TD22057** [comment]
FYI - I don't think this is going to fix the problem.  fileno is used by select to detect when there is data to read/write on the serial port.  If fileno isn't available on windows, that won't work.

**Comment by codewise-nicolas** [comment]
Im running the above fix now for about 48 hours, no problems no errors. Its working out very nicely.
Thanks so much for wiritng the program (its helped me because the insteon component for HA doesnt proeprly work with the 2242 hub I have)

**Comment by TD22057** [comment]
Fix submitted.
