### ISSUE TITLE
addon installation through hassio

### ISSUE THREAD

**Issue by shingle01** [TD22057/insteon-mqtt#82]
Trying to install the addon to hassio.  

I needed to create the path /addons/local/insteon-mqtt/ in order for the local addon to show in hassio addon store

When selecting install I get the following in the hassio system log:

> 18-09-11 02:44:09 INFO (SyncWorker_8) [hassio.docker.interface] Pull image lnr0626/amd64-insteon-mqtt tag 0.6.3.
> 18-09-11 02:44:13 ERROR (SyncWorker_8) [hassio.docker.interface] Can't install lnr0626/amd64-insteon-mqtt:0.6.3 -> 404 Client Error: Not Found ("manifest for lnr0626/amd64-insteon-mqtt:0.6.3 not found").

**Comment by TD22057** [comment]
@lnr0626 : any chance you can take a look at this?  I don't have any way to test hassio.  Thanks.

**Comment by shingle01** [comment]
Looks like its a version mismatch with the lnr0626/amd64-insteon-mqtt image.

I've reduced the version in config.json to 0.6.2 for now to allow me to pull the install.

**Comment by shingle01** [comment]
Might have to wait for @lnr0626 to bump the image version.  

Now getting the following error with a working version of Mosquito:

> 2018-09-11 05:05:03 DEBUG poll: Link connection failed MQTT localhost:1883
> 2018-09-11 05:05:13 DEBUG poll: Link connection attempt MQTT localhost:1883
> 2018-09-11 05:05:13 ERROR Mqtt: MQTT connection error to localhost 1883
> Traceback (most recent call last):
>   File "/usr/lib/python3.6/site-packages/insteon_mqtt/network/Mqtt.py", line 198, in connect
>     keepalive=self.keep_alive)
>   File "/usr/lib/python3.6/site-packages/paho/mqtt/client.py", line 768, in connect
>     return self.reconnect()
>   File "/usr/lib/python3.6/site-packages/paho/mqtt/client.py", line 895, in reconnect
>     sock = socket.create_connection((self._host, self._port), source_address=(self._bind_address, 0))
>   File "/usr/lib/python3.6/socket.py", line 724, in create_connection
>     raise err
>   File "/usr/lib/python3.6/socket.py", line 713, in create_connection
>     sock.connect(sa)
> OSError: [Errno 99] Address not available
> 2018-09-11 05:05:13 DEBUG poll: Link connection failed MQTT localhost:1883

**Comment by billchurch** [comment]
+1 on this. Have the same problem with 0.6.3 tag not existing on @lnr0626 's docker repo. adjusting the version in config.json to 0.6.2 seems to resolve it and it seems to work properly for now.

**Comment by lnr0626** [comment]
Sure thing, building the images now. Sorry for the delay, just saw this in my email.

**Comment by lnr0626** [comment]
the images for 0.6.3 are built and pushed, so you should be able to update now

**Comment by shingle01** [comment]
0.6.3 successfully deployed via addons thanks.

Strangely I'm still having issue connecting to mosquito via the addon.  I have install insteon_mqtt as a standalone process and it connects to mqtt fine...

> 2018-09-13 05:09:45 DEBUG poll: Link connection attempt MQTT localhost:1883
> 2018-09-13 05:09:45 ERROR Mqtt: MQTT connection error to localhost 1883
> Traceback (most recent call last):
>   File "/usr/lib/python3.6/site-packages/insteon_mqtt/network/Mqtt.py", line 198, in connect
>     keepalive=self.keep_alive)
>   File "/usr/lib/python3.6/site-packages/paho/mqtt/client.py", line 839, in connect
>     return self.reconnect()
>   File "/usr/lib/python3.6/site-packages/paho/mqtt/client.py", line 962, in reconnect
>     sock = socket.create_connection((self._host, self._port), source_address=(self._bind_address, 0))
>   File "/usr/lib/python3.6/socket.py", line 724, in create_connection
>     raise err
>   File "/usr/lib/python3.6/socket.py", line 713, in create_connection
>     sock.connect(sa)
> OSError: [Errno 99] Address not available
> 2018-09-13 05:09:45 DEBUG poll: Link connection failed MQTT localhost:1883

**Comment by lnr0626** [comment]
I've been trying to figure out a way to make the add-on stuff a little better. I set up a repository at https://github.com/lnr0626/hassio-addons . That at least removes the requirement to setup the local addon. I'll update the hassio instructions in a PR soon.

**Comment by TD22057** [comment]
@lnr0626 Since I can now build the docker images (#137), should I:
1) clone your repo https://github.com/lnr0626/hassio-addons and change it to point to td22057 and update the hassio docs?
2) remove the Dockerfile and hassio/ directories from insteon-mqtt since they are in the add ons repo?

**Comment by alfonsolsl** [comment]
i'm trying to give it a try to this add-on but was impossible to install for me on hass.io.

i tried: 

1. original first steps on hassio.
Error: `19-07-12 03:22:52 WARNING (MainThread) [hassio.store.data] Can't read /data/addons/local/insteon-mqtt/config.json: required key not provided @ data['arch']. Got None`

2. i manually add lines to the config.json

add: 
`"arch": ["armhf", "armv7", "aarch64", "amd64", "i386"],
"arch": ["armhf", "armv7", "aarch64", "amd64", "i386"],`

then i can see it on my add-on menu, but when i tried to install:

`19-07-12 03:36:58 ERROR (SyncWorker_5) [hassio.docker.interface] Can't install lnr0626/armv7-insteon-mqtt:0.6.8 -> 404 Client Error: Not Found ("pull access denied for lnr0626/armv7-insteon-mqtt, repository does not exist or may require 'docker login'").`

3. Add the hassio repo: Don't show me anything 
Error: 

`19-07-12 04:21:11 WARNING (MainThread) [hassio.store.data] Can't read /data/addons/git/400913fa/insteon-mqtt/config.json: required key not provided @ data['arch']. Got None`

Again.

So, i'm stuck.

Please can you help me out?

**Comment by alfonsolsl** [comment]
@TD22057 i made it using this config.json

`{
    "name": "Insteon MQTT",
    "description": "Python Insteon PLM <-> MQTT bridge",
    "slug": "insteon-mqtt",
    "version": "0.6.8",
    "startup": "services",
    "boot": "auto",
    "auto_uart": true,
    "map": ["config:rw"],
    "options": {},
    "schema": {},
    "arch": ["armhf"],
    "image": "td22057/{arch}-insteon-mqtt"
}`

please update the git config.json

**Comment by billchurch** [comment]
I created a PR for this: https://github.com/lnr0626/hassio-addons/pull/1

I beleive that @lnr0626 is the maintainer of the repo I think...

Until he accepts that PR, you could use my fork: https://github.com/billchurch/hassio-addons

**Comment by lnr0626** [comment]
It's merged, thanks for taking care of that

I've had a number of other things pop up and so haven't had any time to play around with HA for the past half year or so, sorry for not responding sooner @TD22057.

To answer your question, yes to number one - that'd be a good idea so you aren't reliant on me responding to fix issues. number two probably makes sense. I'm happy to continue responding to PRs in my repo for as long as is needed - though I'll likely only see things if I'm @ mentioned.

**Comment by TD22057** [comment]
I believe I have everything needed to handle hassio builds on my end now.  Updated version using my repo w/ the new config will be available in 0.6.9.
