### ISSUE TITLE
Hassio Update to 0.6.4 Fails

### ISSUE THREAD

**Issue by djryan012** [TD22057/insteon-mqtt#87]
I updated the hassio addon config to reflext the 0.6.4. It shows under hassio addon details their is an update. but when I click update it fails and the system logs shows this.

`18-11-27 00:55:51 INFO (SyncWorker_14) [hassio.docker.interface] Update Docker 0.6.3 with lnr0626/armhf-insteon-mqtt:0.6.4'

'18-11-27 00:55:51 INFO (SyncWorker_14) [hassio.docker.interface] Pull image lnr0626/armhf-insteon-mqtt tag 0.6.4.'

'18-11-27 00:55:53 ERROR (SyncWorker_14) [hassio.docker.interface] Can't install lnr0626/armhf-insteon-mqtt:0.6.4 -> 404 Client Error: Not Found ("manifest for lnr0626/armhf-insteon-mqtt:0.6.4 not found").`

**Comment by TD22057** [comment]
See #82.   @lnr0626 has to build those (see the path).  I haven't been able to get the hassio docker images to build at all on my machine so I can't update them (and I don't use hassio).

**Comment by lnr0626** [comment]
they're available now

**Comment by djryan012** [comment]
Thanks, Successfully updated to 6.4
