### ISSUE TITLE
Since release 0.84.1, dimmers will not work

### ISSUE THREAD

**Issue by Louis-Demers** [TD22057/insteon-mqtt#88]
Here is the error message which is logged

```
2018-12-14 01:29:32 ERROR MsgTemplate: Error rendering template '{ "cmd" : "{{json.state.lower()}}",
  "level" : {% if json.brightness is defined %}
               {{json.brightness}}
            {% else %}
               255
            {% endif %} }
' with data: {'value': 'ON', 'json': None}
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/insteon_mqtt/mqtt/MsgTemplate.py", line 186, in _render
    return template.render(data)
  File "/usr/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 1, in top-level template code
  File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'None' has no attribute 'state'
```
my lights.yaml contains

```
- name: "int_gf_masterbedroom_chandelier"
  friendly_name: "Master Bedroom Chandelier"
  platform: mqtt
  state_topic: "insteon/int_gf_masterbedroom_chandelier/state"
  command_topic: "insteon/int_gf_masterbedroom_chandelier/level"
  brightness: true
  
```
 platform used to be mqtt_json, but since 0.84, that became a configuration error and needed to be changed to just mqtt ....

seems very similar to 
[https://github.com/TD22057/insteon-mqtt/issues/3]

**Comment by shingle01** [comment]
Yep, I've got the same issue.  Thanks for the advice regarding changing mqtt_json to mqtt.  However I get the same error:

> 2018-12-14 19:51:36 INFO Dimmer: Dimmer message insteon/2f.31.e0/level b'ON'
> 2018-12-14 19:51:36 ERROR MsgTemplate: Error rendering template '{ "cmd" : "{{json.state.lower()}}",
>   "level" : {% if json.brightness is defined %}
>                {{json.brightness}}
>             {% else %}
>                255
>             {% endif %} }
> ' with data: {'value': 'ON', 'json': None}
> Traceback (most recent call last):
>   File "/opt/insteon-mqtt/lib/python3.6/site-packages/insteon_mqtt/mqtt/MsgTemplate.py", line 186, in _render
>     return template.render(data)
>   File "/opt/insteon-mqtt/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
>     return original_render(self, *args, **kwargs)
>   File "/opt/insteon-mqtt/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
>     return self.environment.handle_exception(exc_info, True)
>   File "/opt/insteon-mqtt/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "/opt/insteon-mqtt/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
>     raise value.with_traceback(tb)
>   File "<template>", line 1, in top-level template code
>   File "/opt/insteon-mqtt/lib/python3.6/site-packages/jinja2/environment.py", line 430, in getattr
>     return getattr(obj, attribute)
> jinja2.exceptions.UndefinedError: 'None' has no attribute 'state'

**Comment by TD22057** [comment]
Did you see the HA changes: https://www.home-assistant.io/components/light.mqtt/#json-schema---examples

I think you need to add a schema json line to the config.
```
- ...
  platform: mqtt
  schema: json
  ...
```

**Comment by Louis-Demers** [comment]
Ha Ha !  went over this page many times but never notice the new  **schema: json** entry that fixed everything.

Thank very much.

**Comment by TD22057** [comment]
Glad it was that simple.  I'll update the examples and send out something to the HA forum later today.

**Comment by Louis-Demers** [comment]
I would suggest that the 0.84.x release notes that announced the disappearance of the mqtt_json platform also announce the introduction of the "schema: jason " property

And the mqtt page should also explicitly mention the introduction of the "schema: jason " property, not just introducing it discretely into the examples.

Thanks  very much again

Louis Demers Eng.
louisdemers@mac.com

**Comment by vizonyc** [comment]
I have tried everything in this tread and I cant seem to get my dimmer to work and still getting this error. 018-12-18 01:05:12 INFO Dimmer: Dimmer message insteon/41.17.92/level b'off'
2018-12-18 01:05:13 ERROR MsgTemplate: Error rendering template '{ "cmd" : "{{json.state.lower()}}", "level" : {{json.brightness}} }' with data: {'value': 'off', 'json': None}
Traceback (most recent call last):
  File "/home/pi/insteon-mqtt/venv/lib/python3.5/site-packages/insteon_mqtt/mqtt/MsgTemplate.py", line 186, in _render
    return template.render(data)
  File "/home/pi/insteon-mqtt/venv/lib/python3.5/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/pi/insteon-mqtt/venv/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/insteon-mqtt/venv/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 1, in top-level template code
  File "/home/pi/insteon-mqtt/venv/lib/python3.5/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'None' has no attribute 'state'

what I have in my HA config:

**switch:
  - platform: mqtt
    schema: json
    name: Dinning Room
    state_topic: "insteon/41.xx.xx/state"
    command_topic: "insteon/41.xx.xx/level"
    brightness: true
    payload_on: "on"
    payload_off: "off"
    optimistic: true
    retain: true**

and in my insteon-mqtt config 

**dimmer:
     state_topic: 'insteon/{{address}}/state'
     state_payload: >
       { "state" : "{{on_str.upper()}}", "brightness" : {{level_255}} }
     on_off_topic: 'insteon/{{address}}/set'
     on_off_payload: '{ "cmd" : "{{value.lower()}}" }'
     level_topic: 'insteon/{{address}}/level'
     level_payload: >
       { "cmd" : "{{json.state.lower()}}",
         "level" : {% if json.brightness is defined %}
                      {{json.brightness}}
                   {% else %}
                      255
                   {% endif %} }**its probably something simple but I cant seem to find the error

**Comment by TD22057** [comment]
Are you sure you're actually using HA >= 84.1?  Obviously the meassage is not json:
`018-12-18 01:05:12 INFO Dimmer: Dimmer message insteon/41.17.92/level b'off'` so my guess would be that it's not actually running the HA version that supports the schema flag.  Either that or somehow one of the other config inputs is causing it to not send json.  It seems unlikely but maybe if you remove the lines that the docs don't say to use (payload_on, payload_off, optimistic) it will actually send the json.

I haven't updated yet so I can't debug very well - I'll update later this week and try it out.
