### ISSUE TITLE
Parse and Report NAK Details

### ISSUE THREAD

**Issue by krkeegan** [TD22057/insteon-mqtt#95]
When we receive a NAK, we should try and parse the cmd2 value and provide the user with a bit more information.  This is supposedly what the cmd2 value means:

0xFF = Sender’s device ID not in responder’s database
0xFE = Load sense detects no load (confirm this one)
0xFD = Checksum is incorrect
0xFC = Pre NAK in case database search takes too long
0xFB = illegal value in command

[http://cache.insteon.com/developer/i2CSdev-022012-en.pdf](http://cache.insteon.com/developer/i2CSdev-022012-en.pdf)

See #94 for a real world example of the issue.

**Comment by TD22057** [comment]
Fixed in PR #98
